### ISSUE TITLE
error (end-of-file) trying to parse answer:

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/merlin#1022]
Merlin dev - Linux x86_64

Since the introduction of: https://github.com/ocaml/merlin/pull/1018

_merlin-locate_ (or _merlin-type-enclosing_ ...) gives:
```
 merlin: error (end-of-file) trying to parse answer:
```
Known problem?

**Comment by brettgilio** [comment]
I can replicate this issue.

https://github.com/hlissner/doom-emacs/issues/1793

**Comment by brettgilio** [comment]
This issue is persisting. Is there any temporary work-around?

**Comment by osener** [comment]
@brettgilio see #1026

**Comment by rgrinberg** [comment]
@trefis I've pushed a hotfix to alleviate the suffering of the users. Feel free to tweak it as you wish

**Comment by Fourchaux** [comment]
:smiley:
