### ISSUE TITLE
Support OCaml 4.09

### ISSUE THREAD

**Issue by madroach** [ocaml/merlin#1028]
Please support OCaml 4.09

**Comment by douglastt** [comment]
+1

**Comment by vzaliva** [comment]
+1

**Comment by XVilka** [comment]
Should be closed as of https://github.com/ocaml/merlin/commit/b693c75bbef4fbdf67382af6d123f8a94ce4d124

**Comment by bschommer** [comment]
A release is still missing.

**Comment by kit-ty-kate** [comment]
This issue can be closed https://github.com/ocaml/opam-repository/pull/15420
