### ISSUE TITLE
Issues with type aliases

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/merlin#1030]
Consider the following snippet:

```ocaml
type age = int
let f (x: int) = x + 1
let g (x: age) = x + 1
```

When I ask Merlin for the definition of `age` it tells me ` type age = age`. When I ask it for the type of `f` and `g`, it says `age -> age` for both.

It would be great to see `int -> int` for `f` and  `age -> int` for `g`; also, it would be great to see `type age = int` for `age`.

**Comment by Fourchaux** [comment]
Note: with Merlin-dev, Emacs, tuareg-mode, OCaml 4.08.1
running _tuareg-eval-buffer_ gives:
 
```ocaml
type age = int
let f (x: int) = x + 1
let g (x: age) = x + 1;;

type age = int
val f : int -> int = <fun>
val g : age -> int = <fun>
```
All good, no?

**Comment by trefis** [comment]
@Fourchaux this has nothing to do with that.

@cpitclaudel the fact that it show "type age = age" is indeed surprising. Are you running with `-short-paths`?

**Comment by cpitclaudel** [comment]
Oh, yes, I am!  I've got the following in my .merlin, coming from Dune:

```
FLG -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -open SGALib__ -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -w -39 -open Backends -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A -w @a-4-29-40-41-42-44-45-48-58-59-60-40 -strict-sequence -strict-formats -short-paths -keep-locs -warn-error -A
```

Indeed, if I try in a directory with no .merlin, the problem goes away.  I was not aware of this option.
Should I open an issue on the OCaml compiler itself?

**Comment by trefis** [comment]
You can try, for the record, here is the way to reproduce with the toplevel:
```
# type age = int;;
type age = int
# let f (x : int) = x + 1;;
val f : age -> age = <fun>
# let g (x : age) = x + 1;;
val g : age -> age = <fun>
# #show age;;
type nonrec age = age
```
