### ISSUE TITLE
Vim: Add a command to print the path to the Merlin version being used

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/merlin#1038]
I'm trying to debug the usual flavour of ‘… not a compiled interface for this version’ bug in my setup that recently started occuring out of nowhere. (“/Users/ec/Sync/Code/excmd/_opam/lib/ocaml/array.cmi is not a compiled interface for this version of OCaml. It seems to be for an older version of OCaml.”)

Unfortunately, for the life of me, I can't figure out why Merlin is suddenly *not* using the copy of Merlin installed in my local switch (`echo $PATH` prints the correct, opam-adjusted value, with `/Users/ec/Sync/Code/excmd/_opam/bin` first, for instance.)

It'd be really helpful to have a command like `:MerlinEchoBinary` or something to show *where the Merlin server being invoked* resides! None of the information in `:MerlinDebugEnable` Because in a case like mine, it's clearly not using the version in `$PATH`, and I'm not sure why.

**Comment by trefis** [comment]
If all the requested command is supposed to do is print the path of the running executable, can't you just use `top`? (or whatever the windows equivalent is called)
