### ISSUE TITLE
Using the newest merlin for OCaml 4.08.1 via opam?

### ISSUE THREAD

**Issue by taquangtrung** [ocaml/merlin#1048]
Hi,

Is this possible to install the newest `merlin` (as of Oct 2019) for OCaml 4.08.1 via `opam`?

I'd like to use some new features and bugs fixed of `merlin`, but the version of `merlin` in `opam` is 3.3.2, which is quite outdated (released on Jul 15, 2019). And `merlin` hasn't supported OCaml 4.09.0 yet.

**Comment by mmottl** [comment]
I'm not sure about the current state of the repository and haven't tried this myself, but you might want to try `opam pin --dev-repo merlin`.  You can also try pinning specific versions that you believe might work (see `opam help pin`).

**Comment by taquangtrung** [comment]
@mmottl: Thanks a lot! The command that you gave works just fine for me.
