### ISSUE TITLE
Python 2 mode is selected in neovim even when it's not working

### ISSUE THREAD

**Issue by psafont** [ocaml/merlin#1050]
When neovim is compiled with +python, `python2-neovim` is not installed in the system, and `python3-neovim` is; Merlin selects Python2, even if it's broken and Python3 is available and working.

A workaround is to add `let g:merlin_python_version = 3` to `init.vim` so Python3 mode is always selected.

I encountered this when upgrading to Fedora 31 from 30 and was forced to uninstall `python-neovim`.

**Comment by XVilka** [comment]
This is very important since the days of Python 2 are counted - it will be dead in a month: https://pythonclock.org/

**Comment by XVilka** [comment]
Some rolling distributions removed python2-neovim from their repositories.
