### ISSUE TITLE
Merlin LSP: on 4.08 mouse hover doesn't work

### ISSUE THREAD

**Issue by Kakadu** [ocaml/merlin#1060]
I tested LSP in VsCode on 4.07 and 4.08. With 4.07 it works fine. But on 4.08 it doesn't guess type under cursor correctly (it seems that it guesses type of expression that contains identifier under cursor)

I tested only vscode, I couldn't manage to configure merlin+LSP on other editors

On this screenshot I set cursor location at `sz` identifier on line 326. After hover mouse event (see the log) it highlighted toplevel let binding  that contains this `sz`.

https://pasteboard.co/IHLyBvO.png

**Comment by XVilka** [comment]
Is this still reproducible with the recent updates?

**Comment by Kakadu** [comment]
It seems that it is better now
