### ISSUE TITLE
Errors on malformed syntax

### ISSUE THREAD

**Issue by epsilon-phase** [ocaml/merlin#1066]
Hi, I've noticed that if one makes a mistake while editing a file in emacs like
```ocaml
let a b:()->int*int=
  ...
```

You get a lot of chaff in the messages buffer in emacs like what you can find [here](https://pastebin.com/r0H4tbyq)(there's an awful lot of it).

The version string I have for the installed merlin is `The Merlin toolkit version ddf678dd, for Ocaml 4.08.1`

**Comment by trefis** [comment]
I believe that has been fixed now. :)
