### ISSUE TITLE
OCaml 4.10 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/merlin#1080]
The first beta for OCaml 4.10 is around the corner and Merlin is not compatible with this version just yet. Merlin is such an essential part of the ecosystem and I'm willing to help on this if some help is needed (for what I can do of course)

**Comment by brettgilio** [comment]
4.10.0 is released, now.

**Comment by kit-ty-kate** [comment]
@brettgilio this was the purpose of my work (to coordinate community packages and the compiler release), we had several discussion, prior to releasing OCaml 4.10.0, with the merlin team and there was too much to do still so we decided to separate the releases. We are well aware of this, future work will be dedicated to ease merlin's upgrade to a new version of the compiler, this is a tedious task.

In the meantime you can try this branch which compiles with OCaml 4.10: https://github.com/ocaml/merlin/branch/ocaml-4.10

or directly pick it up from my transition opam repository here: https://github.com/kit-ty-kate/opam-alpha-repository

**Comment by kit-ty-kate** [comment]
Closing as a preview version has been released a week ago
