### ISSUE TITLE
[Feature Request] Semantic highlighting support

### ISSUE THREAD

**Issue by hackwaly** [ocaml/merlin#1094]
Expect a command which query semantic types of all identifiers in document to add to the protocol.

VS Code is now adding semantic highlighting support.

See: https://github.com/Microsoft/language-server-protocol/issues/18#issuecomment-580209761 and https://github.com/microsoft/vscode-languageserver-node/blob/324d1039fef2b9622a9784c5cc49d9f6dfc11b65/protocol/src/protocol.sematicTokens.proposed.ts#L18

```TypeScript
export enum SemanticTokenTypes {
	comment = 'comment',
	keyword = 'keyword',
	string = 'string',
	number = 'number',
	regexp = 'regexp',
	operator = 'operator',
	namespace = 'namespace',
	type = 'type',
	struct = 'struct',
	class = 'class',
	interface = 'interface',
	enum = 'enum',
	typeParameter = 'typeParameter',
	function = 'function',
	member = 'member',
	property = 'property',
	macro = 'macro',
	variable = 'variable',
	parameter = 'parameter',
	label = 'label'
}
```

**Comment by XVilka** [comment]
It belongs to https://github.com/ocaml/ocaml-lsp, I think.
