### ISSUE TITLE
Merlin fails to compile source file using ppx_expect syntax extension

### ISSUE THREAD

**Issue by cgensoul** [ocaml/merlin#1095]
When a source file containing expectation tests is located in a subdirectory of the main directory of a dune library (using the (include_subdirs unqualified) dune stanza), merlin fails to compile the file reporting an IO error : file not found.

The project as a whole compiles fine via dune.

This [project](https://github.com/cgensoul/merlin-bug.git) is a minimal example exhibiting the bug.

I am using merlin via emacs merlin-mode (emacs 26.3).
I am using ocaml 4.09.0 and merlin version is 73e9771b for Ocaml 4.09.0.

**Comment by cgensoul** [comment]
Here is the merlin log :

# calling binary: "/home/cgensoul/.opam/4.09.0/bin/ocamlmerlin" with arguments: ("server" "errors" "-protocol" "sexp" "-log-file" "-" "-filename" "/home/cgensoul/code/ocaml/merlin-bug/lib/inc/test.ml").
# stdout
((assoc) (class . "return") (value ((assoc) (start (assoc) (line . 0) (col . -1)) (end (assoc) (line . 0) (col . -1)) (type . "typer") (sub) (valid . true) (message . "I/O error: test.ml: No such file or
directory"))) (notifications) (timing (assoc) (clock . 16) (cpu . 16) (query . 1) (pp . 0) (reader . 2) (ppx . 11) (typer . 2) (error . 0)))
# stderr
# 0.02 Mconfig - normalize
{
  "ocaml": {
    "include_dirs": [],
    "no_std_include": false,
    "unsafe": false,
    "classic": false,
    "principal": false,
    "real_paths": false,
    "recursive_types": false,
    "strict_sequence": true,
    "applicative_functors": true,
    "unsafe_string": false,
    "nopervasives": false,
    "strict_formats": true,
    "open_modules": [ "Merlin_bug" ],
    "ppx": [
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval":
          "/home/cgensoul/code/ocaml/merlin-bug/_build/default/.ppx/a2214fde0f9080164c234835e457c45a/ppx.exe --as-ppx --cookie 'library-name=\"merlin_bug\"'"
      }
    ],
    "pp": null,
    "warnings": {
      "actives": [
        1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 43, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62,
        63, 64, 65
      ],
      "warn_error": [
        1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        43, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62
      ]
    }
  },
  "findlib": { "conf": null, "path": [], "toolchain": null },
  "merlin": {
    "build_path": [
      "/home/cgensoul/.opam/4.09.0/lib/base",
      "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types",
      "/home/cgensoul/.opam/4.09.0/lib/base/caml",
      "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib",
      "/home/cgensoul/.opam/4.09.0/lib/fieldslib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/sexplib0",
      "/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte"
    ],
    "source_path": [
      "/home/cgensoul/.opam/4.09.0/lib/base",
      "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types",
      "/home/cgensoul/.opam/4.09.0/lib/base/caml",
      "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib",
      "/home/cgensoul/.opam/4.09.0/lib/fieldslib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/sexplib0",
      "/home/cgensoul/code/ocaml/merlin-bug/lib",
      "/home/cgensoul/code/ocaml/merlin-bug/lib/inc"
    ],
    "cmi_path": [],
    "cmt_path": [],
    "flags_applied": [
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval": [
          "-ppx",
          "/home/cgensoul/code/ocaml/merlin-bug/_build/default/.ppx/a2214fde0f9080164c234835e457c45a/ppx.exe --as-ppx --cookie 'library-name=\"merlin_bug\"'"
        ]
      },
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval": [
          "-open", "Merlin_bug", "-w",
          "@1..3@5..28@30..39@43@46..47@49..57@61..62-40",
          "-strict-sequence", "-strict-formats", "-short-paths", "-keep-locs"
        ]
      }
    ],
    "extensions": [],
    "suffixes": [
      { "impl": ".ml", "intf": ".mli" },
      { "impl": ".re", "intf": ".rei" }
    ],
    "stdlib": null,
    "reader": [],
    "protocol": "sexp",
    "log_file": "-",
    "log_sections": [],
    "flags_to_apply": [],
    "packages_to_load": [],
    "dotmerlin_loaded": [
      "/home/cgensoul/code/ocaml/merlin-bug/lib/.merlin"
    ],
    "packages_loaded": [],
    "packages_path": [],
    "failures": [],
    "assoc_suffixes": [
      { "extension": ".re", "reader": "reason" },
      { "extension": ".rei", "reader": "reason" }
    ]
  },
  "query": {
    "filename": "test.ml",
    "directory": "/home/cgensoul/code/ocaml/merlin-bug/lib/inc",
    "printer_width": 0,
    "verbosity": 0
  }
}
# 0.02 Pipeline - pop_cache
found entry for this configuration
# 0.02 New_commands - run(query)
{ "command": "errors" }
# 0.02 Mreader - run
extension("test.ml") = ".ml"
# 0.02 Mconfig - build_path
16 items in path, 16 after deduplication
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ocaml"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/caml"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/fieldslib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/sexplib0"
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte"
# 0.02 Mconfig - normalize
{
  "ocaml": {
    "include_dirs": [],
    "no_std_include": false,
    "unsafe": false,
    "classic": false,
    "principal": false,
    "real_paths": false,
    "recursive_types": false,
    "strict_sequence": true,
    "applicative_functors": true,
    "unsafe_string": false,
    "nopervasives": false,
    "strict_formats": true,
    "open_modules": [ "Merlin_bug" ],
    "ppx": [
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval":
          "/home/cgensoul/code/ocaml/merlin-bug/_build/default/.ppx/a2214fde0f9080164c234835e457c45a/ppx.exe --as-ppx --cookie 'library-name=\"merlin_bug\"'"
      }
    ],
    "pp": null,
    "warnings": {
      "actives": [
        1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 43, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62,
        63, 64, 65
      ],
      "warn_error": [
        1, 2, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        43, 46, 47, 49, 50, 51, 52, 53, 54, 55, 56, 57, 61, 62
      ]
    }
  },
  "findlib": { "conf": null, "path": [], "toolchain": null },
  "merlin": {
    "build_path": [
      "/home/cgensoul/.opam/4.09.0/lib/base",
      "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types",
      "/home/cgensoul/.opam/4.09.0/lib/base/caml",
      "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib",
      "/home/cgensoul/.opam/4.09.0/lib/fieldslib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/sexplib0",
      "/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte"
    ],
    "source_path": [
      "/home/cgensoul/.opam/4.09.0/lib/base",
      "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types",
      "/home/cgensoul/.opam/4.09.0/lib/base/caml",
      "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib",
      "/home/cgensoul/.opam/4.09.0/lib/fieldslib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib",
      "/home/cgensoul/.opam/4.09.0/lib/sexplib0",
      "/home/cgensoul/code/ocaml/merlin-bug/lib",
      "/home/cgensoul/code/ocaml/merlin-bug/lib/inc"
    ],
    "cmi_path": [],
    "cmt_path": [],
    "flags_applied": [
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval": [
          "-ppx",
          "/home/cgensoul/code/ocaml/merlin-bug/_build/default/.ppx/a2214fde0f9080164c234835e457c45a/ppx.exe --as-ppx --cookie 'library-name=\"merlin_bug\"'"
        ]
      },
      {
        "workdir": "/home/cgensoul/code/ocaml/merlin-bug/lib",
        "workval": [
          "-open", "Merlin_bug", "-w",
          "@1..3@5..28@30..39@43@46..47@49..57@61..62-40",
          "-strict-sequence", "-strict-formats", "-short-paths", "-keep-locs"
        ]
      }
    ],
    "extensions": [],
    "suffixes": [
      { "impl": ".ml", "intf": ".mli" },
      { "impl": ".re", "intf": ".rei" }
    ],
    "stdlib": null,
    "reader": [],
    "protocol": "sexp",
    "log_file": "-",
    "log_sections": [],
    "flags_to_apply": [],
    "packages_to_load": [],
    "dotmerlin_loaded": [
      "/home/cgensoul/code/ocaml/merlin-bug/lib/.merlin"
    ],
    "packages_loaded": [],
    "packages_path": [],
    "failures": [],
    "assoc_suffixes": [
      { "extension": ".re", "reader": "reason" },
      { "extension": ".rei", "reader": "reason" }
    ]
  },
  "query": {
    "filename": "test.ml",
    "directory": "/home/cgensoul/code/ocaml/merlin-bug/lib/inc",
    "printer_width": 0,
    "verbosity": 0
  }
}
# 0.02 Mconfig - build_path
16 items in path, 16 after deduplication
# 0.02 Pparse - apply_rewriter
running "/home/cgensoul/code/ocaml/merlin-bug/_build/default/.ppx/a2214fde0f9080164c234835e457c45a/ppx.exe --as-ppx --cookie 'library-name=\"merlin_bug\"'" from directory "/home/cgensoul/code/ocaml/merlin-bug/lib"
# 0.02 Mppx - changing_directory
/home/cgensoul/code/ocaml/merlin-bug/lib/inc
# 0.02 File_cache(Cmi_cache) - get_cached_entry
reusing "/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte/merlin_bug.cmi"
# 0.02 File_cache(Cmi_cache) - get_cached_entry
reusing "/home/cgensoul/.opam/4.09.0/lib/ocaml/stdlib.cmi"
# 0.02 Mconfig - build_path
16 items in path, 16 after deduplication
# 0.02 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ocaml
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ocaml"
# 0.02 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/base
# 0.02 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/base_internalhash_types"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/base/caml
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/caml"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/base/shadow_stdlib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/fieldslib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/fieldslib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_compare/runtime-lib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/collector"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/common"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_expect/config"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_here/runtime-lib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/config"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_inline_test/runtime-lib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/ppx_sexp_conv/runtime-lib"
# 0.03 stat_cache - reuse cache
/home/cgensoul/.opam/4.09.0/lib/sexplib0
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/.opam/4.09.0/lib/sexplib0"
# 0.03 stat_cache - reuse cache
/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte
# 0.03 File_cache(Directory_content_cache) - read
reusing "/home/cgensoul/code/ocaml/merlin-bug/_build/default/lib/.merlin_bug.objs/byte"
# 0.03 Mtyper - compatible_prefix
reusing 1 items, 0 new items to type
# 0.03 New_merlin - run(result)
{
  "class": "return",
  "value": [
    {
      "start": { "line": 0, "col": -1 },
      "end": { "line": 0, "col": -1 },
      "type": "typer",
      "sub": [],
      "valid": true,
      "message": "I/O error: test.ml: No such file or\ndirectory"
    }
  ],
  "notifications": [],
  "timing": {
    "clock": 16,
    "cpu": 16,
    "query": 1,
    "pp": 0,
    "reader": 2,
    "ppx": 11,
    "typer": 2,
    "error": 0
  }
}

**Comment by let-def** [comment]
Inclusions are not yet supported (the language merlin use for describing build context does not support this feature, it is dune specific).
We plan to fix that in the medium term but there is not much you can do beside avoiding inclusion.

**Comment by cgensoul** [comment]
Duly noted. Thanks for your answer.

**Comment by frejsoya** [comment]
This bug can be reproduced when not using using `include_subdirs`.
