### ISSUE TITLE
Merlin search counsel/ivy integration

### ISSUE THREAD

**Issue by Gopiandcode** [ocaml/merlin#1097]
I've implemented counsel/ivy integration with the merlin search functionality:

![merlin_counsel_integration](https://user-images.githubusercontent.com/23038502/75086215-a5afbf80-5529-11ea-90b5-53ece6ba9ddc.gif)

Unlike the existing merlin search function, it runs the merlin process asynchronously so it doesn't hang emacs while loading the results.

Would the code for this be a useful addition to the wiki?

**Comment by trefis** [comment]
> Would the code for this be a useful addition to the wiki?

Why not open a PR instead?

**Comment by Gopiandcode** [comment]
Sure will do.
