### ISSUE TITLE
mac address duplication with Aimesh network

### ISSUE THREAD

**Issue by Stevenyu1982** [ocaml/merlin#1098]
i have a aimesh setup (asus86u+asus68u) at home, got some strange problem. 

from dmesg, i got this reported, this caused my network become very slow until unusable.
br0: received packet on eth5 with own address as source address
br0: received packet on eth5 with own address as source address
br0: received packet on eth5 with own address as source address
br0: received packet on eth5 with own address as source address
br0: received packet on eth5 with own address as source address
br0: received packet on eth5 with own address as source address

From ifconfig , there are many device shared same mac address,  i am able to use ifconfig eth0 hw ether "some mac address" to fix it. but i am not able to save the change. 
stevenadmin@RT-AC86U-B338:/tmp/home/root# ifconfig |grep -i hwaddr
bcmsw     Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
br0       Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
eth0      Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
eth1      Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
eth2      Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
eth3      Link encap:Ethernet  HWaddr 044:C4:B7:B3:38
eth4      Link encap:Ethernet  HWaddr 04:D4:C4:B7:B3:38
eth5      Link encap:Ethernet  HWaddr 04:D4:C4:B7:B3:38
eth6      Link encap:Ethernet  HWaddr 04:D4:C4:B7:B3:3C
spu_ds_dummy Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
spu_us_dummy Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
stevenadmin@RT-AC86U-B338:/tmp/home/root#

also tried many nvram set command, but non of them are work

stevenadmin@RT-AC86U-B338:/tmp/home/root# nvram show |grep -i eth
size: 63318 bytes (67754 left)
acs_ifnames=eth5 eth6
amas_ethernet=3
br0_ifnames=eth0 eth1 eth2 eth3 eth4 eth5 eth6
bsd_ifnames=eth5 eth6
dpsta_all_ifnames=eth5 eth6
eth_ifnames=eth0
lan_ifnames=eth0 eth1 eth2 eth3 eth4 eth5 eth6
qos_method=0
sta_ifnames=eth5 eth6
sta_phy_ifnames=eth5 eth6
wired_ifnames=eth1 eth2 eth3 eth4
wl0_bsd_if_select_policy=eth6
wl0_ifname=eth5
wl1_bsd_if_select_policy=eth5
wl1_ifname=eth6
wl_ifname=eth5
wl_ifnames=eth5 eth6
wps_config_method=0x784
wps_env_buf=SET wps_method="2" wps_sta_pin="00000000" wps_action="3" wps_config_command="1" wps_pbc_method="2" wps_ifname="eth5

**Comment by hhugo** [comment]
Wrong project

**Comment by Stevenyu1982** [comment]
so where should i ask for help ?

**Comment by let-def** [comment]
Maybe https://github.com/RMerl/asuswrt-merlin ?
