### ISSUE TITLE
Merlin could be a tiny bit more robust when handling errors on Destruct

### ISSUE THREAD

**Issue by giltho** [ocaml/merlin#1102]
Hi ! :)

See discussion [here](https://github.com/ocaml/ocaml-lsp/issues/115) and [here](https://github.com/ocaml/ocaml-lsp/issues/115) with @rgrinberg

Maybe Merlin could be a bit more robust when handling errors on Destruct ?

**Comment by voodoos** [comment]
Merlin is now a _bit_ more robust: we replaced the unhandled exception  `Destruct.Wrong_parent` from `get_every_pattern` by a message saying that calling destruct there is not allowed. (in #1178)

Not sure if that is robust-enough to close this issue :eyes:

**Comment by trefis** [comment]
Let's say it is.

@giltho if you still notice issues, do not hesitate to open new issues (with the particular errors that are not being caught properly, in which situations, etc).
