### ISSUE TITLE
Crash on OCaml 4.10.0, merlin 3.3.4~4.10preview1 (latest) 

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#1103]
When I try using the latest Merlin version I just get a crash when trying to use MerlinTypeOf or MerlinLocate (probably other commands as well).

`Uncaught exception Magic_numbers.Cmi.Error in initial_env.open_module: Magic_numbers.Cmi.Error(_)`

I might have jumped the gun on this version; maybe this is a known problem. Thought it was worth reporting though.

**Comment by Jumblemuddle** [comment]
I'm running into the same issue. I can't seem to figure out what versions of `ocaml`, `reason`, and `merlin` to downgrade to in order to get it working.

**Comment by ddickstein** [comment]
I think this happened when I tried to jump to definition after upgrading my opam switch and merlin version but didn't rebuild my dune project. After rebuilding the crash went away.
