### ISSUE TITLE
Wrong result on a function named 'unit'

### ISSUE THREAD

**Issue by Julow** [ocaml/merlin#1109]
Hi,

```ocaml
let rec unit x = x

and f : Unknown_module.t -> _ =
 fun x -> x

let g x = unit x
```

In this file, asking `:MerlinTypeOf` on any of the two `unit` occurrences gives:

```
type unit = ()
```

This happens only if `Unknown_module` is not found.

**Comment by trefis** [comment]
@voodoos can you give an update on the status of this one?

**Comment by voodoos** [comment]
I would say it is mostly fixed ?

https://github.com/ocaml/merlin/tree/master/tests/test-dirs/type-enclosing/recovery

Merlin gives two answers, the first one is correct, the second not really:
```

  $ $MERLIN single type-enclosing -position 5:11 -verbosity 0 \
  > -filename ./issue1109.ml < ./issue1109.ml | jq ".value[0:2]"
  [
    {
      "start": {
        "line": 5,
        "col": 10
      },
      "end": {
        "line": 5,
        "col": 14
      },
      "type": "'a -> 'b",
      "tail": "no"
    },
    {
      "start": {
        "line": 5,
        "col": 10
      },
      "end": {
        "line": 5,
        "col": 16
      },
      "type": "'a",
      "tail": "no"
    }
  ]
```

**Comment by trefis** [comment]
Meh.
But yeah, let's close this for now. This should get better with a better recovery.
