### ISSUE TITLE
Object type is returned when asking for only the type of a method since OCaml 4.08

### ISSUE THREAD

**Issue by voodoos** [ocaml/merlin#1124]
Given the following code where `|` symbolizes the cursor:
```ocaml
let s = object
  val mutable v = [0; 2]
  method p|ush hd = v <- hd :: v
end
```

Merlin gives the type of the whole object  `< push : int -> unit >` instead of the type of the `push` method `int -> unit`.

When using OCaml versions < 4.08 the returned type is the correct one.

**Comment by trefis** [comment]
Looking at the testsuite, this issue is still present on OCaml ≥ 4.08.
