### ISSUE TITLE
Merlin doesn't autocomplete records in other files

### ISSUE THREAD

**Issue by jfrolich** [ocaml/merlin#1140]
If we have a module that contains records, the records will be autompleted in the same module, but when we try to access it from a different file it won't work.

For instance if we have `Test01.ml`:

```ocaml
type otherColors = {
  primary: string;
}
type t = {
  primary: string;
  secondary: string;
  otherColors: otherColors;
}
let colors =
  {
    primary = "red";
    secondary = "orange";
    otherColors = { primary = "blue" }
  }
```

Inside this file `colors.` will be able to autocomplete with the available fields. However if we are in another module and do `Test01.colors.` autocomplete will not show any options. Now if we bring the Test01 module in scope by doing `Test01.colors.Test01.` the options appear again. However if we do `Test01.colors.Test01.otherColors.` we again have no options. We need to bring the module in scope again by using `Test01.colors.Test01.otherColors.Test01.`.

It would be great if inference would work a little better and it would just be able to autocomplete these records.

**Comment by jfrolich** [comment]
@rgrinberg

**Comment by jfrolich** [comment]
A local open does make it work, but when we do `Test01.(colors.otherColors)` we don't get an accurate results (it basically lists all fields of all records). `Test01.(colors.otherColors.Test01.` does autocomplete correctly (`primary`).

**Comment by voodoos** [comment]
What editor and extension are you using ?

I don't have this issue using vscode with OCaml Platform (and ocamllsp):

![image](https://user-images.githubusercontent.com/5031221/84486498-c600b700-ac9d-11ea-8cb0-c6d96d33814d.png)

**Comment by jfrolich** [comment]
I use VSCode and OCaml Platform. Which exact versions are you using? I'd love to resolve this!

**Comment by voodoos** [comment]
- System:  WSL 2 
- vscode: 1.45.1
- ocaml-platform: 0.7.0
- ocamllsp: a83bd0921b7e11de92e878f55b6447918dbb841c

I think these are all the latest versions.

**Comment by jfrolich** [comment]
I am on Mac OS X. I tested with the same configuration but no dice.
Did you try to do this in different files (to be sure?)

**Comment by ulugbekna** [comment]
Autocompletion for records in different files works for me. I have the following configurations

- MacOS Catalina
- OCaml 4.09
- ocamllsp version `a83bd09` via `ocamllsp --version`
- vscode-ocaml-platform 0.7.0

![image](https://user-images.githubusercontent.com/16353531/84595330-9eede500-ae57-11ea-9aa0-3102794f8cb5.png)

**Comment by jfrolich** [comment]
Anyone has it working in combination with Bucklescript? Perhaps that is the problem?

**Comment by jfrolich** [comment]
Ah I think I found it. It works in OCaml syntax, but it does not work in Reason syntax!
