### ISSUE TITLE
How do I lint a single file?

### ISSUE THREAD

**Issue by dsalaza4** [ocaml/merlin#1141]
I have taken a look at the doc but it looks like merlin does a lot more than expected.

Is there a way to run strict linting on a single file via command line?
Something like:

```
ocamlmerlin lint --all-rulles --config=strtictest --fail-on-warnings example.ml
```

Thanks!

**Comment by voodoos** [comment]
You can try running:

`ocamlmerlin single errors -filename example.ml -w @A < example.ml`

- `single` means that you do not want to start merlin's server
- `errors` is the merlin command to list warnings and errors in some file
- `-w @A` is a compiler flag setting all warnings as fatals (see [`-w warning-list`](https://caml.inria.fr/pub/docs/manual-ocaml/comp.html#s:comp-options))

(The protocol is documented [here](https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md))

Output will be raw json, you can format it by piping to `jq` for example.

However if you don't plan to have a "programmatic" usage of merlin you should probably use one of the editor extensions for vim, emacs, vscode, etc.

Also, if by "linting" you actually mean "formatting", [`ocamlformat`](https://github.com/ocaml-ppx/ocamlformat) might be what you are looking for.

**Comment by dsalaza4** [comment]
@voodoos Thank you!
