### ISSUE TITLE
ocamlmerlin-ser bock multitimes

### ISSUE THREAD

**Issue by kailiangji** [ocaml/merlin#1148]
When I am writing ocaml codes, the emacs blocked suddenly many times. when I use `top` to check the cpu status, I found that ocamlmerlin-ser full filles the cpu.

**Comment by trefis** [comment]
We're going to need a bit more information to help you debug this: is there a particular merlin command that causes these freezes? And are you invoking this command manually or is it something that your editor does without your knowledge?
