### ISSUE TITLE
Compiler warnings are not displayed in vim with Syntastic + Merlin + Dune

### ISSUE THREAD

**Issue by hcnelson99** [ocaml/merlin#1154]
# Summary
When my code has errors, they are displayed as expected by syntastic in vim. However, warnings are not displayed in vim by syntastic. I would like merlin + syntastic to display both errors and warnings.

# Versions
ocamlmerlin version: `The Merlin toolkit version v3.3.6, for Ocaml 4.10.0`
dune version: `2.6.1`
syntastic version: `63b74a7473ec01548298284c210fee0a78a6156d` (latest master)
vim version: `8.2` (`g:merlin_ignore_warnings` is false)
opam version: `2.0.7`
opam switch:
```
#  switch   compiler             description
→  default  ocaml-system.4.10.0  default
```
Relevant editor setup (.vimrc):
```
Plug 'vim-syntastic/syntastic'

...

if executable('opam') && isdirectory(fnamemodify('~/.opam', ':p'))
  let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
  execute "set rtp+=" . g:opamshare . "/merlin/vim"
  let g:syntastic_ocaml_checkers = ['merlin']
  let g:merlin_textobject_grow   = 'm'
  let g:merlin_textobject_shrink = 'M'
endif
```

# Reproducing 
To reproduce, in some test directory create the following files:

dune:
```
(library
    (name test)
    (libraries core)
    (preprocess (pps ppx_jane)))
```

dune-project:
```
(lang dune 2.6)
```

test.ml
```
let unused = 0
```

test.mli
```
(* This file purposefully empty. *)
```

# Observed behavior
```
$ dune build
File "test.ml", line 1, characters 4-10:
1 | let unused = 3
        ^^^^^^
Error (warning 32): unused value unused.
```
but the warning does not show up in vim from merlin. If you write a type error like `let unused : string = 3` then the compile error does show up in both dune and vim.

# Expected behavior

Merlin indicates there is a warning inside of vim like how it does for errors.

# (Side note)
Note: Dune autogenerates a `.merlin` file automatically. Its last two lines are:
```
FLG -ppx '/home/henry/test/_build/default/.ppx/57ef275c515ec1fe105f6ff0979f5a61/ppx.exe --as-ppx --cookie '\''library-name="test"'\'''
FLG -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs
```

I tried messing with the `-w` flag to try to get merlin to show warnings (deleting it, removing 32, etc.) but this didn't seem to work which is why I'm filing this bug here and not with dune. If this is a dune error, let me know and I'll move over there.

Thanks so much for merlin! I really enjoy using it!

**Comment by voodoos** [comment]
I am not a vim user so maybe others like @let-def will have more interesting insight.

Have you tried using merlin without syntastic ? Is the same issue happening without it ?
The syntastic module for OCaml is [3 years old](https://github.com/vim-syntastic/syntastic/tree/master/syntax_checkers/ocaml), I would not be surprised if the protocol changed since then... 

The `-w` compiler flag that dunes adds is turning most warnings into errors (that is what the [`@` means](https://caml.inria.fr/pub/docs/manual-ocaml/comp.html#s:comp-options)). Thus the "unused" warning is reported as an error, and I find it surprising that syntastic does not report it if it is reporting otherslike typing errors.

**Comment by hcnelson99** [comment]
If I disable the syntastic plugin entirely and manually call `:MerlinErrorCheck`, I get the same behavior (errors are displayed but warnings are not displayed in the pop up editor split).

**Comment by trefis** [comment]
This is actually the intended behavior: warnings 32 to 39, as well as 60, are disabled (on purpose) in merlin.

**Comment by Kerl13** [comment]
Hi @trefis would you mind elaborating on this?

I was really puzzled about merlin ignoring some parts of my `.merlin` files until I find this issue. What is the reason behind merlin overriding the warning flags? Is there a way to bypass this behaviour and get my warnings back? I think I used to have them but they stopped showing up at some point.
Also is this documented somewhere? I'm sorry I didn't find it.

Cheers!
