### ISSUE TITLE
Release 3.3.7 doesn't build with dune 1.x

### ISSUE THREAD

**Issue by marsam** [ocaml/merlin#1157]
The latest merlin release [v3.3.7](https://github.com/ocaml/merlin/releases/tag/v3.3.7) doesn't build with dune 1.x stable (1.11.4). 
The opam file indicates that it should build with dune 1.11.4 https://github.com/ocaml/merlin/blob/v3.3.7/merlin.opam#L14

Error:
```
⋮
building
File "_build/.dune/default/src/analysis/dune", line 2, characters 0-52:
2 | (rule
3 |  (action (copy# destruct.ml.old destruct.ml)))
Error: fields targets, target are all missing (exactly one is needed)
```

**Comment by trefis** [comment]
Indeed, thanks for spotting this.
We've fixed the issue in recent releases.
