### ISSUE TITLE
Emacs: `merlin-type-enclosing` works with M-x but not with C-c C-t

### ISSUE THREAD

**Issue by Isweet** [ocaml/merlin#1164]
Say I have a file.

**foo.ml**
```ocaml
let foo x y = x + y
```

If I put my cursor over the formal parameter `x` and enter `C-c C-t` I am told: "No definition found." However, if I leave my cursor where it is and do `M-x merlin-type-enclosing` I am told: "int".

Emacs version: GNU Emacs 26.2
Merlin version: 3.3.8

I don't have anything customized, I just use the setup provided by `opam-user-setup.el`.

**Comment by let-def** [comment]
You can use `C-h k C-c C-t` to see what the key is bound to.

**Comment by Isweet** [comment]
Ah! I didn't bother to check that, just looked at `M-x describe-mode` for Merlin. Apparently `ocp-index-print-info-at-point` is bound to `C-c C-t`.

Thanks, and sorry for my Emacs ignorance!

**Comment by let-def** [comment]
No problem, you are welcome :). It is easy to get lost in Emacs.
