### ISSUE TITLE
Missing dependency on num(?)

### ISSUE THREAD

**Issue by reynir** [ocaml/merlin#1196]
I was upgrading my packages, and I suspect merlin needs to declare `num` a dependency in its opam file. The error I had was `lib/ocaml/arith_flags.cmx: No such file or directory`. It seems that file belongs to the `num` package since OCaml 4.06.0. Running `opam install --restore` fixed the problem for me.

``` shell
[SNIP]
∗ installed num.1.4
∗ installed ocaml-migrate-parsetree.2.1.0
∗ installed stdlib-shims.0.1.0
[ERROR] The compilation of merlin failed at "/home/reynir/.opam/opam-init/hooks/sandbox.sh build dune
        build -p merlin -j 7".
∗ installed zarith.1.11
[SNIP]

#=== ERROR while compiling merlin.3.4.1 =======================================#
# context     2.0.3 | linux/x86_64 | ocaml-base-compiler.4.10.1 | https://opam.ocaml.org#a13cda17
# path        ~/workspace/albatross/_opam/.opam-switch/build/merlin.3.4.1
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p merlin -j 7
# exit-code   1
# env-file    ~/.opam/log/merlin-9635-e3ca28.env
# output-file ~/.opam/log/merlin-9635-e3ca28.out
### output ###
# Error: stat:
# /home/reynir/workspace/albatross/_opam/lib/ocaml/arith_flags.cmx: No such
# file or directory



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build merlin 3.4.1
└─ 
[SNIP]
```

**Comment by voodoos** [comment]
To my knowledge Merlin does not use any module of the Num library. The fact that the restore option of `opam` fixed the problem give me the impression that your switch had an other issue.

> --restore
>         Attempt to restore packages that were marked for installation but
>          have been removed due to errors

**Comment by reynir** [comment]
> And according to the log you gave it looks like num was installed by opam before Merlin.

Yes, it looks like so, but the upgrade was using many processes/threads. I wouldn't trust the order, especially since the referred file resided in `num`.

What other issues do you have mind?

> Are you able to reproduce the issue ?

No, unfortunately I did not note down the state of opam before and after the upgrade.

**Comment by voodoos** [comment]
Okay, I close this issue for now but don't hesitate in reopening it if it happens again !
