### ISSUE TITLE
Go-to-definition of a module defined using a functor leads to functor not module

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/merlin#1199]
Go-to-definition of a module defined using a functor shows the functor used to define the module instead of the place where the module was defined. 

Example:

```ocaml
1 module Make () = struct
2   let u = ()
3 end
4
5 module T = Make ();;
6 
7 let () = T.u
```

Go-to-definition on `T` in `T.u` in goes to the definition of `Make` (line 1) instead of `T` (on line 5). 

I think that's not the expected behavior.

Using the (latest) ocamllsp 1.2.0-5-g68a0237. (I think that ocaml-lsp relies on merlin for this feature, so reporting here)

**Comment by trefis** [comment]
Definitely not the expected behavior, thanks for the report!
