### ISSUE TITLE
Older versions of OCaml are not supported in master

### ISSUE THREAD

**Issue by mrmr1993** [ocaml/merlin#1209]
[This commit](https://github.com/ocaml/merlin/commit/a6c38f1548e39768be7dc4903e659d660b46875c) seems to be responsible. I can't find a relevant pull request for that change, or a discussion describing the rationale.

This was frustrating when trying to make a change and test it on my primary OCaml switch (4.07.1).

/cc @trefis since this was your change.

**Comment by trefis** [comment]
Hi,

Indeed this happened recently without any public discussion (though there was *some* amount of private discussion).
Before the next release, I intend to write a public explanation of this change, and the reason why it happens, as well as the "support story" going forward. But I haven't got around to it just yet.

Sorry for the inconvenience, I hope it didn't make things too difficult for you.

PS: I'll update (and close) this issue with a link to the said write-up once I post it somewhere.

**Comment by voodoos** [comment]
I guess we can close this issue ?
