### ISSUE TITLE
Can merlin be aware of a source to source pre-processor?

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/merlin#1239]
Hello,
In batteries, we have the following line-prefix pre-processor directives:

```
##V=VERSION##
##V<VERSION##
##V<=VERSION##
##V>VERSION##
##V>=VERSION##
```

Where VERSION is an ocaml version like 4.10.0.

Can merlin be made aware that some source files need to be processed by a source to source pre-processor
before they become valid ocaml code?
Or, that a whole project (whatever the source file) uses a pre-processor.

Regards,
F.

**Comment by voodoos** [comment]
Isn't that the role of the `-pp` flag of the compiler ?

```
-pp command
    Cause the compiler to call the given command as a preprocessor for each source file. The output of command is redirected to an intermediate file, which is compiled. If there are no compilation errors, the intermediate file is deleted afterwards. 
 ```
 
 If I am not mistaken (@let-def ?), adding a `FLG` directive with such flag to your `.merlin` should work ?
 Merlin has a special processing of these plags.

**Comment by UnixJunkie** [comment]
Thanks, I'll try.

**Comment by UnixJunkie** [comment]
I guess it's working; merlin did not complain and apparently is still working in emacs after the .merlin change.
