### ISSUE TITLE
410 branch ?

### ISSUE THREAD

**Issue by nojb** [ocaml/merlin#1245]
If I understand correctly from https://tarides.com/blog/2021-01-26-recent-and-upcoming-changes-to-merlin there should be a branch for each supported version of OCaml. I can see `409`, `411` and `412`, but no `410` ? Which branch should I use for 4.10 ? Thanks!

**Comment by trefis** [comment]
Hi,

You understood the article correctly, however as we've not yet done the release which removes the support for older version, our branches are not in place yet.
The branches you're listing are actually stale development branches from when we were actively adding our initial support for this versions of OCaml.

I'll sort all that out in the next few days and ping this issue once done.

**Comment by nojb** [comment]
Thanks for the info!

**Comment by voodoos** [comment]
I just created a `3.4`  branch starting with the tag `v3.4.2` which will track patches to the support of compilers <= 4.10

**Comment by trefis** [comment]
And the "Manually building and installing Merlin" section of the README has been updated with the relevant information and branch names.

**Comment by nojb** [comment]
Thanks!
