### ISSUE TITLE
"Project isn't built." when jumping to installed sources

### ISSUE THREAD

**Issue by emillon** [ocaml/merlin#1251]
Hi,

I'm using merlin 3.4.2 and dune 2.8.2 (which means I'm not using `.merlin` files anymore).

When I'm using "jump to definition" and the destination is an installed file, the following error appears:

> Project isn't built. (Try calling `dune build`.)

For example if the cursor is on `Cmdliner.Term`, I'm typing `gd` in vim and this opens `/path/to/_opam/lib/cmdliner/cmdliner.mli` but displays this error in the status line (and an error marker on the first line).

cc @voodoos who asked me to report this :)

Thanks!

**Comment by rgrinberg** [comment]
Correct me if I'm wrong, but I think this should be reported in the dune repo. `$ dune ocaml merlin` can report the appropriate information for installed sources from the `dune-package` file.
