### ISSUE TITLE
merlin + dune + windows hangs

### ISSUE THREAD

**Issue by nojb** [ocaml/merlin#1256]
I'm trying `merlin` 3.4.2 with `dune` 2.8.2 under native Windows (msvc) on Cygwin (no `opam`). When launching `merlin` the first time (ie the server is not running) under `emacs` the whole process hangs waiting for the spawned `dune` process to finish. If I open a follow-up session then `merlin` seems to work as expected. If I stop the server, the hanging behaviour comes back.

Glad to provide more details if it helps debugging.

**Comment by nojb** [comment]
(same problem when using `dot-merlin-reader` by the way)

**Comment by nojb** [comment]
I did a bit of debugging, it seems this call
https://github.com/ocaml/merlin/blob/59965113df9f7af1bb68d9b86ab8abcd768227a4/src/frontend/ocamlmerlin/ocamlmerlin.c#L638
is blocking... but am not sure what that means yet...

**Comment by voodoos** [comment]
Should be fixed with the latest release (4.2 / 3.5.0). Please reopen if the issue persists.
