### ISSUE TITLE
Merlin in vim no longer jumps to compile error locations when error-style is set to contextual (new default)

### ISSUE THREAD

**Issue by msprotz** [ocaml/merlin#1258]
I was able to workaround this by doing `export OCAML_ERROR_STYLE="short"` but it's slightly cumbersome. This is compounded by the fact that my version of ocamlfind seems unaware of this option and therefore complains when I add to my list of default command-line flags.

**Comment by trefis** [comment]
I'm not sure this has anything to do with merlin.
So just to confirm, are you speaking of what happens when you call `:MerlinErrorCheck`, or something that you think should happen when you build your project on the side (with dune or something of the sort)?

**Comment by msprotz** [comment]
thanks Thomas for responding so promptly!

I recently set up a new machine, with upgraded versions of ocaml, merlin, etc.

Previously, I would do `:make` then some error messages would be printed within vim, vim would pick up on them and immediately jump to the error location. Via the `efm` variable. 

The format of error messages changed in recent version of OCaml, which broke this.

But I thought Merlin would set this variable appropriately for OCaml files? Is it not the case?

Thanks!

Jonathan

**Comment by msprotz** [comment]
Ok, this is entirely my fault -- I confused the roles of merlin vs ocaml-vim and thought the former was in charge of `efm` instead of the latter... closing this. Sorry for the noise.
