### ISSUE TITLE
How can I get merlin to treat files with unusual names "normally"?

### ISSUE THREAD

**Issue by fdopen** [ocaml/merlin#1262]
dune 2.8 no longer generate `.merlin` files. Files with unusual names are now not longer treated in the usual way, e.g:

`ocamlmerlin single dump-configuration -filename msource.foo.ml < /dev/null | jq`:
```
    "merlin": {
      "build_path": [],
      "source_path": [],
      "cmi_path": [],
      "cmt_path": [],
      "flags_applied": [], ...
```

With `.merlin` files however, `msource.foo.ml` was processed like `msource.ml` (build_path, source_path, etc. are filled as expected and type hints, etc. are provided in the usual way.)

How do I get the old behavior back under the new setup?

**Comment by voodoos** [comment]
Thanks for your report.

How are these files compiled ? I guess you have rules to copy these to files with "usual" names ?

**Comment by fdopen** [comment]
Yes, there is usually a rule to generate a file with a regular suffix (similiar to `*.cppo.ml` files), see e.g:
https://github.com/fdopen/ppx_cstubs/blob/962a2d5e98e0a26b58e80019592d84586bf4ce37/examples/dune-project/src/lib/dune#L12
