### ISSUE TITLE
[BUGLET]  merlin--highlight

### ISSUE THREAD

**Issue by progman1** [ocaml/merlin#1290]
this function has
```
   (if merlin-allow-sit-for
        (unwind-protect (sit-for 60) (delete-overlay overlay)))
      (run-with-idle-timer 0.5 nil
        (lambda () (delete-overlay overlay)))))
```
the indentation and logic indicative of alternate branches but
the parentheses make it a sequence.

**Comment by mattiase** [comment]
Yes, that's a clear bracketing mistake. Fix added to PR#1367.
