### ISSUE TITLE
-cmt-path added to build_path instead

### ISSUE THREAD

**Issue by mroch** [ocaml/merlin#1330]
no idea if this is a real issue or not, but I was reading the code and this looks like a typo:

https://github.com/ocaml/merlin/blob/f3565d0ef89cf8df9bc3f10a15dc12069658f45b/src/kernel/mconfig.ml#L253-L258

it's appending to `build_path` instead of `cmt_path`

**Comment by trefis** [comment]
Indeed, thanks!
