### ISSUE TITLE
Merlin unable to locate operators

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#1332]
Consider:

```
let ( +++ ) x y = x ^ y

let z = "foo" +++ "bar"
```

When one hovers over `+++` in the definition of `z`, merlin correctly returns the type. But it fails to find the definition of `+++`.

**Comment by voodoos** [comment]
I just noticed this issue is from April, maybe it has been fixed since then ?

**Comment by ulugbekna** [comment]
I think it got fixed. I can't reproduce it with ocamllsp either.
