### ISSUE TITLE
MerlinLocate doesn't work in shared directory of virtual machine.

### ISSUE THREAD

**Issue by jiseongg** [ocaml/merlin#1344]
I'm developing OCaml project, which will be deployed in the form of [Vagrant](https://www.vagrantup.com) box with Ubuntu 18.04. Note that this project is the extension of [Facebook Infer](https://github.com/facebook/infer) and codes in attached images are from it. Also I've not yet started to develop, so the reproducing issues are simply done with `tags/v1.1.0` of Infer.

In this setup, the root directory of OCaml projects are in `/vagrant` directory in VM, which is shared with host machine. And here, there is a problem with `MerlinLocate`. It says `Several source files in your path have the same name, ...` but, listed files include exactly same files. Like the attached images below.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/47690444/119450236-92178800-bd6e-11eb-8590-176ebe7e6d3e.png">

However, if I clone the same version of source codes to `~/infer` directory and build it, there is no problem. Attached below is the capture of success of `:MerlinLocate Typ` in `Sil.ml`.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/47690444/119451550-5aa9db00-bd70-11eb-9b57-b9c21ef7e881.png">

Since I'm trying to make this project easily built in VM with development setup via single vagrant command (i.e. `vagrant up`), this problem is crucial. The vagrant's sharing project directory is inevitable.

If one can suggest the starting point to hack merlin, it'll be very helpful.

Environments:
```text
$ opam switch
#  switch                         compiler                       description
→  ocaml-variants.4.11.1+flambda  ocaml-variants.4.11.1+flambda  ocaml-variants.4.11.1+flambda

$ opam --version
2.0.4

$ ocamlmerlin -version
The Merlin toolkit version v4.2-411, for Ocaml 4.11.1

$ ocaml --version
The OCaml toplevel, version 4.11.1
```

**Comment by voodoos** [comment]
Hello @jiseongg, thanks for the report. Non of us is familiar with vagrant.

It is not clear to me what you do inside the VM and what you do outside ?
Are all the tools (opam, dune, merlin) installed and run inside the VM ? And your editor too ?

**Comment by jiseongg** [comment]
Hi @voodoos,

The answers for your question are all "yes". All the tools and editors are ran inside VM.

Outside the VM, there is a root directory of a project, say github repository. And it is supposed to be built and ran inside VM. What Vagrant does is make users to easily configure the VM, with the file named `Vagrantfile`. It's similar to Docker, except that docker runs container whereas vagrant runs VM.

In this VM, the project directory outside the VM can be accessed by mounted directory (`/vagrant` directory inside VM.) And, the issue I found is that, if I navigate OCaml codes that's in `/vagrant` directory inside VM using Merlin, `MerlinLocate` doesn't work properly. It is the first image I attached. It looks that the each file is recognized redundantly, so Merlins is saying `"Several source files..."`

By the way, I agree that there might not be an easy way to reproduce it. And, using both vagrant and ocaml seems to be minor case. I also started using local machine in the project I was developing at the time I wrote the issue.

**Comment by voodoos** [comment]
Ok, thank you for the details, it is indeed a very niche case, but it is still surprising that duplicate paths are printed. Since everything is hapening in the virtual machine, Merlin should not be confused like that.

Could you try running this command from the root of the project inside the machine ?

`ocamlmerlin single dump-configuration -filename infer.ml < src/infer.ml`

**Comment by jiseongg** [comment]
It took a while for me to reproduce this issue, since I had removed the machine. Now I'm ready for the environment to reproduce it.

1. The result of the command suggested.
> `ocamlmerlin single dump-configuration -filename Typ.ml < src/IR/Typ.ml`

```json
{
  "class": "return",
  "value": {
    "ocaml": {
      "include_dirs": [],
      "no_std_include": false,
      "unsafe": false,
      "classic": false,
      "principal": false,
      "real_paths": true,
      "recursive_types": false,
      "strict_sequence": false,
      "applicative_functors": true,
      "unsafe_string": false,
      "nopervasives": false,
      "strict_formats": false,
      "open_modules": [],
      "ppx": [],
      "pp": null,
      "warnings": {
        "actives": [
          1,
          2,
          3,
          5,
          8,
          10,
          11,
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          28,
          31,
          43,
          46,
          47,
          49,
          51,
          52,
          53,
          54,
          55,
          56,
          57,
          58,
          59,
          61,
          62,
          63,
          64,
          65
        ],
        "warn_error": [
          31
        ],
        "alerts": {
          "alerts": [],
          "complement": true
        },
        "alerts_error": {
          "alerts": [],
          "complement": false
        }
      }
    },
    "merlin": {
      "build_path": [],
      "source_path": [],
      "cmi_path": [],
      "cmt_path": [],
      "flags_applied": [],
      "extensions": [],
      "suffixes": [
        {
          "impl": ".ml",
          "intf": ".mli"
        },
        {
          "impl": ".re",
          "intf": ".rei"
        }
      ],
      "stdlib": null,
      "reader": [],
      "protocol": "json",
      "log_file": null,
      "log_sections": [],
      "flags_to_apply": [],
      "failures": [],
      "assoc_suffixes": [
        {
          "extension": ".re",
          "reader": "reason"
        },
        {
          "extension": ".rei",
          "reader": "reason"
        }
      ]
    },
    "query": {
      "filename": "Typ.ml",
      "directory": "/vagrant",
      "printer_width": 0,
      "verbosity": 0
    }
  },
  "notifications": [],
  "timing": {
    "clock": 12,
    "cpu": 5,
    "query": 0,
    "pp": 0,
    "reader": 5,
    "ppx": 0,
    "typer": 0,
    "error": 0
  }
}
```

2. The environment
> What is your host's system ? It might be related to case-sensitivity issues.
- Host: macOS Monterey
- Guest: Ubuntu 18.04.5 LTS


> Since everything is hapening in the virtual machine, Merlin should not be confused like that.

I agree. The only difference between problematic situation and normal situation is whether the project directory is shared with host.  (It is summarized with two images I had attached before.)

**Comment by voodoos** [comment]
Sorry, it was probably:
`ocamlmerlin single dump-configuration -filename src/IR/Typ.ml < src/IR/Typ.ml`

But anyway I would suspect case sensitivity issues. There is a handful of reports from different users on different systems having case sensitivity issues with vagrant's default folder sharing. Such as [this one](https://stackoverflow.com/questions/21562913/virtualbox-vagrant-shared-folder-case-sensitivity-issue-on-os-x-and-linux).

Apparently one option would be to use an `nfs` share with the appropriate plugin.

**Comment by jiseongg** [comment]
Ah, I got it. I thought it was the issue of Merlin before. If it's not, maybe I can try to solve it by investigating Vagrant more. Thank you for your help :)

**Comment by voodoos** [comment]
No problem, I am closing the issue for now, don't hesitate to reopen it if needed.
