### ISSUE TITLE
feature request / question: configuration to force dune protocol

### ISSUE THREAD

**Issue by vsiles** [ocaml/merlin#1346]
Hi !
My understanding of merlin is the following: at each request, it checks whether:
- there is a .merlin file "nearby": if there is dot-merlin-reader is spawn to process it
- there is a dune file: invokes dune to get the relevant info

We support two build methods for our project, one using Buck and one using dune. Because how Buck is currently integrated here, we have a versioned .merlin file in our project, in the toplevel directory. We're using dune (< 2.8) so it will produce .merlin files in the source directory and merlin will pick these up before the .merlin we have versioned, so we can easily use both system (just delete the .merlin files except the top one and you're back using buck. Build with dune and "it works").

Now that dune >= 2.8 no longer produces any .merlin file, we can't easily update to use it _and_ continue having the two build systems handy.

That being said, my idea would be to allow an override mechanism, something like "if a `.merlin.force-dune` file is present, don't look for .merlin file and directly invoke dune".

How crazy does this idea sounds to you ?

**Comment by trefis** [comment]
I don't understand how your proposal helps.
Isn't your issue that merlin will always see the dune files first (even when not building with dune)?

**Comment by trefis** [comment]
My point is: the dune files are there, always. (Right?)
So merlin would try and talk to dune, always. And we're *not* going to disable that behavior.

**Comment by vsiles** [comment]
My understanding is that if there is a .merlin _and_ a dune file, merlin would spawn dot-merlin-reader and use the .merlin file, disregarding the dune file.

Am I getting that wrong ?

**Comment by vsiles** [comment]
Discussed on #irc, it won't solve our issues in this form. I'll be back.
