### ISSUE TITLE
Is this a merlin issue or other?

### ISSUE THREAD

**Issue by learn-man** [ocaml/merlin#1356]
I wrote a simple code, like this:

![](https://i.postimg.cc/RVSd0rkx/2021-06-25-180459-527x248-scrot.png)

But compile it show me this:

![](https://i.postimg.cc/m2mwzX4z/2021-06-25-180515-488x111-scrot.png)

I test the code in the `utop`, is work normal.

And i change a bit of code 

```Ocaml
......
| Sun -> 7;;

.......
```

then compile it file. it's done.

this is my config file:

```Emacs Lisp
;;; package --- Summary
;;; Commentary:
;;; Code:
(autoload 'tuareg-mode "tuareg" "Tuaregmode" t)
(load "tuareg-site-file")
(autoload 'merlin-mode "merlin" "Merlin mode" t)

(add-hook 'tuareg-mode-hook 'merlin-mode t)
(add-hook 'caml-mode-hook 'merlin-mode t)

(add-to-list 'auto-mode-alist '("\\.\\(ml\\|mli\\)\\'" . merlin-mode))
(add-to-list 'auto-mode-alist '("\\.\\(ml\\|mli\\)\\'" . tuareg-mode))

(setq merlin-command 'opam)

(provide 'a-ocaml)
;;; a-ocaml.el ends here
```

following 2 pics show the waring messages:

![](https://i.postimg.cc/6Qz2Y3WM/2021-06-25-184114-434x321-scrot.png)

![](https://i.postimg.cc/6Qz2Y3WM/2021-06-25-184114-434x321-scrot.png)

**Is this a merlin config problem or other problem?**
`Thanks!`

**Comment by trefis** [comment]
This is neither a configuration issues, nor an issue with merlin, but rather a problem with your code.
As you can see your editor (that is: merlin) shows you the same error than the compiler.

I suggest that you go to https://discuss.ocaml.org/ if you want some help with this, or any other problem you might encounter.

Best,

**Comment by learn-man** [comment]
@trefis
Thanks.
