### ISSUE TITLE
Emacs bindings

### ISSUE THREAD

**Issue by Chris00** [ocaml/merlin#1386]
After [discussing](https://github.com/ocaml/tuareg/issues/273) with @monnier, @mattiase, and @erikmd about Tuareg _documentation_ bindings, we would like to expand this discussion with the Merlin developers.

- There is unfortunately no standard Emacs' documentation keybinding but we are thinking to use <kbd>C-c C-d</kbd> (we cannot use [<kbd>C-c C-h</kbd>](https://github.com/ocaml/merlin/issues/860) as <kbd>C-h</kbd> is [reserved](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) for discoverability).  This however conflicts with the key for `m︭erlin-d︭estruct`.  May we suggest that <kbd>C-c M-d</kbd> be used for this (which is even more mnemonic 😀).
- Merlin shadows <kbd>C-c C-r</kbd> (bound in Tuareg and Caml-mode to `...-eval-region`).  What do you think of binding `merlin-error-check` to  <kbd>C-c M-r</kbd>?
- Given that <kbd>M-.</kbd> (resp. <kbd>M-,</kbd>) are standard in Emacs (and already supported by Merlin), one can remove <kbd>C-c C-l</kbd> (resp. <kbd>C-c &</kbd>) — I'm thinking to do the same in Tuareg after making `caml-types-show-ident` available through `xref`.
- How about binding `merlin-occurrences` to [<kbd>M-?</kbd> (through `xref`)](https://www.gnu.org/software/emacs/manual/html_node/emacs/Identifier-Search.html)?
- Contrarily to [what is asserted on the wiki](https://github.com/ocaml/merlin/wiki/emacs-from-scratch), <kbd>C-c t</kbd> is no longer bound to `merlin-type-expr` (a [good thing as it is reserved to the user](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html)).  May we suggest to bind it to <kbd>C-c C-t</kbd> with a prefix?

**Comment by mattiase** [comment]
And as an alternative binding for `merlin-destruct`, `C-c C-e` seems to be free -- E for [Explode](https://en.wikipedia.org/wiki/Exploded-view_drawing)?

**Comment by erikmd** [comment]
> And as an alternative binding for `merlin-destruct`, `C-c C-e` seems to be free -- E for [Explode](https://en.wikipedia.org/wiki/Exploded-view_drawing)?

I don't think so: [it is already bound](https://github.com/ocaml/tuareg/blob/c33222d03f80a60818cfdeb0cbadcba7b35dfec2/tuareg.el#L1499) (and AFAICT, `C-c C-e` is a very useful keybinding in Tuareg :)

**Comment by mattiase** [comment]
My mistake, sorry. I always use `C-M-x` because it's faster to type!

**Comment by Chris00** [comment]
It is also bound to <kbd>C-x C-e</kbd> (which is not harder to type than <kbd>C-c C-e</kbd>, contrarily to <kbd>C-M-x</kbd> for me), so we could free that binding...

**Comment by erikmd** [comment]
Hi @Chris00,

> It is also bound to `C-x C-e` (which is not harder to type than `C-c C-e`, contrarily to `C-M-x` for me), so we could free that binding...

Indeed! so regarding `merlin-destruct`, it might be bound, for example:

* to `C-c M-d`
* or to `C-c C-e`, keeping `C-M-x` and `C-x C-e` as the binding for `tuareg-eval-phrase` (*albeit* it can be noted that `C-x C-e` shadows the global command `eval-last-sexp` which can be handy to evaluate elisp fragments in any mode (including sexp's in OCaml comments for example 😅))
* or maybe to something else (`C-c |` ?)

**Comment by bbatsov** [comment]
I think that `C-c M-d` is a good option for `merlin-destruct` and `C-c C-d` would better for something documentation related. I would not mess with classic keybindings from evaluating stuff.

Btw, I've started playing with OCaml recently and I've noticed that Merlin's mode menu is almost empty:

![image](https://user-images.githubusercontent.com/103882/174740480-f518b3cd-deb7-4517-8343-a0821f458132.png)

This doesn't help with the feature discovery.

**Comment by erikmd** [comment]
@Chris00 to follow-up your first post:

> Merlin shadows <kbd>C-c C-r</kbd> (bound in Tuareg and Caml-mode to ...-eval-region). What do you think of binding merlin-error-check to <kbd>C-c M-r</kbd>?

For <kbd>C-c M-r</kbd>: why not, but that's less convenient to type;

Also I'd like to suggest <kbd>C-c C-v</kbd> because TTBOMK this keybinding is unbound in Tuareg/Merlin, and is already used in the standard Emacs modes for Python (to check the ambient script using linters):

- cf. [python.el](https://github.com/emacs-mirror/emacs/blob/7b30e11b2ac5cd360db7ee8b6aed07bd918b93a2/lisp/progmodes/python.el#L348)
- cf. [elpy.el](https://github.com/jorgenschaefer/elpy/blob/7ff8ffa918411887d165764f7a5a12bc46646e73/elpy.el#L346)

**Comment by erikmd** [comment]
Dear all, I believe the discussion led to good solutions (requiring few unbindings, for the sake of backward-compatibility),
so I'm about to prepare two small PRs (for Tuareg and Merlin) that perform the various keybinding enhancements that were suggested in these two issues:

* https://github.com/ocaml/tuareg/issues/273
* https://github.com/ocaml/merlin/issues/1386

**Comment by erikmd** [comment]
## Here is an (exhaustive) list of the changes that the PRs involve:

### Tuareg changes (issue https://github.com/ocaml/tuareg/issues/273 | PR TODO)

| Old binding (to remove) | Function name | Current binding (already existing or new) | Comment | Author |
|-|-|-|-|-|
| `C-c ?` | `tuareg-interactive-next-error-source` | <code>C-c `</code> (existing) | Emacs expects `?` and `C-h` to be unbound in prefix maps (for [self-documenting purpose](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html), e.g., try `C-x ?`) | Suggested by [@mattiase](https://github.com/ocaml/tuareg/issues/273#issue-986904771) |
| `C-c C-h` | `caml-help` | `C-h .` (new) | same binding as [Eglot](https://joaotavora.github.io/eglot/#index-eglot_002dmode_002dmap) | Suggested by [@catern](https://github.com/ocaml/tuareg/issues/273#issuecomment-1551366982) and [@monnier](https://github.com/ocaml/tuareg/issues/273#issuecomment-1552155113) |

### Merlin changes (issue https://github.com/ocaml/merlin/issues/1386 | PR TODO)

| Old binding (to remove) | Function name | Current binding (already existing or new) | Comment | Author |
|-|-|-|-|-|
| `C-c C-r` | `merlin-error-check` | `C-c C-v` (new) | to avoid shadowing Tuareg's `C-c C-r` = `tuareg-eval-region`, and `C-c C-v` is similar to [python.el](https://github.com/emacs-mirror/emacs/blob/7b30e11b2ac5cd360db7ee8b6aed07bd918b93a2/lisp/progmodes/python.el#L348)'s and [elpy](https://github.com/jorgenschaefer/elpy/blob/7ff8ffa918411887d165764f7a5a12bc46646e73/elpy.el#L346)'s check commands | Suggested by [@Chris00](https://github.com/ocaml/merlin/issues/1386#issue-993828239) and [@erikmd](https://github.com/ocaml/merlin/issues/1386#issuecomment-1701520732) |
| `C-c t` (cf. the [wiki](https://github.com/ocaml/merlin/wiki/emacs-from-scratch#getting-the-types-of-expressions)) | `merlin-type-expr` | `C-u C-c C-t` (new) | the binding was documented but not available actually | Suggested by [@Chris00](https://github.com/ocaml/merlin/issues/1386#issue-993828239) |
| `C-c C-d` | `merlin-destruct` | `C-c M-d` (new) | to be able to use `C-c C-d` for a documentation-related function | Suggested by [@erikmd](https://github.com/ocaml/merlin/issues/1386#issuecomment-917407581) and [@bbatsov](https://github.com/ocaml/merlin/issues/1386#issuecomment-1161359799) |
| `C-c C-d` | `merlin-destruct` | <code>C-c &vert;</code> (new) | to recall the <code>&vert;</code> in pattern matching and provide a simpler keybinding than `C-c M-d` | Suggested by [@erikmd](https://github.com/ocaml/merlin/issues/1386#issuecomment-917407581) |
| N/A (unbound) | `merlin-document` | `C-c C-d` (remap) | sounds better for a documentation-related function | Suggested by [@mattiase](https://github.com/ocaml/tuareg/issues/273#issuecomment-913227000) and [@bbatsov](https://github.com/ocaml/merlin/issues/1386#issuecomment-1161359799)

## Here is a list of possible future changes (more discussion/work is needed):

| Old binding (to remove) | Function name | Current binding (already existing or new) | Comment | Author |
|-|-|-|-|-|
| N/A (unbound) | `merlin-occurrences` | `M-?` (existing) | may need new `xref`-related code | Suggested by [@mattiase](https://github.com/ocaml/tuareg/issues/273#issuecomment-917393431) and [@Chris00](https://github.com/ocaml/tuareg/issues/273#issuecomment-917397639) |
| `C-c C-l` | `caml-types-show-ident` and `merlin-locate` | `M-.` (existing) | may need new `xref`-related code | Suggested by [@Chris00](https://github.com/ocaml/merlin/issues/1386#issue-993828239) |
| `C-c &` | `merlin-pop-stack` | `M-,` (existing) | may need new `xref`-related code | Suggested by [@Chris00](https://github.com/ocaml/merlin/issues/1386#issue-993828239) |
