### ISSUE TITLE
Emacs: highlight matching {begin,struct,sig}…end blocks

### ISSUE THREAD

**Issue by MisterDA** [ocaml/merlin#1387]
Hi!
(I'm afraid this issue is going to sound silly ­— perhaps a not-our-bug)

There's something in my Emacs config that highlights lightly a set of matching parentheses (maybe related to https://www.gnu.org/software/emacs/manual/html_node/emacs/Matching.html). I'm not sure whether Merlin actually does anything to enable that feature on OCaml code, but if it does, could it be possible to also highlight the matching keywords when the emacs cursors hovers `struct … end`, `sig … end`, or `begin … end` blocks?

**Comment by trefis** [comment]
Merlin doesn't do any highlighting, you'll want to have a look at https://github.com/ocaml/tuareg I believe.

**Comment by mattiase** [comment]
Actually Tuareg attempts to do that and it should work for the keyword pairs that you mention. Try enabling `show-paren-mode` if you haven't already, and consider using a newer Tuareg (possibly the development version from Github; it is stable enough for daily use).

**Comment by MisterDA** [comment]
`show-paren-mode` is what I was looking for, thank you very much!
