### ISSUE TITLE
`-alert` not understood by Merlin

### ISSUE THREAD

**Issue by nojb** [ocaml/merlin#1400]
It seems Merlin does not understand the `-alert` flag to the compiler.

![image](https://user-images.githubusercontent.com/113560/140303948-195c610a-5414-4d0c-b2ed-73379a638b63.png)

**Comment by jberdine** [comment]
See also https://github.com/ocaml/merlin/issues/1176

**Comment by nojb** [comment]
I tried a fix in #1401
