### ISSUE TITLE
Destruct on fields

### ISSUE THREAD

**Issue by smimram** [ocaml/merlin#1406]
In the following code
```
type t = A | B

type r = { field : t }

let f x =
  x.field
```
when I use `merlin-destruct` (`C-c C-d`) on `x.field` I get the error message
```
merlin: Destruct not allowed on record_field
```
while I expected something like
```
let f x =
  match x.field with | A -> (??) | B -> (??)
```

However, if I write
```
let f x =
  let y = x.field in
  y
```
and destruct `y` it works and generates
```
let f x =
  let y = x.field in
  match y with | A -> (??) | B -> (??)
```

Since the second case does not look significantly easier than the first one and the first one (matching on a field) is quite common, would it be possible to add support for such situations in merlin? Thanks!

PS: while redacting this report, it occured to me that what merlin is trying to do is in fact to destruct the field itself in some sense. In this case, is there another way to generate pattern matching for `x.field` directly?

**Comment by voodoos** [comment]
This issue was fixed in https://github.com/ocaml/merlin/pull/1375.
It is a part of Merlin's `4.4-41x` releases so it requires at least OCaml 4.11.0.

**Comment by voodoos** [comment]
Please reopen if the issue persists!
