### ISSUE TITLE
[Request] Merlin that tracks ocaml trunk

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml/merlin#1411]
Merlin (and also ocaml-lsp-server that depends on it) are critical to do any sort of practical large scale programming in a typed programming language like OCaml.

I've noticed that only after a compiler is released or when it is shortly due to be released does one get a merlin version for it.

Would it be possible to have a always "upto date" version of merlin that works with the compiler trunk? I can understand that this could be a difficult task because merlin probably needs to deal with a few compiler internals. 

But the surface OCaml language is stable to a large extent so hopefully this is something that is not too impratical?

How do compiler developers deal with this? I'm sure you need things like jump to definition etc. while working on e.g. 4.14. How are you doing that easily? Is it possible to get a minimally working version of merlin for the OCaml trunk yourself?

**Comment by sidkshatriya** [comment]
As you do a lot of tool upgrades when compiler versions change I was wondering if you had any opinions on this @kit-ty-kate

**Comment by trefis** [comment]
The current official answer is https://github.com/ocaml/ocaml/blob/trunk/HACKING.adoc#using-merlin
