### ISSUE TITLE
merlin not working for vim

### ISSUE THREAD

**Issue by logan-lieou** [ocaml/merlin#1422]
When I run `opam user-setup install` after `opam install merlin` it seems to be setting up for emacs but I want to use merlin with vim
![image](https://user-images.githubusercontent.com/20232318/148135260-83ac6948-7810-4dba-ace0-5d0cdfd869c7.png)
I also get a bunch of these warnings not sure if this is useful
![image](https://user-images.githubusercontent.com/20232318/148135349-026b8ac2-6e0b-413a-9a8f-c33e306bc219.png)

When I go into vim it seems merlin completely not working
![image](https://user-images.githubusercontent.com/20232318/148135398-de910366-f8d0-46db-b47e-b54c7f953f84.png)

**Comment by logan-lieou** [comment]
I'm assuming I'm missing something here but I just wanna use vim

**Comment by voodoos** [comment]
Could you check if you have something similar to the following lines in your `.vimrc` file:
```
let g:opamshare = substitute(system('opam var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
syntax on
filetype plugin on
filetype indent on
```

**Comment by voodoos** [comment]
Were you able to solve your issue @logan-lieou ?

**Comment by logan-lieou** [comment]
I decided to switch to emacs :((

**Comment by let-def** [comment]
If you try again to get `vim` to work, please paste the output of `:scriptnames`.

**Comment by voodoos** [comment]
Closing this as it is stale. Don't hesitate to reopen if you have more reproduction  information.
