### ISSUE TITLE
MerlinLocate/MerlinLocateImpl locate the interface of local executable

### ISSUE THREAD

**Issue by copy** [ocaml/merlin#1424]
Consider:

```
% echo 'let _ = Test2.foo' > test.ml
% echo 'let foo = 42' > test2.ml
% echo 'val foo : int' > test2.mli
% echo '(executable (name test))' > dune
```

After building, `MerlinLocateImpl` (and `MerlinLocate` with `let g:merlin_locate_preference = 'ml'`) on `Test2.foo` in test.ml jump to the test2.mli instead of test2.ml as expected.

**Comment by copy** [comment]
Gentle ping. This makes lsp's jump-to-definition somewhat frustrating to use.

**Comment by voodoos** [comment]
A complete rewrite of `locate` will land with OCaml 5.2 and it appears to fix that issue :-)

**Comment by copy** [comment]
Testing again with merlin 5.1-502 and ocaml-lsp-server 1.19.0, it seems that the issue only occurs when building only the executable (e.g. `dune build -w test.exe`).

`dune build -w` or `dune build -w @check` works, so let's close this.

Thanks for the work on locate!
