### ISSUE TITLE
Error installing opam merlin in Mac M1

### ISSUE THREAD

**Issue by mytran2111** [ocaml/merlin#1429]
Hi, I have this error while trying to install merlin using opam install merlin command. My current switch is ocaml-system.4.12.0  

```
#=== ERROR while compiling cppo.1.6.8 =========================================#
# context     2.1.2 | macos/x86_64 | ocaml-system.4.12.0 | https://opam.ocaml.org#1e60c1ea
# path        ~/.opam/4.12.0/.opam-switch/build/cppo.1.6.8
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p cppo -j 7
# exit-code   1
# env-file    ~/.opam/log/cppo-3194-db780e.env
# output-file ~/.opam/log/cppo-3194-db780e.out
### output ###
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:40:2: error: invalid instruction mnemonic 'adrp'
# [...]
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:41:10: error: brackets expression not supported on this target
#  ldr x1, [x1, _camlCppo_version__1@GOTPAGEOFF]
#          ^
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:42:10: error: brackets expression not supported on this target
#  str x1, [x0, #0]
#          ^
# /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s:43:11: error: unknown token in expression
#  movz x0, #1, lsl #0
#           ^
# File "src/cppo_version.ml", line 1:
# Error: Assembler error, input left in file /var/folders/q0/qb537jy92q10k3q7x7wzxv900000gn/T/buildbd9f86.dune/camlasmda5b05.s

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
┌─ The following actions failed
│ λ build cppo        1.6.8
│ λ build csexp       1.5.1
│ λ build easy-format 1.3.2
│ λ build result      1.5
└─ 
╶─ No changes have been performed
```

_Originally posted by @mytran2111 in https://github.com/ocaml/merlin/issues/1231#issuecomment-1011285311_

**Comment by voodoos** [comment]
You should use backticks ``` to prevent copy pasted code to be formatted by the markdown parser of Github. (I edited your post.)
Also there is no need for multiple copies of the issue, you can simply reference issues by their number (#1231) if you think they are linked, and in this case they aren't since the message is completely different.

Also, the error happened "while compiling `cppo.1.6.8` so this is does not appear to be Merlin related, you should report to [@ocaml-community/cppo](https://github.com/ocaml-community/cppo/issues).

**Comment by voodoos** [comment]
Also it looks like it is linked to that issue: https://github.com/ocaml/ocaml/issues/10374

**Comment by voodoos** [comment]
And if you installed opam via homebrew there seems to be a solution in this issue: https://github.com/ocaml/opam/issues/4798

If it doesn't solve your specific problem you can probably reboot that conversation or open a new Issue on [opam's issue tracker](https://github.com/ocaml/opam/issues).
