### ISSUE TITLE
MerlinDestruct on custom datatype

### ISSUE THREAD

**Issue by wzprichardwzp** [ocaml/merlin#1435]
Is there a way to set it, so when the data is destructed, the branches will be formatted to not all be on the same line?

match foo with
| A -> _ 
| B -> _
| C -> _

instead of 
`match foo with | A -> _ | B -> _ | C -> _`

**Comment by voodoos** [comment]
There is no setting to control that behaviour. Running a code formatter that supports typed holes like `ocamlformat` right after destruct should work.
