### ISSUE TITLE
Release tags confuse Melpa, cause Nix breakage

### ISSUE THREAD

**Issue by sheijk** [ocaml/merlin#1442]
Currently the version scheme for releases adds -412/-413 postfixes. Those cause Melpa to misparse versions as 4.4.-4.412/413 and broke Nix usage of merlin and some related plugins.

There are two bug reports for this already, [for Nix](https://github.com/nix-community/emacs-overlay/issues/178) which has a work-around and [for Melpa](https://github.com/melpa/melpa/issues/7946). This is mostly to bring attention to these issues - it's not clear who needs to fix them, possibly all sides.

**Comment by voodoos** [comment]
Thank for letting us know. I guess we could use a different scheme such as `v414.0`, `v414.1`, `v500.0` etc. 
It is probably easier to machine-parse but it makes it less clear that it is the same Merlin but for different OCaml versions. However we probably already diverged a bit between our backports so there are probably not exactly the "same" Merlins anyway.

I don't have a strong opinion on this. @let-def, @trefis, do you have one ?

**Comment by sheijk** [comment]
Melpa uses version-to-list ([see here](https://github.com/melpa/melpa/issues/7946)) to parse the number. According to it's documentation only numbers separated by dots and some special cases like alpha/beta etc. are allowed (see version-regexp-alist)

**Comment by trefis** [comment]
> It is probably easier to machine-parse but it makes it less clear that it is the same Merlin but for different OCaml versions. However we probably already diverged a bit between our backports so there are probably not exactly the "same" Merlins anyway.

We might have diverged a bit but not that much.
I like the fact that the versioning scheme we have indicates what features people can expect.

We can of course try and find another one that satisfies all the package managers out there. But I'd want to have @kit-ty-kate (or another opam expert)'s opinion before we change anything.

**Comment by kit-ty-kate** [comment]
opam is not affected by the tag name, what would the real version number be?

**Comment by voodoos** [comment]
Usually the "real" version number is the same as the tag name without the "v".

**Comment by kit-ty-kate** [comment]
> So 4.5-414 or 414.4.5 or 4.5.414

`414.4.5` looks quite weird and is annoying if it is to be changed again in the future (see janestreet version scheme) but other than this one the other two are totally fine by me

**Comment by voodoos** [comment]
Looking at the `version-to-list` spec it seems that negative numbers are to be expected end encode keywords like "pre", "beta", alpha". So even if that interpretation of Merlin's tag is wrong, it feels like Nix should handle this kind of negative version that can appear in correctly tagged Melpa packages, isn't it ?

```
Examples of version conversion:

   Version String    Version as a List of Integers
   \"1.0.7.5\"         (1  0  7 5)
   \"1.0pre2\"         (1  0 -1 2)
   \"1.0PRE2\"         (1  0 -1 2)
   \"22.8beta3\"       (22 8 -2 3)
   \"22.8Beta3\"       (22 8 -2 3)
   \"0.9alpha1\"       (0  9 -3 1)
   \"0.9AlphA1\"       (0  9 -3 1)
   \"0.9alpha\"        (0  9 -3)
```

**Comment by voodoos** [comment]
Oh I see that there is already a mitigation merged on Nix's side: https://github.com/NixOS/nixpkgs/pull/154066

@sheijk can you confirm that this means users of Nix don't need a manual workaround ? In that case we will probably keep the current scheme for clarity.

**Comment by sheijk** [comment]
I think this is what @adisbladis called "tapered over" so I understand it's meant to be temporary. But maybe it should just be declared to be intended if negative numbers are allowed there.

**Comment by voodoos** [comment]
I don't understand it as temporary, more like "the minimal fix for that issue, but not a completely satisfying one yet"...
But in any case it should not be removed since Melpa does use negative numbers as markers of versions that ends with some keywords. (Which is morally the case for our version numbers, even if it is not a standard one.)

Now that the fix is merged on Nix, the only incentive for us to change our current versioning would be to have a more meaningful melpa parse result.

**Comment by voodoos** [comment]
We decided to keep the current numbering for now.
Please don't hesitate to reopen that issue if it continues to cause breakage.
