### ISSUE TITLE
type-enclosing sometimes repeats initial type result when index is incremented

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#1477]
Consider the following:

```
let f x = x
let g (x : int) = x
let a = f 1
let b = g 1
```

If you place the cursor on the `f` in the third line and get the type, you get `'a -> 'a`. Expand that and you get `int -> int` (the text selection does not expand). Expand again to get `int` when the selection expands to `f 1`.

However, if you place the cursor on `g` in the fourth line and do the same, you get `int -> int` twice before the selection expands to `g 1` and you get `int`. This may lead people to assume that the expand selection feature does not work properly if when they try it for the first time it seems to no-op.

**Comment by voodoos** [comment]
I see, we could probably filter out one of the two first results if they are indeed the same.
