### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by bbatsov** [ocaml/merlin#1504]
I think it's never a bad idea to enable GitHub discussions for bigger projects like Merlin, as this way it's easy to separate discussions (e.g. brainstorming on ideas, process, etc) from actual issues/tickets.

**Comment by voodoos** [comment]
Thanks for the suggestion! Personally I do not feel that there is enough activity in the issue tracker for the split to be worth-it right now. We could definitely improve the tagging of issues however. But we will keep that in mind! 

(also looking at the Dune project that activated the feature a while ago, it doesn't look like people use it)

**Comment by bbatsov** [comment]
That's also a matter of teaching people about the discussions by actively converting issues to discussions. 😉 I think there's a super strong inertia with issues and everyone uses them by default for everything, so efforts are required to teach people about any different workflow. 

That being said - tagging issues as "Question/Discussion" can get one relatively far as well.

**Comment by voodoos** [comment]
Let's go with labels for now :-)
