### ISSUE TITLE
Opam vim configurations slow down Vim 9 on MacOS

### ISSUE THREAD

**Issue by foolishhugo** [ocaml/merlin#1510]
Starting at some point this year, I noticed that my MacOS vim slowed down a lot. It went from a second or two to having to run for 10 to 12 seconds. 

I don't know if this is connected with with a MacOS update, which we have had a few this year. Or with my upgrading to vim 9. 

I troubleshooted this today, suspecting Ale being what slowed start up, but then it got fast again when I commented out the OPAM vim configuration. So something there was slowing it down. I wrapped the configuration in a function, so I can run it when I want to use OCaml.

This is not really asking to solve this issue. I am writing this more as documentation. I may troubleshoot at some point in the future.

Everything except for the function start and end was the configuration.

```
" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
function OpamOn()
  let s:opam_share_dir = system("opam config var share")
  let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

  let s:opam_configuration = {}

  function! OpamConfOcpIndent()
    execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
  endfunction
  let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

  function! OpamConfOcpIndex()
    execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
  endfunction

  let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

  function! OpamConfMerlin()
    let l:dir = s:opam_share_dir . "/merlin/vim"
    execute "set rtp+=" . l:dir
  endfunction

  let s:opam_configuration['merlin'] = function('OpamConfMerlin')

  let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
  let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
  let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))

  for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
    if count(s:opam_available_tools, tool) > 0
     call s:opam_configuration[tool]()
    endif
  endfor
endfunction
" ## end of OPAM user-setup addition for vim / base ## keep this line


```

**Comment by raphael-proust** [comment]
I've had a similar issue on some different OS. IIRC, the culprit on my system was `opam list` which took much too long to be used in this context.

I was also lazy and I ended up replacing some of the dynamic opam configuration discovery functions with some static values which work on my system. My configuration is now:

```
let s:opam_share_dir = system("opam var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')
execute "set rtp+=" . s:opam_share_dir . "/merlin/vim"
```

(I don't use the other tools.)

**Comment by foolishhugo** [comment]
> I've had a similar issue on some different OS. IIRC, the culprit on my system was `opam list` which took much too long to be used in this context.
> 
> I was also lazy and I ended up replacing some of the dynamic opam configuration discovery functions with some static values which work on my system. My configuration is now:
> 
> ```
> let s:opam_share_dir = system("opam var share")
> let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')
> execute "set rtp+=" . s:opam_share_dir . "/merlin/vim"
> ```
> 
> (I don't use the other tools.)

Let me  test `opam list` and try out  your solution at some point today. Thanks!

**Comment by voodoos** [comment]
Thanks for the hint @raphael-proust.
Looking at the `opam-user-setup` repository the issue has apparently already been solved: https://github.com/ocaml-opam/opam-user-setup/issues/53

However it seems that it was not released yet...

**Comment by voodoos** [comment]
I'm closing this since it is not a Merlin issue per-see.
