### ISSUE TITLE
Doc comments are associated with the wrong constructors

### ISSUE THREAD

**Issue by mheiber** [ocaml/merlin#1513]
**Steps to rero**

Create foo.ml, with these contents:

```ocaml
type t =
    | A
    (**A Comment *)
    | B
    (**B Comment *)
    | C
```

Then open the file in VSCode, using the Ocaml Platform extension (tested with v1.10.7), which I think uses Merlin v4.6-413 via ocaml-lsp-server.

Hover over each constructor

**Actual behavior**

Here are the hovers ocaml-lsp-server provides for each constructor, respectively:
- A: "A comment"
- B: "A comment B comment"
- C: "B comment"

**Expected behavior**

Here are the hovers I'd expect ocaml-lsp-server to provide for each constructor, respectively:
- A: "A comment"
- B: "B comment"
- C: "C comment"

This expectation is based on the OCaml manual https://v2.ocaml.org/manual/doccomments.html#ss:label-comments:

> Comments which appear immediately after a labelled argument, record field, variant constructor, object method or polymorphic variant constructor are are converted into [attribute](https://v2.ocaml.org/manual/attributes.html#attribute)s.

**version**

I used `ocaml-lsp-server.1.13.2~5.0preview` which I think uses **Merlin v4.6-413**

**Comment by voodoos** [comment]
Thanks for your report ! I am able to reproduce your "actual behaviour".
However I don't see the difference between your actual and expected behaviours. Did you made a typo ?

I guess the expected behaviour should be:
- A: "A comment"
- B: "B comment"
- C: ""

**Comment by mheiber** [comment]
@voodoos thanks, I've fixed the typo:

```
Here are the hovers I'd expect ocaml-lsp-server to provide for each constructor, respectively:
- A: "A comment"
- B: "B comment"
- C: "C comment"
```

**Comment by mheiber** [comment]
Thanks for the pointers, I found a fix that makes the new test pass:

https://github.com/voodoos/merlin/compare/test/issue1513-doc...mheiber:merlin:fix/issue1513-doc?expand=1

Before opening a PR, I'll wait for #1513 and handle other cases where `after_only` should be false (labelled parameters, record fields, etc.) as well

**Comment by mheiber** [comment]
Thanks for the pointers, I think I found a fix:

https://github.com/voodoos/merlin/compare/test/issue1513-doc...mheiber:merlin:fix/issue1513-doc?expand=1

 I plan to handle other cases where comments should appear `only_after` (methods, labelled params, etc.) before opening a PR.
