### ISSUE TITLE
locate fails with "didn't manage to find <Module>" but Module.<tab> list all the values inside the module correctly

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/merlin#1519]
I've been in this case so many times in my projects and I'm not too sure how to reproduce it. Any ideas?
I use the locate feature quite frequently but it's very finicky to get it working half the time.

**Comment by voodoos** [comment]
Thanks @kit-ty-kate ! We will need more information to diagnose the issue:

- what versions of ocaml/merlin are you using and with which editor ?
- do you have a specific project were it happens a lot, or better, a precise location in a project were `locate` reliably fails so we can try to reproduce ?

**Comment by kit-ty-kate** [comment]
I managed to reproduce!

OCaml version: 4.14.0
Merlin version: 4.6-414
Editor: Emacs
Project: opam (commit https://github.com/ocaml/opam/commit/edea329d10fcf2dce9d99500240cbbee32b740e6)

Steps to reproduce:
1) `opam install --deps .` (optional if you already have them)
2) `./configure && make`
3) Open `src/client/opamListCommand.ml` in Emacs
4) `C-c C-r` (reload) to double check that Merlin does not detect any error (should show "No errors" at the bottom)
5) `C-c C-l` (locate) on `OpamTypes` on line 13 (this should show "didn't manage to find OpamTypes")
6) However `C-c C-t` or adding a `.` at the end of that line then hitting `M-<tab>` work fine and display all the available types from this module

Observation: This seems to happen for all the modules that are in `(modules_without_implementation ...)` as it also happens for `OpamStateTypes` at the line after but not for the other open modules in the same block of code.

**Comment by kit-ty-kate** [comment]
The same thing happens with @dbuenzli's libraries (such as `fpath`) on an empty project as they do not install a .ml file

**Comment by dbuenzli** [comment]
Are we supposed to install `.ml` files nowadays ?

**Comment by kit-ty-kate** [comment]
no no, this is only the behaviour of dune.

(sorry i didn't mean to tag you)

**Comment by voodoos** [comment]
I was able to write a minimal test reproducing the issue.
Surprisingly jumping to a type inside the module without implementation works, but jumping to the module itself doesn't.
