### ISSUE TITLE
Memory leak on completion

### ISSUE THREAD

**Issue by art-w** [ocaml/merlin#1529]
With OCaml 4.14 and the latest merlin (`4.6-414` and git master (*)), when editing a file in the Irmin repository and querying for completion, the `ocamlermlin-server` quickly reaches >5go of memory usage in just a few seconds.

To reproduce, it's enough to edit [this test file from the Irmin repository](https://github.com/mirage/irmin/blob/main/test/irmin-pack/test_tree.ml) and insert a line anywhere, even at the very top:

```ocaml
let _ = Irmin_pack_unix. (* repeatedly ask for completion *)
```

From a quick look with @voodoos, it's not super clear if the typechecker is responsible for holding onto memory for too long, but it contributes to the size of the leak. For example in the test file, removing the functor instantiations in `module Store = ...` lowers how fast merlin is leaking by a lot. I'm guessing other projects are affected, but that the increasing memory consumption isn't noticeable if one doesn't abuse functors (?)

(*) I believe that @voodoos reproduced the issue on an older version of ocaml/merlin that predates the module shapes

**Comment by voodoos** [comment]
I think I found the culprit !

There is a memoization mechanism for functors:
```
and functor_components = {
  fcomp_arg: functor_parameter;
  (* Formal parameter and argument signature *)
  fcomp_res: module_type;               (* Result signature *)
  fcomp_shape: Shape.t;
  fcomp_cache: (Path.t, module_components) Hashtbl.t;  (* For memoization *)
  fcomp_subst_cache: (Path.t, module_type) Hashtbl.t
}
```

Deactivating that memoization makes the typing very slow on Irmin but stabilize memory consumption.
