### ISSUE TITLE
merlin-construct should shorten module paths

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#1552]
If I run `merlin-construct` on the hole in this example:
```
module M = struct
  module N = struct
    type t = T
  end
end

let f M.N.T = ()
let z = f _
```
it fills in `M.N.T` even though `T` would be sufficient. This means that as `merlin-construct` becomes more widely used during development, unnecessary module paths will proliferate in a codebase.

**Comment by bcc32** [comment]
My guess would be that, in the cases where `merlin-construct` inserts any identifiers, module prefixes are definitely unnecessary, given that the compiler could infer the type and use type-directed disambiguation.
