### ISSUE TITLE
feature request: find occurrences

### ISSUE THREAD

**Issue by nbros** [ocaml/merlin#156]
It would be great if merlin could search for an identifier and return a list of locations for all occurrences of this identifier either in the current buffer or the whole project (depending on an option).

This would allow implementing editor services such as **mark occurrences** (example for Java in this screenshot):
![mark occurrences](http://help.eclipse.org/indigo/topic/org.eclipse.jdt.doc.user/tips/images/mark-occurrences.png)

and **search**:
![search](http://help.eclipse.org/indigo/topic/org.eclipse.jdt.doc.user/tips/images/link-with-editor-in-occs.png)

**Comment by nilsbecker** [comment]
the `:MerlinRename` functionality is great but does not yet seem to work for module aliases. that would be a nice addition. e.g.

   module A = Array

and then call `MerlinRename` on `A` to change it globally to `Arr` or whatever.
