### ISSUE TITLE
Completion for object methods

### ISSUE THREAD

**Issue by sidkshatriya** [ocaml/merlin#1575]
This feels like a notable omission, or perhaps I'm missing something:

Let us say the OCaml class of an object is known e.g. `abc : <some_class; ...>`. 

When I type `abc#` in the editor (with merlin or ocaml-lsp-server enabled) ,  I should be able to get an autocomplete on all the methods in `some_class` but I don't.

But it gets worse, supposing I have `foo: < bar: int -> int; baz: int -> string >` where the methods are explictly listed, even here when I do `foo#` I should be given an autocomplete which allows me to choose between `bar` and `baz` methods, but I dont...

I am using merlin 4.8-500. I've tried with ocaml-lsp-server and am aware that it uses merlin in the backend.

How can merlin help me select methods on an object?

**Comment by sidkshatriya** [comment]
I added a PR for the test. 

Interestingly this issue seems to be a regression. See #598 which was fixed (and was also a regression).

**Comment by sidkshatriya** [comment]
@voodoos Would greatly appreciate if you could have a look at this bug. It seems like a pretty big deal that autocomplete on object method names is broken. It seems like it used to work before. I tried to explore this issue in code but didn't make much progress.

**Comment by voodoos** [comment]
Yes, it looks like this issue is a bit subtle to fix because we cannot easily fold on methods available in the environment.
I will think about it.

**Comment by sidkshatriya** [comment]
If it is any help, even recent versionf of `utop` are able to autocomplete on object methods successfully. Check  https://github.com/ocaml-community/utop/blob/master/src/lib/uTop_complete.ml -- hopefully it might be useful?
