### ISSUE TITLE
`make build` overwrites preprocess files

### ISSUE THREAD

**Issue by 3Rafal** [ocaml/merlin#1604]
Each time I run `make build` command on a clean branch I get following files to be overwritten:
```
src/ocaml/preprocess/menhirLib.ml
src/ocaml/preprocess/menhirLib.mli
src/ocaml/preprocess/parser_raw.ml
```

Diff: 
[my_diff.txt](https://github.com/ocaml/merlin/files/11476374/my_diff.txt)

This is a bit confusing and painful... 
I've found a workaround, which is to run `dune build -p merlin` which was suggested in a related issue: #1479 
I wonder if there is a way to fix it? Or maybe we should just edit a Makefile or/and add a note in readme?

**Comment by voodoos** [comment]
My "workaround" is to pin the correct version of Menhir: `opam pin menhir 20201216`
