### ISSUE TITLE
Allow jump to an enclosing module type

### ISSUE THREAD

**Issue by goldfirere** [ocaml/merlin#1656]
The current `jump` command allows jumps to an enclosing `fun`, `let`, `module`, or `match`. It would be great to also add support for module types, perhaps by adding the `sig` target.

**Comment by voodoos** [comment]
Do you mean jumping to the enclosing `sig ...` from inside the signature ?

**Comment by goldfirere** [comment]
Yes, exactly. How is jumping to a module binding the same?

**Comment by voodoos** [comment]
There are definitely some cases that could be added to the `jump` command like `sig` and `struct`. It also lacks the module type binding case.

**Comment by xvw** [comment]
Hi @goldfirere!
PR #1728 implements the behaviour proposed by @voodoos [here](https://github.com/ocaml/merlin/issues/1656#issuecomment-1650001766), is the fix enough or do you really want to jump to `sig` enclosing specifically?

**Comment by goldfirere** [comment]
Hello @xvw! Welcome! Yes, that looks like the fix. Thanks.
