### ISSUE TITLE
ppx deriving on a type adversely affects merlin location

### ISSUE THREAD

**Issue by ddickstein** [ocaml/merlin#1660]
Given:
```
open Core
module M = struct
  type t =
    | Foo
    | Bar
end
```
Getting the type of `t` highlights just the type definition and gives `type t = Foo | Bar` as expected. However, given:
```
open Core
module M = struct
  type t =
    | Foo
    | Bar
  [@@deriving compare]
end
```
Getting the type of `t` selects the entire module and returns it as `sig type t = Foo | Bar val compare : t -> t -> int end`.

**Comment by voodoos** [comment]
Retrospectively, I discovered the `merlin.hide` and `merlin.focus` attributes which are specifically designed for ppxes. The better fix would be for `ppx_compare` to make use of `merlin.focus` to guide Merlin in the correct branch.

Doc: https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md#locations-in-ppx-rewriters
