### ISSUE TITLE
Unclean sources

### ISSUE THREAD

**Issue by SnarkBoojum** [ocaml/merlin#1681]
"dune clean" doesn't remove src/ocaml/preprocess/parser_raw.cmly -- I had to add a line to the Debian packaging to get rid of it. Perhaps something needs to be done for proper cleaning? [Notice: it might be a dune issue.]

And additionally, the files src/ocaml/preprocess/menhirLib.ml,  src/ocaml/preprocess/menhirLib.mli and src/ocaml/preprocess/parser_raw.ml are generated files so they could be dropped from the source tree.

**Comment by voodoos** [comment]
I will have a look at the `cmly` but it does look like a menhir generated file that Dune should clean as part of the menhir rules.

The `MenhirLib` and `Parser_raw` modules are in the source tree to remove Merlin dependency to Menhir (Menhir is a `dev` dependency and not necessary to build and install merlin in release mode), they are here on purpose.

**Comment by voodoos** [comment]
It might be related to https://github.com/ocaml/dune/issues/7454 (bad interaction between menhir and promotion)
