### ISSUE TITLE
merlin.hide can hide type-signatures inside modules?

### ISSUE THREAD

**Issue by davesnx** [ocaml/merlin#1695]
Given this struct

```
module Component = {
  let make = () => 12;
  let make = () => make();
}
```

```
module Component = { ... }
________^
```

Once the editor hover on `Component` it returns (tested with `ocamlmerlin single type-enclosing -position 1:9`)

```
let make: unit => int
```

```
module Component = { ... }
___________________^
```

while It hovers on `{` it returns (tested with `ocamlmerlin single type-enclosing -position 
 1:20`)

```
let make: unit => int
let make: unit => int
```

---

I'm developing a ppx that wants to hide the first `make`. I tried to add `[@melin.hide]` and `[@melin.focus]` respectively and I have a few doubts:

- Does merlin.hide/focus work outside of ppx? 
- It's required to have a ghost location? or another AST with the same location?

I read https://github.com/ocaml/merlin/blob/master/doc/dev/PROTOCOL.md#merlinhide-and-merlinfocus and https://github.com/ocaml-ppx/ppxlib/blob/main/src/merlin_helpers.mli which gave me those doubts.

What I'm trying to do is actually possible?

**Comment by voodoos** [comment]
Hide / focus annotations are not interacting with the typing of the file. They are used by the Merlin's heuristic that tries to find the most appropriate node "under the cursor".

However the behavior shown when hovering over the struct keyword is a bit surprising and can probably be improved.

**Comment by davesnx** [comment]
That makes total sense, sorry for the confusion.
