### ISSUE TITLE
`501-preview` doesn't interpret the `-cmi-file` flag on the command line.

### ISSUE THREAD

**Issue by ncik-roberts** [ocaml/merlin#1703]
`-cmi-file` was added as a flag upstream for type-checking a file against a specified interface.

This was merged into merlin's `501` and `501-preview` branches, but seemingly only halfway. The `Clflags.cmi_file` ref was merged, and is referenced in `src/ocaml/typing/typemod.ml`, without the corresponding argument-parsing code in `src/kernel/mconfig.ml`.

I'm not sure if this was intentional or not, so I thought I'd open an issue.

**Comment by voodoos** [comment]
Thanks for the report Nick, that indeed sounds like an oversight, I will have a look.
