### ISSUE TITLE
FLG -pp ppx.exe -as-pp does not work on Windows

### ISSUE THREAD

**Issue by jonahbeckford** [ocaml/merlin#1722]
### Problem

A `dune` stanza:

```scheme
(executable
 (name something)
 (modules something)
 (modes byte)
 (libraries DkSDKCoder_Std csexp)
 (preprocess
  (action
   (run %{lib:DkSDKCoder_PPX:ppx.exe} --as-pp %{input-file}))))
```

The merlin config from `dune ocaml merlin dump-config .`:

```scheme
 (FLG (-open Dune__exe))
 (FLG
  (-pp
   "C:\Users\beckf\AppData\Local\Programs\DkSDK\coder\h\main\lib\DkSDKCoder_PPX\ppx.exe
   --as-pp"))
 (FLG
  (-w
   @1..3@5..28@30..39@43@46..47@49..57@61..62@67@69-40
   -strict-sequence
   -strict-formats
   -short-paths
   -keep-locs
   -g))
```

During LSP session in vscode, I was getting `Uninterpreted extension` errors attached to PPX macros like `[%proc ...]`.

### Root Cause

By adding some custom logging into `ppxlib` I could see the following failures from `ppx.exe`:

```powershell
C:\Users\beckf\AppData\Local\Programs\DkSDK\coder\h\main\lib\DkSDKCoder_PPX\ppx.exe: too many input files. 
    First argument was
       C:\Users\beckf\AppData\Local\Temp\merlinppcc6fceQuickstart.ml.
    Next argument was
       1>C:\Users\beckf\AppData\Local\Temp\merlinppcc6fceQuickstart.ml.out.
    
    All arguments:
       C:\Users\beckf\AppData\Local\Programs\DkSDK\coder\h\main\lib\DkSDKCoder_PPX\ppx.exe --as-pp C:\Users\beckf\AppData\Local\Temp\merlinppcc6fceQuickstart.ml 1>C:\Users\beckf\AppData\Local\Temp\merlinppcc6fceQuickstart.ml.out.
```

Notice the `merlinpp` temporary file. The call flow is:

1. `Pparse.apply_pp` calls `System.run_in_directory` on line 162: https://github.com/ocaml/merlin/blob/857f17a6fdf997ce04227b4c28b88a2edb573782/src/ocaml/driver/pparse.ml#L150-L168
2. `System.run_in_directory` **incorrectly** asks for Command Prompt to redirect stdout with `1>` on line 777:
https://github.com/ocaml/merlin/blob/857f17a6fdf997ce04227b4c28b88a2edb573782/src/utils/std.ml#L761-L781

There are a couple problems:

1. In Command Prompt you can't do `1>` (although weirdly can do `2>`). In fact, I don't think `1>` is necessary in any shell.
2. None of that shell redirection would work anyways because `windows_merlin_system_command` is used.

_I'm testing out a hack but there is probably a better way ..._

**Comment by jonahbeckford** [comment]
### Internal Reproduction Steps

(This is for myself)

In `scout-coordinator`:

```json
    "ocaml.sandbox": {
        "kind": "custom",
        "template": "${firstWorkspaceFolder}/dk user.dksdk0.coder.cmdexec VERSION main QUIET CMD $prog $args"
    }
```

and patch `ppxlib`:

```diff
diff --git a/src/driver.ml b/src/driver.ml
index 3caaed2c..5528c539 100644
--- a/src/driver.ml
+++ b/src/driver.ml
@@ -1184,7 +1184,7 @@ let embed_errors = ref false
 let set_input fn =
   match !input with
   | None -> input := Some fn
-  | Some _ -> raise (Arg.Bad "too many input files")
+  | Some a1 -> raise (Arg.Bad (Printf.sprintf "too many input files. First was %s. Then came %s. Args: %s" a1 fn (Array.to_list Sys.argv |> String.concat ~sep:" ")))

 let set_kind k =
   match !kind with
```

Then:

1. `./dk user.dksdk.coder.compile VERSION main EXPRESSION Y:\source\scout-coordinator\cde\Quickstart.ml POLL 0.5 OUTPUT Y:\test.cdi PROJECT_DIR Y:\source\scout-coordinator DUMP_MERLIN` which will create a valid `_build\default\.merlin-conf\exe-QuickstartMain` for LSP/Merlin and dump the `FLG` command.
2. `opam install --switch OPAMPREFIX ./merlin-lib.opam` in patched merlin project
3. `opam install --switch OPAMPREFIX ./ppxlib.opam` in patched ppxlib project
4. `opam install --switch OPAMPREFIX ocaml-lsp-server`
5. `copy -force OPAMPREFIX\_opam\bin\ocamllsp.exe $env:LOCALAPPDATA\Programs\DkSDK\coder\h\main\bin\ocamllsp.exe`
6. `Developer: Reload Window` action in VS Code and look in the `OCaml Language Server` output.

**Comment by nojb** [comment]
I think the clean fix is to extend `ml_merlin_system_command` with an optional argument that allows redirecting stdout to a file (it is currently always redirected to `stderr`). Then in `run_in_directory` we would pass this extra argument when the `stdout` argument is not `None` under Windows (instead of appending `1> ...` to the command-line which doesn't make sense).

**Comment by jonahbeckford** [comment]
That seems straightforward. I'll try that out.
