### ISSUE TITLE
unknown flag `-unboxed-types`

### ISSUE THREAD

**Issue by Maelan** [ocaml/merlin#1794]
Merlin annoyingly reports this flag as an error, although it is a perfectly legal compiler flag (and induces no change in OCaml syntax).

As soon as the `dune` file contains `-unboxed-types` (or its negation, `-no-unboxed-types`), I get spammed with this on every OCaml file I open (in my case, in Vim, with Merlin errors reported via the Syntastic plugin, which opens a disruptive error window whenever there is an error.)

**Comment by voodoos** [comment]
Thanks for the report @Maelan. It's very surprising that a flag so old (sicne 4.04) is missing from our [ignored_flags list](https://github.com/ocaml/merlin/blob/v5.1-502/src/kernel/mconfig.ml#L440-L458) and no one complained.

@xvw are you interested in doing the fix ? It should be quite straightforward: add a test that calls the `errors` command via merlin cli with these flags. It should show the error. Then add the flags to the `ocaml_ignored_flags` list to fix it.
