### ISSUE TITLE
bwrap: loopback: Failed RTM_NEWADDR: Operation not permitted on Ubuntu

### ISSUE THREAD

**Issue by oceanfish88** [ocaml/merlin#1849]
Hi there.

I was watching[ this](https://www.youtube.com/watch?v=i4ZQ2EGI8sY) and tried to check out Merlin.

I was trying to install it, but got the following errors:

$ opam install merlin
opam user-setup install
[ERROR] Sorry, resolution of the request timed out.
        Try to specify a more precise request, use a different solver, or increase the allowed time by setting OPAMSOLVERTIMEOUT to a bigger value (currently, it is set to 60.0
        seconds).
Opam plugin "user-setup" is not installed. Install it on the current switch? [y/n] y

The following actions will be performed:
=== install 1 package
  ∗ user-setup 0.8

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved user-setup.0.8  (https://opam.ocaml.org/cache)
[ERROR] The compilation of user-setup.0.8 failed at "make".

#=== ERROR while compiling user-setup.0.8 =====================================#
# context     2.2.1 | linux/x86_64 | ocaml.5.2.0 | https://opam.ocaml.org#ed95ebf3e30096ed7dbaa2c9ad0c6c5e98000155
# path        ~/.opam/default/.opam-switch/build/user-setup.0.8
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   1
# env-file    /tmp/opam-yantitarenko5-6526/user-setup-6526-1bfd17.env
# output-file /tmp/opam-yantitarenko5-6526/user-setup-6526-1bfd17.out
### output ###
# bwrap: loopback: Failed RTM_NEWADDR: Operation not permitted

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build user-setup 0.8
└─ 
╶─ No changes have been performed

Here is some system information:

$ lsb_release -a

> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 24.04.1 LTS
> Release:	24.04
> Codename:	noble

$ uname -a

> Linux yangelia 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by voodoos** [comment]
That doesn't look like a Merlin related issue. Are you by any change trying that in an unpriviledged docker container ? If so there are some options here: https://github.com/ocaml/opam/issues/4327

**Comment by voodoos** [comment]
Did you solve your problem ? I am going to close this issue since it is not related to Merlin. Feel free to continue asking questions if you are still blocked.
