### ISSUE TITLE
Installation didn't work (vim)

### ISSUE THREAD

**Issue by mihaidusmanu** [ocaml/merlin#233]
I've been trying to install merlin using opam but every time I run into the same error:

"test.ml" [New File]
Error detected while processing function merlin#LoadProject:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wooshmi/.opam/system/share/ocamlmerlin/vim/autoload/merlin.py", l
ine 544, in load_project
    command = [vim.eval("merlin#FindOcamlMerlin()"), "-project-find", directory
]
vim.error: Vim(echoerr):ocamlmerlin not found!
Error detected while processing function <SNR>11_LoadFTPlugin:
line   17:
E170: Missing :endfor

I have tried everything - reinstalling vim, clearing my .vimrc, deleting all vim extension. I've seen that I'm not the only one that ran into this error, but I couldn't find a solution...

**Comment by justgage** [comment]
Note to others, I can't seem to get merlin to work while I'm logged into the fish shell (despite adding it to my path) it does work when I log in using zsh though.

**Comment by ibnfirnas** [comment]
So I had this issue when using MacVim, while my login shell was `zsh`. Turns-out `.zshrc` is only read by the interractive `zsh`, and `.zprofile` is read otherwise. I symlinked the former to the later and now all is good in the hood.

**Comment by mitcc** [comment]
@ibnfirnas Your solution finally works for me.
