### ISSUE TITLE
Autoclose big type window in emacs

### ISSUE THREAD

**Issue by Drup** [ocaml/merlin#237]
When a type is too big to fit in the minbuffer, merlin opens a new buffer with the whole type. It would be nice if this buffer either 
1) Was not interactive and would close itself on q
2) Would close itself when the cursor move.

Also, a key-binding to put the type/content of this buffer directly in the clipboard would be handy (I use it when I write .mli).

edit : on merlin2.

**Comment by Lionel-Rieg** [comment]
I got the exact same problem.
Auto close would definitely be handy.

**Comment by rgrinberg** [comment]
> Also, a key-binding to put the type/content of this buffer directly in the clipboard would be handy (I use it when I write .mli).

This exists.

> Was not interactive and would close itself on q

That's how it works in the buffer that lsp-mode brings up.

> Would close itself when the cursor move.

Seems quite awkward when you want to copy a part of this buffer.
