### ISSUE TITLE
Better automatic lookup for completion.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/merlin#240]
Writing `.merlin` files is annoying, especially since I'm basically repeating information I have already written somewhere else (e.g. in my `_tags` file, in my `opam` file etc.). Also sometimes I just want to make a test on a small `.ml` files and then completion doesn't work out of the box.

`ocp-index` just looks into the right places for cmti files (`_build` directory, opam current switch `lib` dir), which is damn convenient, no configuration needed.

**Comment by sgronblo** [comment]
Is this issue dead? I'm trying to get into OCaml and was wondering if you really need to update multiple locations when you add a dependency to a project.

**Comment by sgronblo** [comment]
Why are the build systems terrible?

**Comment by dbuenzli** [comment]
> Why are the build systems terrible?

That's OT, but be reassured, I'm going to twist @let-def's arm at some point.

**Comment by let-def** [comment]
As @dbuenzli said. If someone wants to write a minimal parser for `_tags`, please open a PR :).

**Comment by dbuenzli** [comment]
Not a proper parser but such a thing exists in `topkg-care` [here](http://erratique.ch/software/topkg/doc/Topkg_care.OCamlbuild.html#VALpackage_tags).

**Comment by samoht** [comment]
Having a way to parse `_tags` files would be awesome.

**Comment by dbuenzli** [comment]
A few weeks ago we talked with @let-def about another build-system agnostic strategy. Try to use the [build invocation information](https://github.com/ocaml/ocaml/blob/4d2f22f269fda0aeb7d6c547ef366fd4661008b6/typing/cmt_format.mli#L57) recorded in `cmt` files. This could completely kill the need for `PKG` and `FLG` directives for build systems that generate `cmt` files in a given standard build directory. 

@let-def did have a shot at this ? I'd be keen on deleting all these `.merlin` files from my repos.

**Comment by let-def** [comment]
@dbuenzli I am focusing on OCaml 4.05 support at the moment. I will look at this after the release.
