### ISSUE TITLE
merlin does not install with ocaml 4.02.0

### ISSUE THREAD

**Issue by brabalan** [ocaml/merlin#300]
I did a `opam switch 4.02.0` and I cannot install merlin (it worked fine with system, which is 4.02.1). Here is the error message:

```
# File "src/ocaml/typing/typecore.ml", line 2960, characters 10-32:
# Error: This variant pattern is expected to have type
#          (a, b, c, d, e, f) CamlinternalFormatBasics.ignored
#        The constructor Ignored_scan_next_char does not belong to type CamlinternalFormatBasics.ignored
# make[2]: *** [src/ocaml/typing/typecore.cmx] Error 2
# make[1]: *** [native-code] Error 2
# make: *** [ocamlmerlin] Error 2
```

I also reported this on the opam-repository issues list: https://github.com/ocaml/opam-repository/issues/3037

**Comment by chenglou** [comment]
I'm on OCaml 4.02.0, had the same problem so pinned merlin to the git url, but now I have this:

```
# File "src/ocaml/typing/typecore.ml", line 3075, characters 10-19:
# Error: This function has type
#          string -> Parsetree.expression list -> Parsetree.expression
#        It is applied to too many arguments; maybe you forgot a `;'.
```

Any idea? Thanks.

**Comment by gasche** [comment]
This is independent from your report, but you should not use 4.02.0 as it was found to have a major regression in compilation time. Do you have a really good reason not to be using at least 4.02.1, and preferably the latest minor release 4.02.3?

**Comment by chenglou** [comment]
Thanks, 4.02.3 worked.
