### ISSUE TITLE
Visual Studio Plugin

### ISSUE THREAD

**Issue by jordwalke** [ocaml/merlin#304]
Now that visual studio is opening up, it would be really awesome to get merlin to work within it. A lot of people use F# over OCaml on Windows simply because of absence of tooling like merlin for OCaml on Windows.

http://www.visualstudio.com/en-us/products/visual-studio-community-vs

**Comment by bschommer** [comment]
How about supporting Visual Studio Code:
https://code.visualstudio.com/docs/extensions/language-support
It seems at least to me that making ocamlmerlin a language server implementing:
https://code.visualstudio.com/docs/extensions/language-support
seems possible.

**Comment by hcarty** [comment]
@bschommer See https://github.com/hackwaly/vscode-ocaml

**Comment by bschommer** [comment]
@hcarty thanks for the hint, I will have a look at it.
