### ISSUE TITLE
Merlin 1.0.0 under emacs errors

### ISSUE THREAD

**Issue by thelema** [ocaml/merlin#36]
contents of _Messages_ as follows

```
Parsing .merlin file /home/thelema/tcam/.merlin
File mode specification error: (wrong-type-argument number-or-marker-p nil)
Toggling auto-complete-mode off; better pass an explicit argument.
Parsing .merlin file /home/thelema/tcam/.merlin
if: Wrong type argument: number-or-marker-p, nil
```

The result seems to be that I get no contextual completion, just any string it can find with the same prefix.

**Comment by yetanotherion** [comment]
I have a similar issue on mac os x yosemite, GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21).
The backtrace outputs
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  merlin-goto-point(((assoc) (cursor (assoc) (line . 1) (col . 0)) (marker . false)))
  merlin-make-point(((assoc) (cursor (assoc) (line . 1) (col . 0)) (marker . false)))
  merlin-seek-before(1)
  merlin-tell-to-point(1025)
  merlin-sync-to-point(1025)
  merlin-to-end()
  merlin-after-save()
  run-hooks(after-save-hook)
  basic-save-buffer()
  save-buffer(1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)

**Comment by def-lkb** [comment]
@yetanotherion: which version of merlin? latest available in opam?
Can you try with the current git? Or wait a few days, we are planning a release soon.

**Comment by yetanotherion** [comment]
Thanks, the issue is indeed fixed in the current git version.


2015-04-26 21:07 GMT+02:00 def-lkb <notifications@github.com>:

> @yetanotherion <https://github.com/yetanotherion>: which version of
> merlin? latest available in opam?
> Can you try with the current git? Or wait a few days, we are planning a
> release soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-lambda-church/merlin/issues/36#issuecomment-96421342>
> .
>



-- 
Ion
