### ISSUE TITLE
Support for intelligently adding/removing module opens

### ISSUE THREAD

**Issue by hcarty** [ocaml/merlin#396]
It can be useful when writing new code/prototyping an idea to open more modules than you want in a clean codebase.  It would be useful if merlin could automate the steps required to intelligently add or remove local- and module-level `open`s.

For example, to remove an `open Printf` from this code:

``` ocaml
open Printf
let () = printf "Text!"
```

a `:MerlinUnopen` command on `Printf` could transform this snippet into:

``` ocaml
let () = Printf.printf "Text!"
```

The inverse, `:MerlinOpen Printf`, could convert the code in the opposite direction.  Any explicit mentions of the `Printf` module in the context of the module/local `open` would be removed.

Thank you for merlin.  It is a wonderful tool.

**Comment by let-def** [comment]
Thanks for the suggestion. I am closing this issue, development is happening in #613.

**Comment by hcarty** [comment]
Thank you very much!

**Comment by let-def** [comment]
@hcarty: the branch is quite old, I will need to rebase and cleanup before having a usable prototype. If you don't mind beta testing, I can tell you when it is ready.

**Comment by hcarty** [comment]
I'll be happy to test when the code is ready.  We can follow up in #613 when the time comes if that would be better.
