### ISSUE TITLE
code outline bugs

### ISSUE THREAD

**Issue by db4** [ocaml/merlin#422]
Re: code outline feature (issue #155)
This code  

```
let v1 = 1
let v2 = 2
let v3 = 3
```

gives a code outline without v3:

``` json
["tell","file","test.ml"]
["return",{"cursor":{"line":4,"col":0},"marker":false}]
["outline"]
["return",[{"name":"v2","kind":"Value","pos":{"line":2,"col":4},"children":[]},{"name":"v1","kind":"Value","pos":{"line":1,"col":4},"children":[]}]]
```

Looks like the last value is always missing in the outline. And the values' order is reversed. Is it the expected behavior?

Another problem is missing class/object support. Are you going to implement it some day?

**Comment by trefis** [comment]
> Looks like the last value is always missing in the outline 

This only seem to happen when one uses `["tell","file",...]` but not when called from an editor (although the returned cursor is at the same position). I'll investigate.

> the values' order is reversed. Is it the expected behavior?

"Yes". That is, I'm reordering the values based on some weird criteria in the vim plugin, so I didn't really expect the values to be returned in any particular way.  
I could change that if it help you.

> Another problem is missing class/object support. Are you going to implement it some day?

If you have a use for it, sure.

**Comment by db4** [comment]
> This only seem to happen when one uses `["tell","file",...]` but not when called from an editor (although the returned cursor is at the same position). I'll investigate.

Thank you.

> I'm reordering the values based on some weird criteria in the vim plugin, so I didn't really expect the values to be returned in any particular way.

Well, I think the code outline in an editor should preserve language constructs order (including nested ones) otherwise the outline tree view will be very confusing; but anyway I can sort JSON data by the row/column myself.

>>Another problem is missing class/object support. Are you going to implement it some day?

>If you have a use for it, sure.

I'm experimenting with merlin integration into OcaIDE (https://github.com/nbros/OcaIDE). With its internal parser OcaIDE is able to show class/object/method info in the outline view. I would like to keep this feature.

**Comment by trefis** [comment]
OK. I'll add support for classes & cie. and reverse the order of the tree.

As for the problem with `tell file` I will also look into it, but I'd suggest not to use that from an editor (although considering how well documented the protocol is, I understand you chose to use that).

**Comment by def-lkb** [comment]
Just add `["tell","eof"]` after the file.
As for not using that… The protocol will break anyway, it's better to know what you really need so we can tailor the protocol for this use case too.

**Comment by def-lkb** [comment]
(the note about tailoring the protocol is broad: I would be happy to hear about specific needs for OcaIDE/eclipse, if you have any)

**Comment by db4** [comment]
> Just add ["tell","eof"] after the file

Thanks!

> it's better to know what you really need so we can tailor the protocol for this use case too.

I can't tell you for sure yet. I'm not the author of OcaIDE and just experimenting with merlin integration (OcaIDE's author shared his point of view in issue #155). Probably other "tell" variants will used instead of ["tell","file",...]. BTW, it would be great if someone updated protocol.md and other developer docs: the current version is far from been up-to-date.

**Comment by trefis** [comment]
I think that outline should now work as you expect.

**Comment by db4** [comment]
Thank you very much, I'm now experimenting with that. Is it possible to add also objects without classes support (immediate objects and object types)?

**Comment by trefis** [comment]
I can add support for object types, I don't understand what you mean by immediate objects.

**Comment by db4** [comment]
> I can add support for object types, I don't understand what you mean by immediate objects.

Well, it's an object created without a class:
http://caml.inria.fr/pub/docs/manual-ocaml/objectexamples.html#sec25

**Comment by trefis** [comment]
Yes, but do you really want that to show up in the outline?
If you have
```ocaml
let x = {
  foo = 3;
  bar = 'a';
  baz = [];
}
```
you don't want the fields to show up in the outline, you just want `x`.
So why would you want the fields of an object?

Or, perhaps more convincingly:
```ocaml
let x =
  let module M = struct
    let foo = 3
    let bar = 'a'
  end in
  ...
```
once again you only have (and want) `x` in the outline.

**Comment by db4** [comment]
> Yes, but do you really want that to show up in the outline?

I tend to think so. This is how OcaIDE does that now.

> If you have
> ```ocaml
let x = {
  foo = 3;
  bar = 'a';
  baz = [];
}
```
> you don't want the fields to show up in the outline, you just want x.

I probably do. Because Eclipse outline is a tree structure. With current OcaIDE parser it represents the whole Ocaml AST (all top-level nodes are initially collapsed). So I can expand any node and get any desirable level of detail. I'm not sure that it's absolutely necessary in Merlin-generated outline, but sometimes it's quite convenient.

In the meantime I stumbled upon the following problem with pervasives.mli:

```JSON
["seek","before",{"line":0,"col":0}]
["return",{"cursor":{"line":1,"col":0},"marker":false}]
["reset","mli","C:/local/OCaml/lib/pervasives.mli"]
["return",{"cursor":{"line":1,"col":0},"marker":false}]
["tell","source","<...>"]
["return",{"cursor":{"line":1072,"col":0},"marker":false}]
["tell","eof"]
["return",{"cursor":{"line":1072,"col":0},"marker":false}]
["outline"]
["error",{"type":"type","start":{"line":1,"col":-1},"end":{"line":1,"col":-1},"valid":true,"message":"Error: Unbound module Pervasives"}]
```

Other stdlib interfaces don't suffer from that. What could that mean?

**Comment by db4** [comment]
And one more thing I forgot to mention. Outline view also shows type annotations taken from .annot files. If I cannot see the whole tree I just lose that info for all nested elements.

**Comment by trefis** [comment]
Yeah hmm, you don't want to look at the outline at this point.
You want a dump of the typedtree.

**Comment by db4** [comment]
>  You want a dump of the typedtree

Probably so. Is it possible with Merlin?

**Comment by db4** [comment]
I understand it may be too much work. In the meantime can you just add type and ocamldoc info to outline data? It might be "doc" and "type" string fields for Value elements.

BTW, currently "outline" for `let x = 1` gives
```JSON
["return",[{"start":{"line":1,"col":4},"end":{"line":2,"col":0},"name":"x","kind":"Value","children":[]}]]
```
Why end = {2,0} but not {1,5}? I thought it should be right after the identifier, no?

**Comment by def-lkb** [comment]
This is a known problem in the handling of end location of menhir (when the last non-terminal of a production is nullable). We have plans to fix that.
