### ISSUE TITLE
"reset" broken in master branch?

### ISSUE THREAD

**Issue by db4** [ocaml/merlin#424]
PROTOCOL.md says that

```
### ["reset"]
Clear content of virtual buffer.
```

and "reset" really did that before. Now I have switched to master branch and "reset" seems to be ignored:

``` JSON
["reset","ml","test.ml"]
["return",{"cursor":{"line":1,"col":0},"marker":false}]
["tell","source","let x = 1\n"]
["return",{"cursor":{"line":2,"col":0},"marker":false}]
["tell","eof"]
["return",{"cursor":{"line":2,"col":0},"marker":false}]
["outline"]
["return",[{"start":{"line":1,"col":4},"end":{"line":3,"col":0},"name":"x","kind":"Value","children":[]}]]
["reset","ml","test.ml"]
["return",{"cursor":{"line":2,"col":0},"marker":false}]
["tell","source","let x = 1\n"]
["return",{"cursor":{"line":2,"col":0},"marker":false}]
["tell","eof"]
["return",{"cursor":{"line":2,"col":0},"marker":false}]
["outline"]
["return",[{"start":{"line":1,"col":4},"end":{"line":1,"col":9},"name":"x","kind":"Value","children":[]},{"start":{"line":1,"col":13},"end":{"line":3,"col":0},"name":"x","kind":"Value","children":[]}]]
```

Note that  `"let x = 1\n"` value is duplicated.

**Comment by def-lkb** [comment]
Yes, reset is no longer doing as told. It is used to "checkout" the content of a buffer.
The goal is to minimize the logic on editor side. The protocol is still being heavily adjusted.

What you want can be obtained by adding a `["seek","before",{"col":0,"line":0}]`, so that virtual cursor is at the beginning.

**Comment by db4** [comment]
> What you want can be obtained by adding a ["seek","before",{"col":0,"line":0}], so that virtual cursor is at the beginning.

Thanks! Now it works. But is line=0 correct? I thought merlin counted lines from 1.

**Comment by def-lkb** [comment]
Yes lines are counted from 1.
So before line 0 as the effect of clearing the buffer, but before line 1 would work equally well :).
