### ISSUE TITLE
Emacs mode: C-c C-x is evil

### ISSUE THREAD

**Issue by AltGr** [ocaml/merlin#444]
Ths is the default shortcut for `next-error`.

However, "exit emacs" happens to be `C-c C-x`. And `c` and `x` happen to be next to each other on most keyboards.
It would be nice to provide a safer default keybinding.

**Comment by samoht** [comment]
I got caught a couple of times as well, but now I am getting used to it :-)

**Comment by Drup** [comment]
I changed it to C-c C-v, which is as easy and less evil.

**Comment by thranur** [comment]
I concur, I had to add this to my `.emacs` (replaced `C-c C-x` with the letter farthest away from it in the keyboard, and uppercase just to be sure):

    (global-unset-key (kbd "C-x C-c")) ; avoid accidents with merlin's C-c C-x
    (global-set-key (kbd "C-x P") 'save-buffers-kill-terminal) ; for terminal-mode 
                                ; (previous unbinding prevents quitting otherwise)

**Comment by rgrinberg** [comment]
After a few years, it's unlikely this issue is going to be fixed :) I suggest you all slowly migrate to the LSP frontend + eglot or lsp-mode.
