### ISSUE TITLE
Merlin syntax checking doesn't work with ppx_type_conv

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#445]
These are the relevant lines that were added to my .merlin:

```
PKG ppx_deriving
PKG ppx_sexp_conv
```

Here is the error that I get from merlin

```
Cannot load /Users/rgrinberg/.opam/pgd/lib/ppx_type_conv/./ppx_type_conv_deriving.cmxs: error loading shared library: dlopen(/Users/rgrinberg/.opam/pgd/lib/ppx_
type_conv/./ppx_type_conv_deriving.cmxs, 138): Symbol not found: _camlPpx_type_conv__Type_conv__set_ppx_deriving_implementation_4246 Referenced from: /Users/rgrinberg/.opam/pgd/lib/ppx_type_conv/./ppx_t
ype_conv_deriving.cmxs Expected in: flat namespace in /Users/rgrinberg/.opam/pgd/lib/ppx_type_conv/./ppx_type_conv_deriving.cmxs↲
```

**Comment by def-lkb** [comment]
Ok, that's a linking order problem.
Hmm, there is a lot of guessing around what should be done with ppxs.

**Comment by rgrinberg** [comment]
@def-lkb How should I test this? Any branches in particular? Or just apply the patch locally?

**Comment by rgrinberg** [comment]
I've tried the `browse-node` branch which includes the linked commit and it seems to have fixed my problem for now.

One thing I've noticed however, is that merlin's typechecking is noticeably slower on this branch? I get a noticeable delay every time I save in Vim. Maybe I'm imagining things...

Is there an ETA as to when this would make it into master/next release?

thanks again for your hard work @def-lkb

**Comment by def-lkb** [comment]
Most of the time is spent in applying preprocessors.
You can try the [experimental-caching-ppx](https://github.com/the-lambda-church/merlin/tree/experimental-caching-ppx) branch which memoizes preprocessor output and see if that helps.

Ultimately, the current scheme is not efficient, a few tweaks to PPX protocol could help a lot. I will start a discussion upstream.

ETA: branch is near release, one or two weeks unless major bug is discovered

**Comment by rgrinberg** [comment]
The performance seems to be good again. Thanks. Will keep using this and report if there's any issues.

**Comment by trefis** [comment]
The branch has been merged before 2.3, can this issue be closed?

**Comment by drvink** [comment]
This still seems to be broken. Try making a `.merlin` for [ppx_variants_conv](https://github.com/janestreet/ppx_variants_conv) containing the following:

```
PKG compiler-libs.common ppx_core ppx_type_conv
B _build/**
S src
```

and then view `src/ppx_variants_conv.ml`.

**Comment by let-def** [comment]
I was able to run some simple tests. In absence of new complaints, I will close.
