### ISSUE TITLE
Nice to haves, easy to implement methinks 

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/merlin#448]
Small suggestions.

1) Merlin-types buffer should go away when I hit `q`
2) Merlin-types buffer should also know about `merlin-type-enclosing`

**Comment by Fourchaux** [comment]
2) : is this not already the case ?

(Merlin_Master)
Currently, the FIRST invocation of 'merlin-type-enclosing' displays the result
in replacement of the original source code. Would be more convenient to have a new window.

**Comment by fxfactorial** [comment]
2) No, and I'm using merlin master. I want the type signature as usually in the mini buffer when I check in merlin-types buffer, would rather not have a new buffer.

**Comment by trefis** [comment]
1. I agree this is a good idea, why don't you submit a pull request?
2. I don't understand what you mean

**Comment by arichiardi** [comment]
@fxfactorial I think I have noticed it depends on the size of the type. It seems like module signatures are actually creating a new buffer. Not sure I have not checked the source code.

**Comment by Khady** [comment]
A *merlin-types* buffer is created for all signatures, whatever the size. Which is pretty convenient because I can display it all the time.

**Comment by Wilfred** [comment]
I believe 1. is a duplicate of #237.

**Comment by rgrinberg** [comment]
I cannot reproduce this using `lsp-mode`. This is the recommended frontend for merlin now.
