### ISSUE TITLE
Merlin ought to give types when emacs point is hovering over

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/merlin#500]
As said in title, I want merlin to give me the type of something after a timeout when the point is over something and I want that type shown in the mini-buffer.

I've seen this implemented in @infinity0's script here: https://github.com/infinity0/l33tutils/blob/master/devel/emacs/site-lisp/merlin-extra.el
Perhaps we can merge that in.

**Comment by Fourchaux** [comment]
Great.  +1  
Rem: 'emacs-fsharp-mode' has this display, but only the minibuffer is used
https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-doc.el

**Comment by Khady** [comment]
This is now available in https://github.com/Khady/merlin-eldoc too. Wondering if it is necessary to try to include it to merlin-mode directly.

**Comment by rgrinberg** [comment]
It's also done in lsp-ui. I suggest we pursue these fancy features in an editor independent way.
