### ISSUE TITLE
Constructor resolution confusing merlin

### ISSUE THREAD

**Issue by bluddy** [ocaml/merlin#575]
If a module isn't opened but its constructors are used anyway, which is surprisingly allowed, merlin thinks the constructors aren't in the environment.

Steps to reproduce: ocaml 4.03+flambda. Build the compiler itself (make world.opt), then go to `middle_end/closure_conversion.ml`. `Lprim` (around line 43) is not found in the environment, because it's in lambda.ml, which isn't opened.

**Comment by trefis** [comment]
Disambiguation of labels and constructors wasn't working to well at the time, but this should now (i.e. on master) be fine.
