### ISSUE TITLE
merlin-phrase-next

### ISSUE THREAD

**Issue by william3** [ocaml/merlin#606]
thanks very much for this nice wiki. I tried to use "merlin-phrase-next", but get this message (debian jessie, emacs 24.4.1, opam switch 4.04.0) : 

merlin-phrase-next (C-c C-n) returns : 
merlin-phrase-next: Wrong number of arguments: (lambda nil "Go to the phrase indicated by COMMAND.
Returns the position." (let ((cell (cons nil nil))) (merlin/sync-to-end) (let ((--dolist-tail-- (merlin/send-command (list (quote shape) (merlin/unmake-point (point))))) shape) (while --dolist-tail-- (setq shape (car --dolist-tail--)) (merlin--traverse-shape (point) cell shape) (setq --dolist-tail-- (cdr --dolist-tail--)))) cell)), 1

Best regards

**Comment by raphael-proust** [comment]
Have you re-installed merlin since you switched to 4.04.0? Have you updated your .emacs? Can you check what version of `ocamlmerlin` is installed?

This looks like a version mismatch between your emacs config and your merlin binary. (Not certain about that though.)

**Comment by let-def** [comment]
Actually, I didn't port merlin-phrase-next to current version. I have to reimplement it for next release.

**Comment by let-def** [comment]
This is fixed in the version that sould be released around the same time as OCaml 4.05.
