### ISSUE TITLE
Feature: Merlin API search

### ISSUE THREAD

**Issue by let-def** [ocaml/merlin#612]
[experimental-polarity](https://github.com/ocaml/merlin/tree/experimental-polarity) implements a hoogle/ocamloscope like search engine.
It needs a UI (after being ported to latest version :P).

**Comment by rgrinberg** [comment]
That link is broken I think.

**Comment by let-def** [comment]
Thanks.

**Comment by shonfeder** [comment]
Hi! I am interested in this feature, and hoping to use (and would happily help develop) something along the lines of #459.

Would any assistance on this be useful? (E.g., I could make a go at updating the experimental polarity branch to catch up with the state of merlin)
