### ISSUE TITLE
Feature: refactoring of module scope (code-action)

### ISSUE THREAD

**Issue by let-def** [ocaml/merlin#613]
Some refactoring action related to `open`:
- insert `open X`, replacing all `X.x` by `x` in the following code body
- remove `open X`, inserting `X.` where necessary
- insert aliases `module X = Long_name` replacing all references to `Long_name` in the body

The [experimental-open-unopen](https://github.com/ocaml/merlin/tree/experimental-open-unopen) branch implements the first two features.

**Comment by let-def** [comment]
The code-action infrastructure, discussed in #607, seems to be the right place to expose this feature.

**Comment by let-def** [comment]
Merger in master.

**Comment by hcarty** [comment]
So cool, thank you!
