### ISSUE TITLE
Merlin+Atom crashes on Windows 10

### ISSUE THREAD

**Issue by mrakgr** [ocaml/merlin#616]
First time using Ocaml here, but I've verified that it running correctly in the Cygwin terminal. Here are the steps I took to install it:

1) Got the graphical 64-bit 4.02.3 installer [from here.](https://fdopen.github.io/opam-repository-mingw/installation/) The installation went smoothly.
2)
```
opam install merlin
opam user-setup install
```
The second command gave me a bunch of file not found errors towards the end.
3)
```
E:\Downloads>apm install ocaml-merlin
Installing ocaml-merlin to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install language-ocaml
Installing language-ocaml to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install ocaml-indent
Installing ocaml-indent to C:\Users\Marko\.atom\packages done

E:\Downloads>apm install linter
Installing linter to C:\Users\Marko\.atom\packages done
```
This went smoothly.
4) In Atom I made a new `ocaml-test.ml` file and when I saved it this error pops up.
```
Error: write EPIPE
at exports._errnoException (util.js:1026:11)
at Socket._writeGeneric (net.js:706:26)
at Socket._write (net.js:725:8)
at doWrite (_stream_writable.js:307:12)
at writeOrBuffer (_stream_writable.js:293:5)
at Socket.Writable.write (_stream_writable.js:220:11)
at Socket.write (net.js:651:40)
at Interface._writeToOutput (readline.js:241:17)
at Interface.prompt (readline.js:206:10)
at Interface.question (readline.js:219:12)
at file:///C:/Users/Marko/.atom/packages/ocaml-merlin/lib/merlin.coffee:40:20
at file:///C:/Users/Marko/.atom/packages/ocaml-merlin/lib/merlin.coffee:38:11
```
I suppose there are other plugins I could try, but browsing the Ocaml news, I saw that Merlin was made a headline project so I decided to try it first. I'd like to get it going if possible.

**Comment by 314eter** [comment]
If merlin works on the command line, this is an issue with [atom-ocaml-merlin](https://github.com/314eter/atom-ocaml-merlin), so you should open an issue there.
