### ISSUE TITLE
the emacs lisp files are not compatible with emacs.23.1.1

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/merlin#618]
which is the version that ships with centos 6.5

defvar-local should be defvar

then

 Symbol's function definition is void: condition-case-unless-debug

And I give up fixing any further.

**Comment by let-def** [comment]
We just don't have the time to support outdated versions of editors.
I recommend you just upgrade your version of emacs.

**Comment by UnixJunkie** [comment]
Fine, I could install it from sources.
