### ISSUE TITLE
emacs mode: provide an easy way to transfer to result of C-c t to the clipboard

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/merlin#619]
Currently this involves a trip to the `*merlin-types*` buffer which is a bit long winded.

**Comment by samoht** [comment]
+1

That's a little dance that I also do pretty often.

**Comment by let-def** [comment]
Just type `C-w` after selecting which type to copy (with `C-up`/`C-down`)

So `C-c C-t C-w` for copying type (bonus: `C-c C-t C-d` for destructuring a value if possible).

**Comment by dbuenzli** [comment]
Perfect, thanks for reading the manual.
