### ISSUE TITLE
Ability for multiple `.merlin` files in a directory. 

### ISSUE THREAD

**Issue by jordwalke** [ocaml/merlin#622]
Here's the use case:

- A build system for a project already generates a `.merlin` file.
- The package/sandbox manager wants to partake in automatically managing a `.merlin` file (to supply some findlib paths for the sandbox/project).
- It could generate a separate `sandbox.merlin`, just specifying the part that it wants to control (findlib config likely), existing alongside the repo's usual `.merlin` file.

**Comment by let-def** [comment]
How is the `.merlin` selected by merlin?

**Comment by raphael-proust** [comment]
For reference, some of this was mentioned in #614

**Comment by jordwalke** [comment]
@let-def I would imagine that Merlin would merge all of them. The typical use case is that a build system would place additional information in an extra `autogeneratedByBuild.merlin` or something.

**Comment by bobzhang** [comment]
allow such syntax?
-include local.merlin

**Comment by jordwalke** [comment]
@bobzhang That could work as long as perhaps merlin gracefully tolerates the file not being generated yet. (The build system might have cleaned it away etc).

**Comment by rgrinberg** [comment]
Making .merlin files more complex is not a good option. We have a better plan.
