### ISSUE TITLE
How to make merlin locate modules in Extlib?

### ISSUE THREAD

**Issue by tddsg** [ocaml/merlin#625]
Hello,

When using Merlin to locate functions in the ExtLib library, I always encounter this kind of error:

`merlin/locate: Needed cmt file of module ’ExtList’ to locate ’ExtList.List.split_nth’ but it is not present`

Here is my .merlin file (I'm using Emacs):

```
PKG core lwt Z3 camlp4 csv extlib batteries thread core async
S src
S src/*
S src/*/*
S ~/.opam/4.03.0/lib
S ~/.opam/4.03.0/lib/*
S ~/.opam/4.03.0/lib/*/*
S ~/.opam/4.03.0/lib/*/*/*
```

In the configuration of Merlin, I added the ExtLib library and its source.
Can you advise why Merlin needs the *.cmt file to locate the ExtLib? 
It seems that when installing ExtLib by opam, no *.cmt files are generated.

Thank you for taking your time to consider my question!

**Comment by let-def** [comment]
cmt files contain location information (position in the source file) and they are not installed by most packages.
[Letting merlin locate go to stuff in .opam](https://github.com/ocaml/merlin/wiki/Letting-merlin-locate-go-to-stuff-in-.opam) can help you.

**Comment by tddsg** [comment]
This is great! Thank you! Sorry when I googled, the page you mentioned didn't show up in my google result.
