### ISSUE TITLE
[Question] Merlin reports some errors about merlin.hole

### ISSUE THREAD

**Issue by Kakadu** [ocaml/merlin#626]
More precisely `Uninterpreted extension 'merlin.hole'.` Thie error seems to be very merlin-specific and maybe it should not be displayed, i.e. IDE merlin-integration plugin should filter errors like these. Am I understanding it right? Should I report this to IDE-specific merlin plugin?

Maybe merlin can skip sending messages like this at all?

**Comment by let-def** [comment]
Merlin is not producing this error message. It is produced by some janestreet tool, but I don't know the whole story.

**Comment by hhugo** [comment]
I think this has been solved already. What version of ppx_core are you using ?

**Comment by Kakadu** [comment]
I dont think I'm using it.

On Mar 12, 2017 1:06 PM, "hhugo" <notifications@github.com> wrote:

I think this has been solved already. What version of ppx_core are you
using ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ocaml/merlin/issues/626#issuecomment-285934579>, or mute
the thread

**Comment by let-def** [comment]
Actually I was wrong, it can appear on 4.04 with the current released version of Merlin. You would mind trying the dev version?

**Comment by Kakadu** [comment]
Fixed in the dev version
