### ISSUE TITLE
:MerlinLocate (vim) doesn't work in the ocaml compiler repository 

### ISSUE THREAD

**Issue by 0xpr** [ocaml/merlin#628]
Example: 

In the [ocaml](https://github.com/ocaml/ocaml) compiler repository (4.02 branch), I created a .merlin file in the /driver directory

```
S  .
B  .
```

compenv.cmi, compenv.cmo , compenv.cmt,  compenv.cmti, compenv.cmx, compenv.ml    compenv.mli, compenv.o and the corresponding files for optmain.ml all exist (built using make world.opt)

merlin fails on all references to compenv in optmain.ml with either:
   - ($location)/compenv.cmi is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
   - 'readenv' is not in the environment. 

The references are being resolved when I tested it with a simple 2 file ocaml project - it even printed warnings when I didn't use -bin-annot, however I can't get it to work on the ocaml compiler repository itself.

Is this is the intended behavior? And is there any workaround if it is the intended behavior?

**Comment by let-def** [comment]
You are compiling a version of ocaml which is not compatible with your version of merlin.
In your case, you should use merlin for 4.02.

**Comment by 0xpr** [comment]
Ah, I see. I forgot the compiler was being compiled with the bootstrapped version. Thanks!
