### ISSUE TITLE
MerlinTypeOf fails to display in MacVim

### ISSUE THREAD

**Issue by nilsbecker** [ocaml/merlin#629]
since a while i observe that `:MerlinTypeOf` messages are displayed only for a fraction of a second or not at all in the status buffer. this happens whether or not i invoke it via a key map. 

i was thinking this is a bug in MacVim, which could be the case. however , `YankLatestType` always succeeds in showing a correct message, which suggests that this might be a bug in merlin, or a bug in MacVim that could be worked around easily by doing the display in the same way as `YankLatestType`. 

the behavior is unfortunately not always reproducible. fullscreen mode increases the chances of seeing it.

**Comment by raphael-proust** [comment]
I can't reproduce on Ubuntu (default Terminal, default up-to-date vim) with

```
$ ocamlmerlin -version
The Merlin toolkit version 2.5.3, for Ocaml 4.02.3
```

and with

```
$ grep merlin .vimrc
execute "set rtp+=" . g:opamshare . "/merlin/vim"
  let l:dir = s:opam_share_dir . "/merlin/vim"
let s:opam_configuration['merlin'] = function('OpamConfMerlin')
let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
```

**Comment by nilsbecker** [comment]
yes, i also cannot reproduce in terminal vim. i only see it in gui macvim on os x. the symptom is this: focus switches to the status buffer quickly (which i see by a color change) then back to the buffer, but nothing is visible in the status buffer. 

it's likely to be some bug on the macvim side, but as i said above since YankLatestType works it might be possible to work around it easily.

**Comment by let-def** [comment]
Could it be some extensions you are using which is interacting weirdly?
Can you share a listing of `:scriptnames` and `:au`.

**Comment by nilsbecker** [comment]
sorry for the delay, i somehow missed the reply. 

first off: to reproduce, i need to start macvim in gui mode, then do a split with two vertically stacked windows. then from the upper window, invoke `:MerlinTypeOf`. focus will jump down to the status line and then back up, leaving an empty status line. (from the lower window it works). unfortunately, that does not reproduce the bug every time...

i have a ton of extensions and autocommands. scriptnames is 150 lines. 
probably it makes sense to try debugging only when reproducing with a minimal `.vimrc`. how would a minimal `.vimrc` look for Merlin?

**Comment by let-def** [comment]
```viml
set nocompatible
syntax on
filetype plugin on 
set rtp+=~/.opam/xxx/share/merlin/vim
```

**Comment by xguerin** [comment]
I have the same issues, but I cannot reproduce with the minimal `vimrc` above. It must be a plugin conflict then.

**Comment by nilsbecker** [comment]
i retried now with the minimal vimrc. i can reproduce my problems. to do so i have to edit two .ml files in a split (with :split ). displaying type info from the bottom window works everythime. from the top window, it works the first time. but after that i see the focus jump quickly to the status line then back but no type info is displayed.

**Comment by nilsbecker** [comment]
aha: if i also point the .gvimrc to an empty file, the type display works! after then doing `:set macligatures` it stops working. this option was enabled in my gvimrc. so i can confirm that the macligatures option is sufficient to break the type display in merlin on macvim.

**Comment by nilsbecker** [comment]
ok, with my original config files, minus the macligatures option, i get a functioning :MerlinTypeOf. so the macligatures option seems to break it indeed. sounds like an issue of macvim?

**Comment by xguerin** [comment]
Most likely. I am trying to build a minimum test case that does not involve Merlin before posting an issue on the MacVim page.

**Comment by let-def** [comment]
Thanks for these investigations.
We implemented a lot of workaround for various vim bugs. I shouldn't encourage more hacks, but vim is such a mess that it is unavoidable: if you know how to work around the issues in macvim, maybe we can implement a specific path in merlin plugin for handling that.

**Comment by rgrinberg** [comment]
Any editor specific hacks (in this case, it's a hack for a particular frontend of one editor!) are even less attractive today now that we have LSP. Give coc.nvim a try, it's quite likely that it fixed all the display issues for you.
