### ISSUE TITLE
Unbound module errors in toplevel

### ISSUE THREAD

**Issue by cpitclaudel** [ocaml/merlin#630]
Hi there,

If I put `PKG yojson` in my .merlin as suggested to work around "unbound module" errors, FLycheck support in Emacs works just fine.

But then when I press `C-M-x`, the ocaml toplevel that gets started doesn't know about Yojson:

```
    Yojson.Safe.pretty_to_channel (open_out_bin filename) json
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Yojson
```

Is that expected?

**Comment by let-def** [comment]
Yes it is. The toplevel is not managed by Merlin, probably by tuareg in your setup.
There is no immediate solution.
