### ISSUE TITLE
Function argument placeholders with LSP's snippets

### ISSUE THREAD

**Issue by wokalski** [ocaml/merlin#632]
I really like merlin but as an OCaml newbie I don't know function argument count and labels from the top of my head. Many IDEs and vim completion plugins support jumping over arguments which are a great way to solve this issue. (an example at the bottom)

Implementing this functionality from scratch would be a bit of a pain and would probably go beyond the scope of this project. However there are vim plugins like [neosnippet](https://github.com/Shougo/neosnippet.vim) (used in the example), [ultisnips](https://github.com/SirVer/ultisnips), and probably others which handle the jumping part of it. The only thing that autocompletion provider has to do is certain formatting of text in the buffer.

I would like to contribute this functionality. My contribution would just change the text that's inserted after completing a word. The rest is handled by the aforementioned plugins. It would also include an option to enable/disable this feature.

Would you accept it?

![kwi-08-2017 23-43-36](https://cloud.githubusercontent.com/assets/1693190/24832683/475820e4-1cb5-11e7-9615-bb1715b1c2c8.gif)

**Comment by wokalski** [comment]
Here's how it'd work with OCaml.
![kwi-09-2017 00-11-40](https://cloud.githubusercontent.com/assets/1693190/24832835/320f11da-1cb9-11e7-83c0-5d3954087b4b.gif)

**Comment by let-def** [comment]
Yes definitely, this is a valuable feature. Thanks.

**Comment by copy** [comment]
Out of curiosity:

1. Can arguments also be shown as a visual hint? python-jedi, for example, shows it like this:

    ![screenshot_2017-04-09_19-45-00](https://cloud.githubusercontent.com/assets/1816456/24842457/72fd5c0c-1d5d-11e7-98c9-fb2a37cef0dd.png)

2. Is type information available?

**Comment by wokalski** [comment]
1. AFAIK only in the preview window (could you show the full screenshot?).
2. It is available.

What's your idea?

**Comment by copy** [comment]
> AFAIK only in the preview window (could you show the full screenshot?).

It is implemented using setline: https://github.com/davidhalter/jedi-vim/blob/master/jedi_vim.py#L422

> What's your idea?

It would be nice if the types of parameters were shown (either as part of the placeholder or like in python-jedi). Actually, merlin already does this (`g:merlin_completion_arg_type`), but it is shown only in the omni-completion window and just for the current argument.

**Comment by wokalski** [comment]
ah, good catch. I also thought of placeholders which indicate the type but the jedi feature is awesome. Although a bit tricky. What should we do if func call is spread across few lines? Does jedi handle all such cases?

In this combo ideally I imagine that the type of the argument you currently fill is shown above the cursor. I'm afraid it's beyond the scope of this issue though. I'd like to ship it asap.

**Comment by copy** [comment]
Jedi display exactly one line, which is cut of if the signature is too long.

> I'm afraid it's beyond the scope of this issue though.

Sure. Since type information is available I'll play around with this a bit to see if I can make it work.

**Comment by rgrinberg** [comment]
This feature does seem quite exciting, but what do you think of supporting it via LSP snippet completion?

**Comment by wokalski** [comment]
@rgrinberg by now I've had 2 or 3 attempts at supporting this feature. I implemented it a long time ago in a fork but it was a hacky implementation - it was specific to my vim setup. It was pretty nice to use indeed.

It was in the pre merlin-lsp era. Right now LSP would be the way to go IMO.

**Comment by rgrinberg** [comment]
@wokalski Okay, I've updated the issue title appropriately.

**Comment by trefis** [comment]
@rgrinberg I'm closing this one and will let you reopen this on the lsp repository if appropriate.
