### ISSUE TITLE
MerlinTypeOf fails on some expressions after `let%lwt`

### ISSUE THREAD

**Issue by copy** [ocaml/merlin#633]
In this example:

```ocaml
let _ =
  let%lwt a = Lwt.return 5 in
  let b = 6 in
  Lwt.return_unit
```

`MerlinTypeOf` fails on `b` and `6` (and in general, normal let bindings after `let%lwt`).

**Comment by let-def** [comment]
`lwt.ppx` introduces wrong locations.

The pattern that binds the lwt expression `Lwt.return 5` is given a location that covers the whole expression. Hence when you ask anything about the second line, merlin thinks it is this pattern and answer `int Lwt.t`.

Merlin cannot answer properly if locations doesn't match input.

**Comment by copy** [comment]
I see, moved to https://github.com/ocsigen/lwt/issues/337.
