### ISSUE TITLE
Syntax highlighting incorrect for generative functors 

### ISSUE THREAD

**Issue by pacemkr** [ocaml/merlin#640]
Or so I can deduce. Note that the coloring is off starting with the `struct` keyword on the second line.

A screenshot:
<img width="369" alt="image" src="https://cloud.githubusercontent.com/assets/339051/25558010/deafb5c4-2ceb-11e7-9458-1b1c9aa92e2b.png">

The example code: 

```
(* Broken *)
module Functor1 () = struct
end

(* syntax highlighting still incorrect *)
(* Capital cased comment. *)

let fn1 _ = ()
(* Previous line makes it normal again. *)

(* Normal *)
module Functor2 = struct
end
```

Using `vim` with `zenburn` theme. Issue reproducible in 2.5.4 and 2.5.3.

**Comment by hcarty** [comment]
This is an issue with the syntax highlighting setup for vim, not an issue with merlin as merlin doesn't handle syntax highlighting. You could try https://github.com/rgrinberg/vim-ocaml

**Comment by pacemkr** [comment]
Ah, thank you.
