### ISSUE TITLE
ppx extension doesn't quite work

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#651]
Using js_of_ocaml/master merlin/master the following snippet:

```ocaml
let () =
  Dom_html.window##.onload := Dom_html.handler (fun _ -> failwith "")
```

Gives the following error:
```
'##.' is not a valid value identifier.
```

Note that merlin 2.5.4 doesn't work at all. Perhaps it's time for a release?

**Comment by trefis** [comment]
What does your config look like, i.e. are you sure merlin is using the ppx?

I think people at janestreet are using js_of_ocaml-ppx (from git) and merlin (git master as well), and it works fine.
@hhugo will confirm.

**Comment by rgrinberg** [comment]
I moved around some directories in my project and forgot to clean old .merlin files. Sorry for the noise.

**Comment by mheiber** [comment]
What does "merlin is using the ppx" mean?
In order to use Merlin with [Bucklescript](https://github.com/bloomberg/bucklescript), do I have to do something to point Merlin toward Bucklescript ppx files?

**Comment by raphael-proust** [comment]
@mheiber 

https://github.com/ocaml/merlin/wiki/project-configuration documents the syntax of the `.merlin` file.

Search for PPX.
