### ISSUE TITLE
Emacs merlin spurious communication

### ISSUE THREAD

**Issue by tomjridge** [ocaml/merlin#655]
In Emacs, I'm getting a lot of errors like the following:

```
Error in merlin/send-command-async callback: (error "Command ((assoc) (document auto /tmp/l/git/github/snapdev/snapdev.ml) (query errors)) failed with error nil")
error in process filter: tq-process-buffer: Spurious communication from process merlin, see buffer *spurious*<13>
error in process filter: Spurious communication from process merlin, see buffer *spurious*<13>
```
And the spurious 13 buffer contains:

```
("failure" "invalid arguments")
("failure" "Invalid parse")
("failure" "invalid arguments")
("failure" "Invalid parse")
```

The problem seems to manifest after I switch projects (using helm and projectile). 

Restarting merlin doesn't fix things. 

Help!

**Comment by tomjridge** [comment]
If I close the .ml, and then open it again, things seem OK. Some emacs hook not being run when switching buffers via helm/projectile?

**Comment by let-def** [comment]
I think you have multiple versions of merlin / merlin-mode competing (stable and git), is it possible?

**Comment by tomjridge** [comment]
Yes. Thanks very much! :(
