### ISSUE TITLE
Types displayed when using ppx.lwt are incorrect

### ISSUE THREAD

**Issue by Khady** [ocaml/merlin#660]
```ocaml
let test_lwt () =
    let%lwt _value = Lwt.return_none in
    let val2 = 3 in
    Lwt.return val2
```
If I ask for the type of `val2`, merlin tells me it's `_a option Lwt.t` and highlights the whole code except the first line.

Merlin 2.5.4 in emacs.

**Comment by raphael-proust** [comment]
Maybe related to #633 / ocsigen/lwt#337

**Comment by Khady** [comment]
Very probably. I missed it. Thanks
