### ISSUE TITLE
Problem with lwt.ppx, jbuilder and merlin

### ISSUE THREAD

**Issue by bluddy** [ocaml/merlin#661]
Using the master version of lwt, I make use of lwt.ppx and jbuilder. jbuilder builds lwt.ppx with migrate_parsetree etc. As soon as I want to edit in vim, merlin now goes haywire, making it impossible to type anything.

I can't tell what the problem is exactly. Is there a way to view how merlin is running the ppx? I've noticed that the .merlin file includes an argument --as-ppx to give to the ppx, but this argument, though listed in '_build/default/.ppx/lwt.ppx/ppx.exe --help', doesn't seem to actually work. Even after removing the argument though, merlin keeps failing.

**Comment by bluddy** [comment]
Looks like this has to do with [this issue](https://github.com/janestreet/jbuilder/issues/30). Since jbuilder is becoming the standard OCaml build tool, and merlin is already a crucial OCaml tool, I think it's a good idea to make a minor release on opam with this fix.

**Comment by let-def** [comment]
@bluddy Can you try the "beta" branch of merlin? I backported the patch, it it works for your case I will make a minor release.

**Comment by andreypopp** [comment]
I confirm that `merlin@beta` stops failing on `lwt.ppx`.

**Comment by let-def** [comment]
Thanks, I will push a minor update.
