### ISSUE TITLE
Error if the file starts with a number ?

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/merlin#666]
Merlin 3.0.0 dev & OCaml 4.04.1+flambda & Spacemacs & Linux

Funny things happen if the first character of the file is a number:

```1+2 ;; ``` cursor before ' + ' & 'tuareg-eval-phrase' -> int = 1 ??
```1+2 ;;```  cursor after  ' + '  & 'tuareg-eval-phrase' -> int = 2 ??

Also :
```1*2 ;; ``` cursor before ' * ' & 'tuareg-eval-phrase' -> int = 1 ??
```1*2 ;; ``` cursor after  ' * ' & 'tuareg-eval-phrase' ->
```
*2
^
Error: Syntax error
```

With e.g. :
```(1+2) ;; ``` -> int = 3 : OK

**Comment by let-def** [comment]
You are talking only about tuareg. What is merlin error here?

**Comment by Fourchaux** [comment]
Okee. Submit Issue to ocaml/tuareg. 
Wait and See ...
