### ISSUE TITLE
u'Graph.add: class type already defined'

### ISSUE THREAD

**Issue by talex5** [ocaml/merlin#670]
I get this error sometimes when asking Merlin for the type of something. I simplified the example case to this file in my project:

```
module type S = sig
  class virtual x : object
    method private virtual release : unit
  end
end

module Make (C : S) = struct

  class c =
    object
      method private release = ()
    end

  let x = 3
end
```

Asking for the type of `x` produces the error.

My `.merlin` file is (simplified from jbuilder-generated one):

```
FLG -short-paths
```

Merlin is the latest Git version:

```
The Merlin toolkit version git-a2facd4bb772ee0261859382964c30e8401866e8, for Ocaml 4.04.0+afl
```

**Comment by trefis** [comment]
@lpw25 is going to have a look at this.

**Comment by let-def** [comment]
Is it still occuring on current git version?

**Comment by trefis** [comment]
Yes.

**Comment by trefis** [comment]
Actually, I can't reproduce that particular one anymore.
