### ISSUE TITLE
View exported types in the case of mli

### ISSUE THREAD

**Issue by bluddy** [ocaml/merlin#685]
Here's a problem that occurs currently with merlin:

In a.ml, I write

    let foo x y = x

In a.mli, I write

    val foo: int -> int -> int

Inside a.ml, merlin will show me foo's type as being

    val foo: 'a -> 'b -> 'a

which is correct, but is still a problem. Technically, within a.ml, foo's type hasn't been constrained. However, from the perspective of external modules, foo's type *has* been constrained. Scale this example up, and you get to a situation where large amounts of code, which I've tried to constrain and comment using .mli files (which is the recommended OCaml method), do not report the (very important) constrained types from merlin, and I end up writing code 'blind', with merlin providing very limited assistance.

Is there any way we can solve this problem? Is it perhaps solved already somehow? Can we add a command to merlin to use exported types when an mli file is present?

**Comment by rgrinberg** [comment]
> Is there any way we can solve this problem?

Yes, write:

```
let foo : int -> int -> int = fun x y -> ...
```
