### ISSUE TITLE
merlin-command: opam config failed ("/bin/bash: opam: command not found ")

### ISSUE THREAD

**Issue by bschommer** [ocaml/merlin#691]
I get this error message now with version 3.0.1 under emacs. I'm not using opam, however I have merlin installed and in my PATH and it also seems to work without problems except for this additional error.

**Comment by bschommer** [comment]
I suspect this has something to do with the order in which the path to the merlin binary is resolved.

**Comment by let-def** [comment]
`merlin-command` defaults to `opam`, so it is always tried first. If you are not using opam, do you mind manually setting `merlin-command` to "ocamlmerlin" (for instance via customize)?

While the error message might be annoying to you, it is helpful to beginners (opam not in PATH is a common configuration problem). Setting merlin-command to something else than opam should prevent the error message from appearing.

**Comment by bschommer** [comment]
I'm using spacemacs, so I'm not sure how complicated it will be. I will have a look again.

**Comment by bschommer** [comment]
I thought a little bit more about the problem. How about disabling the warning if spacemacs is used. Normally the ocaml layer also performs these test, so it should be safe to assume that the merlin-command is set up right.

**Comment by bschommer** [comment]
No longer a problem for me.
