### ISSUE TITLE
Compiling on Windows

### ISSUE THREAD

**Issue by kkirstein** [ocaml/merlin#692]
Hi,

it looks like since 3.0.0 merlin does not compile on Windows anymore (some POSIX functionality, e.g. /sys/socket.h is missing there). I guess this is needed by the client/server feature of merlin. Are there any plans to support Windows for version 3, maybe by making the POSIX requiring features optional?

**Comment by let-def** [comment]
Windows support is being worked on. @dra27 made wonderful progress, you can track that https://github.com/ocaml/merlin/pull/684 .
