### ISSUE TITLE
Company backend is slow

### ISSUE THREAD

**Issue by ul** [ocaml/merlin#694]
I use merlin as a part of `ocaml` layer of Spacemacs with `company` being an autocompletion engine. When autocompletion triggers it freezes emacs for a second or two. In VSCode it works instantly in the same project.

How could I help in investigation and fixing that problem?

**Comment by let-def** [comment]
Can you share the version of all software (and the output of M-x merlin-version), and also the content of the `*message*` buffer after trying to complete a few times?

**Comment by ul** [comment]
```
The Merlin toolkit version 3.0.2, for Ocaml 4.02.3+BS

Quit
[No matches]
ReactDOMRe :  <module>
ReactDOMRe.Style :  <module>
```

During autocomplete request nothing is logged into `*Messages*`, lines above appeared as a consequence of selecting something or cancelling.

**Comment by ul** [comment]
Spacemacs v.0.200.9 (develop branch)
Emacs GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-22

**Comment by basus** [comment]
I am getting the same issue with the same setup on OS X. To me, it looks like the keyboard locks up while the completion finishes, so I can't see what I'm typing for a while. I'm not using Merlin with any other editor, so I'm not sure if it's Merlin being slow, or a concurrency issue with how Merlin interacts with `company`.

**Comment by let-def** [comment]
This could be a communication issue on OS X... I will try to reproduce your setup this week-end.

**Comment by basus** [comment]
I'm having the same issue using Spacemacs on Arch Linux.

**Comment by bikalgurung** [comment]
I am experiencing similar issue in emacs/red hat linux 7.4 with merlin pinned to dev version. i.e. I definitely notice a freeze when merlin tries to autocomplete.

**Comment by let-def** [comment]
I have no problem with emacs & merlin on Archlinux. I am trying with spacemacs.

**Comment by rgrinberg** [comment]
I'm also experiencing some delays with newest merlin and I use spacemacs. But they're really not predictable or reproducible.

From my limited knowledge of emacs however, I see that merlin is essentially relying on the `call-process-region` primitive which is a sync operation. Did the previous versions of merlin use this?

**Comment by let-def** [comment]
No the previous Merlin didn't. But Emacs is very bad at concurrency (it was failing in bad ways when different plugins tried to call merlin), the new protocol was designed to work around this and use call-process-region.

**Comment by let-def** [comment]
@rgrinberg Do you think GC can explain the pause you are observing? (not predictable but rare)

If I understand well, other people are having a different issue. It is always slow when invoking company-mode (hence very predictable)?

**Comment by ul** [comment]
In my case company-mode is always slow, and delay is of the same magnitude every time.

**Comment by ul** [comment]
I investigated another perf pain point in my Spacemacs setup related to helm-projectile and encountered that thread https://github.com/syl20bnr/spacemacs/issues/4207

After putting `(setq shell-file-name "/bin/sh")` in my config I've got decent completion speed. Lag is still noticeable, but doesn't ruin my flow now.

Does merlin execute its binary on every completion? I thought it starts in server mode and elisp client then communicates with it.

**Comment by rgrinberg** [comment]
> Does merlin execute its binary on every completion? I thought it starts in server mode and elisp client then communicates with it.

I believe the new "stateless" protocol starts a binary for every command. Perhaps that's what started the slowness for you?

**Comment by ul** [comment]
Yes, if it starts it for every command inside default shell then it is definitely the main source of slowness in my case. Because I have `nvm` initialisation in my `fish` shell config, which delays shell start for a few seconds.

**Comment by let-def** [comment]
Indeed, the new emacs mode starts a lightweight wrapper for all command. The wrapper itself is fast, but I wasn't thinking about the intermediate shell.

I will try to disable shell invocation and directly exec the binary from emacs (but `merlin-mode` is already using `call-process-region` which should not go through a shell?).

**Comment by let-def** [comment]
Indeed, I used a fake shell that waits two seconds before doing anything and completion speed wasn't affected.
Opening the buffer was slow because merlin-mode calls opam through a shell to find where the binary is.

@ul something else is calling the shell (or making company/merlin/... calls a shell) during completion. Can you investigate?

**Comment by ul** [comment]
TBH I'm Emacs noob. How to trace shell calls within Emacs?

**Comment by zcassini** [comment]
Setting `(setq shell-file-name "/bin/sh")`  made a world of difference for me.

**Comment by trefis** [comment]
Ping.

**Comment by bacam** [comment]
I've been having problems like this so I tried stracing emacs.  It's calling `opam config var bin` via the shell for every invocation of merlin if you use opam to find the merlin binary.

(Curiously, it turns out that the shell isn't my problem. Instead I find that merlin is taking a while to respond to emacs, even though it returns quickly when run from the terminal.  I didn't manage to find out why.)

**Comment by rgrinberg** [comment]
Please try using lsp-mode or eglot on Emacs in conjunction with [ocaml-lsp](https://github.com/ocaml/ocaml-lsp). We don't have the resources to fix issues with the individual editor backends.
