### ISSUE TITLE
Merlin does not compiler on FreeBSD

### ISSUE THREAD

**Issue by orbitz** [ocaml/merlin#695]
`src/platform/os_ipc_stub.c:6:10: fatal error: 'alloca.h' file not found`

On FreeBSD, alloca is in `stdlib.h`.

**Comment by let-def** [comment]
@bschommer contributed a fix: https://github.com/ocaml/merlin/pull/687
Is master still not building for you?

**Comment by orbitz** [comment]
This commit seems to be the cause of not compiling.  Master does not build.

**Comment by let-def** [comment]
Ah, stupid me. That makes sense sorry.

**Comment by let-def** [comment]
@bschommer: is stdlib including alloca in your setup? (Or do we need to ifdef the code :/)

**Comment by orbitz** [comment]
I modified the code to get it installing, however now I'm seeing:

["exception","Yojson.Json_error(\"Line 1, bytes 66-99:\\nInvalid token 'ests/abb_fut/test_ustate.ml\\\") (qu'\")"]
["exception","Yojson.Json_error(\"Line 1, bytes 99-132:\\nInvalid token 'ery protocol version 3))\\n((assoc)'\")"]
["exception","Yojson.Json_error(\"Line 1, bytes 133-166:\\nInvalid token '(document auto \\\"/usr/home/orbitz/'\")"]
["exception","Yojson.Json_error(\"Line 1, bytes 166-199:\\nInvalid token 'projects/acsl/abb_intf/tests/abb_'\")"]
["exception","Yojson.Json_error(\"Line 1, bytes 199-232:\\nInvalid token 'fut/test_ustate.ml\\\") (query tell '\")"]
["exception","Yojson.Json_error(\"Line 1, bytes 232-265:\\nInvalid token 'start end \\\"module Ustate = struct'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 2-35:\\nInvalid token 'type t = int\\nend\\n\\nmodule Fut = Ab'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 35-68:\\nInvalid token 'b_fut.Make(Ustate)\\nopen Fut.Infix'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 68-101:\\nInvalid token '_monad\\nopen Fut.Infix_app\\n\\nlet te'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 101-134:\\nInvalid token 'st1 =\\n  Oth.test\\n    ~desc:\\\\\\\"Modi'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 134-167:\\nInvalid token 'fy the ustate and verify it takes'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 168-201:\\nInvalid token 'effect\\\\\\\"\\n    ~name:\\\\\\\"Ustate updat'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 201-234:\\nInvalid token 'e\\\\\\\"\\n    (fun _ ->\\n       let fut1'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 235-268:\\nInvalid token '= Fut.put_state 2 in\\n       let ('\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 268-301:\\nInvalid token '_, us) = Fut.run_with_state fut1 '\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 301-334:\\nInvalid token '(Fut.State.create (), 1) in\\n     '\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 336-369:\\nInvalid token 'assert (us = 2))\\n\\nlet test2 =\\n  O'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 369-402:\\nInvalid token 'th.test\\n    ~desc:\\\\\\\"Modify ustate'\")"]
["exception","Yojson.Json_error(\"Line 2, bytes 403-436:\\nInvalid token 'with a random value\\\\\\\"\\n    ~name:\\\\'\")"]
["failure","invalid arguments"]

I'm just doing merlin-restart-process in emacs, do I need to do something else when switching to the new install?

**Comment by let-def** [comment]
It seems emacs is still communicating with the old version of merlin. You need to make it use the new binary.

**Comment by orbitz** [comment]
I've created pull request #696

**Comment by bschommer** [comment]
In my setup it is not including `alloca`, probably due to some macro missing. I would suggest guarding the include of `alloca.h` with an ifdef for linux see [man](http://man7.org/linux/man-pages/man3/alloca.3.html).

**Comment by let-def** [comment]
I merged @orbitz patch, I will close this issue for now.
Also maybe I will just remove the use of alloca. This is not performance critical, a simple malloc should do good enough.
