### ISSUE TITLE
generated files

### ISSUE THREAD

**Issue by vzaliva** [ocaml/merlin#697]
I have ML files which are generated from other languages. In particular, I have Menhir parser generated for .mly file and some OCaml types extracted from Coq. When I re-generate these files outside of Emacs, merlin does not notice that they have changed and shows lot of errors based on old content.

It would be great for Merlin to know how to regenerate these files. For example, project file may have some directives like:

`DEP parser.ml parser.mly make
`

which says that `parser.ml` depends from `parser.mly` and could be rebuilt running `make` command.

**Comment by let-def** [comment]
Hm, this is not the intended workflow of merlin: you invoke make from your editor (or whatever build system you are using) and Merlin catches the changes.

Merlin don't notice mly and generated ml files have changed because it doesn't look for them in the first place.
