### ISSUE TITLE
Unbound value from ppx_deriving function

### ISSUE THREAD

**Issue by graymalkin** [ocaml/merlin#702]
I have some code like this

```ocaml
type variable = string
  [@@deriving show] (* DBG *)

(* ... *)
let my_fun (f: variable) =
    Printf.printf Format.std_formatter "%s\n" (show_variable f)
```

and Merlin complains with an error of `Unbound value show_variable`.

I have a `.merlin` file which contains `PKG ppx_deriving`

I've tried `ppx_deriving.show` and `ppx_deriving.std` too.

Versions:
- merlin: `The Merlin toolkit version 3.0.2, for Ocaml 4.04.0`
- ocaml: `4.04.0`

**Comment by let-def** [comment]
I cannot reproduce. I have ppx_deriving 4.2.
```
$ cat .merlin
PKG ppx_deriving.show
$ cat test.ml
type variable = string
  [@@deriving show] (* DBG *)

(* ... *)
let my_fun (f: variable) =
    Printf.printf "%s\n" (show_variable f)
```
Can you try with latest packages?

**Comment by rgrinberg** [comment]
I cannot reproduce either.
