### ISSUE TITLE
nuclide not picking up merlin

### ISSUE THREAD

**Issue by kennetpostigo** [ocaml/merlin#703]
I reset my laptop recently and was setting up my editor and noticed that autocomplete and type hints weren't showing in nuclide. I don't think it is picking up opam merlin installation. Not sure why, but this goes away if I use [reason-cli](https://github.com/reasonml/reason-cli). It picks up reason-cli's vendored ocamlmerlin. However I don't necessarily want reason-cli because i'm working on native stuff and less web things at the moment. 

OS: macOS Sierra 10.12.6
Ocaml version: 4.02.3 installed using OPAM
Tried with: merlin.2.5.4 and merlin.2.5.3, nuclide not compatible with merlin3.0.0

The project i'm working deps are: lwt, alcotest, bisect_ppx.

OCaml, Merlin, and refmt path:
```
/Users/kennetpostigo/.opam/4.02.3/bin/ocaml
/Users/kennetpostigo/.opam/4.02.3/bin/ocamlmerlin
/Users/kennetpostigo/.opam/4.02.3/bin/refmt
```

```
Ocamlmerlin raised an error: 
[
  "error",
  {
    "type":"type",
    "sub":[],
    "valid":true,
    "message":"Error: Error while running external preprocessor\nCommand line: /Users/kennetpostigo/.opam/4.02.3/lib/bisect_ppx/./ppx.exe --as-ppx '/var/folders/94/f0jjqvnx52s_qc5kwtk8ftbm0000gn/T/camlppxa1280e' '/var/folders/94/f0jjqvnx52s_qc5kwtk8ftbm0000gn/T/camlppx24b281' 1>/dev/null 2>/dev/null"
  }
]
```

as well as: 
```
[ERROR] datatip - Error getting datatip from provider nuclide-type-hint Ocamlmerlin returned an error
Error: Ocamlmerlin returned an error
    at Interface.reader.on.line (/Users/kennetpostigo/.atom/packages/nuclide/pkg/nuclide-ocaml-rpc/lib/MerlinProcess.js:525:16)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:247:10)
    at Interface.<anonymous> (readline.js:384:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:383:11)
    at Socket.ondata (readline.js:107:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

**Comment by aantron** [comment]
I guess Bisect is involved, but the error message is pretty unhelpful. When Bisect fails "deliberately," it prints to stderr, and it looks like that was redirected, making it hard to know what happened.

I could try running merlin with Bisect.

However, I think your build system should be set up not to have Bisect_ppx enabled by default. That should be enough to prevent it from being pulled in. Somehow, Bisect should be enabled only when you want to generate a coverage report (so not in the setup used by merlin).

**Comment by let-def** [comment]
Also you should really update to Merlin 3, it is backward compatible.

**Comment by kennetpostigo** [comment]
@let-def when I tried to use Merlin 3 nuclide would give me compatibility errors:
```
[ERROR] nuclide-ocaml-rpc - Unsupported merlin version: 3.0.2
```

**Comment by let-def** [comment]
Then nuclide should be updated. Just relaxing the check might be enough.
