### ISSUE TITLE
Parse error: [label] expected after "#" (in [expr])

### ISSUE THREAD

**Issue by anemator** [ocaml/merlin#704]
The project builds and runs (in Chrome) as expected, but I see that parse error while using merlin from within vim with the following setup:
- ocaml 4.05.0
- jbuilder 1.0+beta12
- merlin 3.0.2
- js_of_ocaml, js_of_ocaml-ppx 3.0

~~~ocaml
(* main.ml *)
let () =
  let str = Js.string "blah" in
  Dom_html.window##alert str (* error on this line *)
~~~

~~~lisp
; jbuild
(jbuild_version 1)

(executable
 ((name main)
  (preprocess (pps (js_of_ocaml-ppx)))))
~~~

~~~sh
# .merlin, generated by jbuilder
B _build/default
FLG -ppx '/Users/rob/Repos/test2/_build/default/.ppx/js_of_ocaml-ppx/ppx.exe --as-ppx'
FLG -w -40
PKG bytes
PKG js_of_ocaml
PKG uchar
~~~

**Comment by let-def** [comment]
The error message in the title is generated by camlp4 not by merlin.
I guess you are using syntastic, what is the output of `:SyntasticInfo`?
Merlin is enabled with `let g:syntastic_ocaml_checkers = ['merlin']`

**Comment by anemator** [comment]
Thank you! I had both merlin and camlp4o in that list (for years now). Simplifying it to just the one checker as you've written fixed the problem.

Thanks again and for the quick response.
