### ISSUE TITLE
merlin fails to find local definition

### ISSUE THREAD

**Issue by rgrinberg** [ocaml/merlin#708]
Try to find the definition of the `env` binding on the right hand side of this let binding:

https://github.com/rgrinberg/utop/blob/dev/src/lib/uTop_main.ml#L1449

The bindings is defined just a few lines above however

**Comment by let-def** [comment]
Have you tried in a file that doesn't include preprocessor definitions?

**Comment by trefis** [comment]
#806 is a duplicate of this one, but as it contains an easier snippet to reproduce the issue I'll keep it alive and close this one instead.
