### ISSUE TITLE
Unable to install Merlin on macOS

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/merlin#722]
Hi! New to OCaml; and I'm trying to install Merlin to use Facebook's Nuclide.

Unfortunately, I get this:

```
❯ ~ opam install merlin
The following actions will be performed:
  ∗  install merlin 3.0.2

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[default] https://opam.ocaml.org/archives/merlin.3.0.2+opam.tar.gz downloaded

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of merlin failed at "make -j 4".

#=== ERROR while installing merlin.3.0.2 ======================================#
# opam-version 1.2.2
# os           darwin
# command      make -j 4
# path         /Users/ec/.opam/system/build/merlin.3.0.2
# compiler     system (4.05.0)
# exit-code    2

------8<-----------

### stderr ###
# [...]
# src/frontend/ocamlmerlin.c:1:10: fatal error: 'stdlib.h' file not found
# #include <stdlib.h>
#          ^
# 1 error generated.
# make: *** [ocamlmerlin] Error 1
```

If I were writing C, I'd throw a `-v` at `clang`, but I'm really not sure where to start in debugging this, since I'm so new to OCaml.

Any assistance is greatly appreciated! <3

----

 - macOS: **10.13** Beta (17A362a)
 - OCaml: **4.05.0**, installed with opam **1.2.2**, installed with Homebrew
 - clang: version **3.8.1**

**Comment by let-def** [comment]
I would guess something is wrong with your setup and this has nothing to do with Merlin.

I saw discussions on IRC relating to a similar problem that was solved at the system level. Am I right to assume it was you and that this issue can be closed?

**Comment by ELLIOTTCABLE** [comment]
Actually, that hadn't solved it; but your reminder to take a second stab at Merlin *did* lead me to a solution.

Turns out, for whatever reason, Merlin isn't building under LLVM-clang on macOS 10.13. I was unable to reproduce on 10.12.

The workaround that did it for me was to abandon clang entirely for LLVM-gcc:

    CC=gcc opam install merlin

Hope this is helpful to someone other than myself — and thanks for the glance, @let-def, even though it ended up being something you couldn't have helped with given the available information. `(=`
