### ISSUE TITLE
Use asynchronous completion for emacs

### ISSUE THREAD

**Issue by edwintorok** [ocaml/merlin#725]
Merlin in Emacs is usually "fast enough", however here is a file where completion can take several seconds with OCaml 4.05.0 and Merlin 3.0.2, which delays input:
https://github.com/yminsky/incremental-tutorial/blob/master/solutions/ex4.ml#L56

Try typing `(s >>| State.hosts)`, the `hosts` takes several seconds to appear when typed.

Company mode apparently supports [asynchronous completion](https://github.com/company-mode/company-mode/commit/5cef93597739782b9be4b9ffdae686cffc0c7946#diff-e82edc9ca8f099fbc91caf8a1b78635), would be nice if merlin supported it.

However looking at https://github.com/ocaml/merlin/blob/master/emacs/merlin.el#L889 I don't know enough elisp to implement it, it would seem that `let*` would have to be turned into lots of callbacks and lambdas. Maybe something like these could help? https://jyp.github.io/posts/elisp-cps.html https://github.com/dcolascione/elisp-generators https://github.com/jordonbiondo/promises.el

**Comment by rgrinberg** [comment]
Async completion with company mode would be awesome to have. I've implemented such completion for utop's emacs mode and it works great. The only thing that we really need is for merlin to use the async process primitives emacs provides.

**Comment by rgrinberg** [comment]
If you use lsp-mode or eglot, completion is already asynchronous. It's not worth it to reinvent this here.
