### ISSUE TITLE
condition-case: merlin: error (end-of-file) trying to parse answer:

### ISSUE THREAD

**Issue by Ninjapouet** [ocaml/merlin#733]
On ubuntu bash under windows 10, merlin (at 8978ef2) fails with the above message. When trying to manually invoke the showing type command on the file foo.ml:

> let foo = 42

i got the following:

> $ MERLIN_LOG=~/foo.log ocamlmerlin server type-enclosing -protocol sexp -verbosity 0 -filename /home/ninjapouet/foo.ml -position 1:5 -index 0
sendmsg: Invalid argument
merlin path: /home/ninjapouet/.opam/4.04.2/bin/ocamlmerlin-server
socket path: /tmp/ocamlmerlin_1000_16_281474976999922.socket

**Comment by let-def** [comment]
Which version of merlin?

**Comment by let-def** [comment]
Ahah you put the git commit, sorry for my stupid question.

**Comment by let-def** [comment]
Hmm, ok, sendmsg is maybe not behaving properly in this system.

**Comment by dra27** [comment]
It's pure Ubuntu at this point - just a different kernel

**Comment by let-def** [comment]
What is the build number of your Windows? Are you running Creator or Anniversary edition?

**Comment by Ninjapouet** [comment]
Windows 10 Entreprise 10.0.14393, but my Ubuntu bash uses the 14.04. Seems that there may be some issues with it, i'll try to update to 16.04.

**Comment by let-def** [comment]
According to "https://msdn.microsoft.com/en-us/commandline/wsl/release_notes" support for ancillary data (which merlin uses) has been added to build 15042 (and according to another issue, the proper fix came a bit later, maybe in 15046 / Creators update).

**Comment by Ninjapouet** [comment]
Damn Windows ! :smile:  I can't upgrade it for now but it seems clear the issue doesn't come from merlin. Let's continue using a good Linux VM for now. I'll keep you inform whenever the issue persists.

**Comment by dra27** [comment]
@Ninjapouet - just FYI, the version of Windows relates to the effective version of the Linux kernel you're using, so `sendmsg` will be the same regardless of whether you use 14.04 or 16.04. WSL is a reasonably fast-moving target, so I'm afraid you may struggle if you're stuck on the long-term service branch (which 14393 suggests you probably are)

**Comment by Ninjapouet** [comment]
Just for information : i tested  merlin on Windows 15065's Ubuntu bash and it works :smile:
