### ISSUE TITLE
Please make `merlin-locate/pop-stack` aware of xref

### ISSUE THREAD

**Issue by ejgallego** [ocaml/merlin#735]
It would be great if `merlin-locate` could integrate with standard emacs [xref](https://www.gnu.org/software/emacs/manual/html_node/emacs/Xref.html) instead of shipping its own solution.

**Comment by let-def** [comment]
This would be nice. However we currently have no emacs user in Merlin team.
My elisp is good enough to fix most bugs but not for integrating emacs features.
Would you mind doing a PR?

**Comment by ejgallego** [comment]
I will try once I a get a free slot.

**Comment by let-def** [comment]
I am ready to help on Merlin side :).

**Comment by rgrinberg** [comment]
I gave this a try in #776. I don't think we need to change much in merlin, just have a proper xref backend and tell users to use the xref functions for finding the definition and manipulating the stack.

**Comment by ejgallego** [comment]
That's great @rgrinberg , thanks, in fact the other day I spent a few minutes learning the xref API, but have been too busy to attack this yet, sorry.
