### ISSUE TITLE
Separating warnings and errors in Vim / ALE

### ISSUE THREAD

**Issue by mmottl** [ocaml/merlin#736]
There doesn't currently seem to be any way to distinguish between errors and warnings in Vim with ALE.  I'd like to highlight them differently.  Could you please add such a feature?

**Comment by copy** [comment]
This is fixed in #656 (cc @trefis, I'd suggest to have another look at this PR).

**Comment by copy** [comment]
This issue is fixed in master and can be closed.

**Comment by let-def** [comment]
Thanks!
