### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by Meai1** [ocaml/merlin#743]
I just did a fresh install of everything on a fresh Ubuntu 17.10 VM, how do I fix this?

Steps:

> npm install -g https://github.com/reasonml/reason-cli/archive/3.0.0-bin-linux.tar.gz
> npm install -g bs-platform
> bsb -init my-first-app -theme basic-reason 
> cd my-first-app
> npm run start

`Js.log "Hello, BuckleScript and Reason!";`

> [merlin] invalidCharacter.orComment.orString
> {
>   module Internal = Js_internal;
>   type t(+'a);
>   type null(+'a);
>   type undefined(+'a);
>   type nullable(+'a);
>   type null_undefined('a) = nullable('a);
>   external toOption: (nullable('a)) => option('a) = "#null_undefined_to_opt";
>   external test: (nullable('a)) => bool = "#is_nil_undef";
>   external testAny: ('a) => bool = "#is_nil_undef";
>   type boolean;
>   type promise(+'a, +'e);
>   external true_: boolean = "true" "BS:2.0.0����
> �@@��$true@@";
>   external false_: boolean = "false"
>     "BS:2.0.0����
> 
> �@@��%false@@";
>   external null: null('a) = "" "BS:2.0.0����
> �@@��$null@@";
>   external undefined: undefined('a) = ""
>     "BS:2.0.0����
> �@@��)undefined@@";
>   external to_bool: (boolean) => bool = "#boolean_to_bool";
>   external typeof: ('a) => string = "#typeof";
>   external log: ('a) => unit = "log"
>     "BS:2.0.0����    ���B�@@F��#log@@�'console@";
>   external log2: ('a, 'b) => unit = "log"
>     "BS:2.0.0����! ���B�@��B@F��#log@@�'console@";
>   external log3: ('a, 'b, 'c) => unit = "log"
>     "BS:2.0.0����$
> '&���B�@��B��B@F��#log@@�'console@";
>   external log4: ('a, 'b, 'c, 'd) => unit = "log"
>     "BS:2.0.0����)-,���B�@��B��B��B@F��#log@@�'console@";
>   external logMany: (array('a)) => unit = "log"
>     "BS:2.0.0����    ���@�@@F��#log@A�'console@";
>   external unsafe_lt: ('a, 'a) => bool = "#unsafe_lt";
>   external unsafe_le: ('a, 'a) => bool = "#unsafe_le";
>   external unsafe_gt: ('a, 'a) => bool = "#unsafe_gt";
>   external unsafe_ge: ('a, 'a) => bool = "#unsafe_ge";
>   module Null = Js_null;
>   module Undefined = Js_undefined;
>   module Nullable = Js_null_undefined;
>   module Null_undefined = Js_null_undefined;
>   module Exn = Js_exn;
>   module Array = Js_array;
>   module String = Js_string;
>   module Boolean = Js_boolean;
>   module Re = Js_re;
>   module Promise = Js_promise;
>   module Date = Js_date;
>   module Dict = Js_dict;
>   module Global = Js_global;
>   module Json = Js_json;
>   module Math = Js_math;
>   module Obj = Js_obj;
>   module Typed_array = Js_typed_array;
>   module Types = Js_types;
>   module Float = Js_float;
>   module Int = Js_int;
>   module Option = Js_option;
>   module Result = Js_result;
>   module List = Js_list;
>   module Vector = Js_vector;
> }
>

**Comment by phongphan** [comment]
Looks like ReasonML 3 is no longer support OCaml function all syntax.

Change
`Js.log "Hello, BuckleScript and Reason!";`
to
`Js.log("Hello, BuckleScript and Reason!");`
would work.
