### ISSUE TITLE
error "type" field documented incorrectly

### ISSUE THREAD

**Issue by mroch** [ocaml/merlin#745]
the docs say that the "type" field of the "errors" response should be:

https://github.com/ocaml/merlin/blob/1f9a49822d29f1a7fb2dbc59881cfe4622f0b3c5/src/frontend/new/new_commands.ml#L169

also mentioned in [OLD-PROTOCOL.md](https://github.com/ocaml/merlin/blob/1f9a49822d29f1a7fb2dbc59881cfe4622f0b3c5/doc/dev/OLD-PROTOCOL.md#error-management) and [PROTOCOL.md](https://github.com/ocaml/merlin/blob/1f9a49822d29f1a7fb2dbc59881cfe4622f0b3c5/doc/dev/PROTOCOL.md#errors)

but they seem to be just "warning" and "error":

https://github.com/ocaml/merlin/blob/1f9a49822d29f1a7fb2dbc59881cfe4622f0b3c5/src/frontend/query_json.ml#L198-L200

**Comment by mroch** [comment]
ah, ok, I see this was correct in 2.5 (except for the "unkown" typo :)):

https://github.com/ocaml/merlin/blob/957e551140587f0cd83d9186a06fba10a38c6084/src/ocaml_aux/error_report.ml#L44-L69

is this just a docs issue or a bug? we're updating nuclide's response validation here: https://github.com/facebook/nuclide/blob/41667df3c517061797928785904c118bf8a1837c/pkg/nuclide-ocaml-rpc/lib/MerlinService.js#L33

**Comment by let-def** [comment]
I rewrote error report implementation to follow the protocol documentation (and fixed the spelling of unknown). :)
