### ISSUE TITLE
Merlin autocomplete not working in vim 

### ISSUE THREAD

**Issue by FyreeW** [ocaml/merlin#746]
After installing Merlin through opam and following [these](https://opam.ocaml.org/blog/turn-your-editor-into-an-ocaml-ide/) instructions, the Merlin autocomplete does not show up like shown:
![image](https://user-images.githubusercontent.com/22550097/32313633-e4a5ad9e-bf71-11e7-812d-dacc05c7fdaf.png). Are there any additional steps needed to get autocomplete working?

**Comment by copy** [comment]
If you don't use any particular plugin, you can trigger the completion menu by pressing c-x c-o and navigate the menu using c-n and c-p.

For more convenience, I would suggest installing [supertab](https://github.com/ervandew/supertab), [neocomplete](https://github.com/Shougo/neocomplete.vim) or [deoplete](https://github.com/Shougo/deoplete.nvim) and set them up as documented [here](https://github.com/ocaml/merlin/blob/a2facd4bb772ee0261859382964c30e8401866e8/vim/merlin/doc/merlin.txt#L333-L360).

**Comment by FyreeW** [comment]
I tested c-x c-o on `List.`, and it seems to be working correctly. Is it possible to set it up where it triggers automatically (right now requires c-x c-o), and becomes more accurate as I type (if I type `List.c` it will only look for List functions that start with c)?

**Comment by hcarty** [comment]
The completion pop-up won't show automatically unless you have a separate plugin installed and setup to trigger that action.

**Comment by FyreeW** [comment]
Would something like deoplete do that?

**Comment by copy** [comment]
> Would something like deoplete do that?

Yes.

**Comment by copy** [comment]
@FyreeW If this works for you, could you close the issue?
