### ISSUE TITLE
Type error at installation

### ISSUE THREAD

**Issue by rafoo** [ocaml/merlin#747]
Hello,

I would like to try merlin but I fail to install it. I try to install the `merlin` opam package and get the following type error:

```
File "src/ocaml/typer/typing/typecore.ml", line 3019, characters 10-16:
Error: This variant pattern is expected to have type
         (a, b, c, d, e, f, g, h, i, j, k, l)
         CamlinternalFormatBasics.fmtty_rel
       The constructor Any_ty does not belong to type CamlinternalFormatBasics.fmtty_rel
Hint: Did you mean Int_ty?
```

I am running Debian/GNU/Linux and my opam swith is `4.02.1`. I have attached opam build files.

[merlin-22484-6d07ae.zip](https://github.com/ocaml/merlin/files/1447697/merlin-22484-6d07ae.zip)

**Comment by trefis** [comment]
Thanks for the report, this is now fixed on master.

However, I encourage you to update to OCaml 4.02.3, previous minor versions of OCaml were somewhat broken.

**Comment by rafoo** [comment]
Thank you very much for the quick fix! Installation with `opam pin -k git add merlin https://github.com/ocaml/merlin.git` worked.
