### ISSUE TITLE
$ opam user-setup install dont works

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [ocaml/merlin#752]
I want to use merlin, utop, tuareg (ocaml things) on my emacs. But when i give opam the following code, the emacs setting doesnot work, instead come many issues. Do anyone have some idea?

```
Administrator@USER-6FNCH9N4V0 ~
$ opam user-setup install
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
```

**Comment by trefis** [comment]
I don't think any of the frequent contributors to this repository use user-setup, so we won't really be able to help you.
If you still have a problem with this I think you should open an issue of [user-setup's bugtracker](https://github.com/OCamlPro/opam-user-setup/issues).
