### ISSUE TITLE
OCaml 4.06.0 + JBuilder + Merlin debugging help

### ISSUE THREAD

**Issue by dc-mak** [ocaml/merlin#761]
Hello,

Merlin is complaining about 'Unbound modules': I'm using JBuilder 1.0+beta16, OCaml 4.06.0 and Opam 2.0 beta, Merlin 3.0.5 and ocamlfind 1.7.3 (on elementaryOS, based on Ubuntu 16.04 LTS).

JBuilder compiles the project no problems, I can load it into Utop but Merlin is acting up and I can't make sense of this log (`let g:merlin_debug=1` in my NeoVim (2.2) init.vim).
EDIT: Same problems occur with Emacs 24.5.1, tuareg 2.1.0. I noticed that I could ``open Base;;`` then ask for the type of  ``compare_int`` and I would get ``Base.compare_int: int -> int -> bool`` but it would still say `Unbound module Base` and `Unbound value compare_int`.

Merlin's log:
[merlin_log.txt](https://github.com/ocaml/merlin/files/1573564/merlin_log.txt)

And merlin project file:
[merlin.txt](https://github.com/ocaml/merlin/files/1573588/merlin.txt)

Relevant variables from `printenv` (no `OCAMLLIB` or `CAMLLIB` - is this necessary?)
```
OPAM_SWITCH_PREFIX=/home/dhruv/.opam/4.06.0
CAML_LD_LIBRARY_PATH=/home/dhruv/.opam/4.06.0/lib/stublibs:/home/dhruv/.opam/4.06.0/lib/ocaml/stublibs:/home/dhruv/.opam/4.06.0/lib/ocaml
OCAML_TOPLEVEL_PATH=/home/dhruv/.opam/4.06.0/lib/toplevel
MANPATH=:/home/dhruv/.opam/4.06.0/man
PATH=/home/dhruv/.opam/4.06.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/dhruv/.local/bin
```

It was working earlier today with 4.04 but I needed to upgrade to 4.06 for unrelated and now this has happened :(

Thanks for the help!

**Comment by dc-mak** [comment]
In case anyone else hits this - remove the ppx_* (except for *runtime-libs/expanders) from the .merlin file (and your jbuilder `libraries` list, it's only necessary for the `pps` field).

**Comment by kandu** [comment]
ah, it seems that you switched to 4.06 and installed the new version of base. the base v0.10.0 published on the official opam repo yesterday caused the problem.
Since merlin doesn't depend on base, it could be base v.0.10.0 that overwrites or shadows some components, mess up some subtle behavior of the stdlib
[v0.10.0 conflicts with merlin](https://github.com/janestreet/base/issues/35)
workaround, opam install base.v0.9.4

**Comment by leviroth** [comment]
Can you elaborate on what you mean by "remove the ppx_*"? I'm having this problem, but I'm depending on packages like `ppx_type_conv`, so I can't simply remove them from the jbuilder file.

**Comment by dc-mak** [comment]
Before, I had the following in my jbuild (or something equivalent)
```
(jbuild_version 1)

(library (
    (name lt4la)
    (synopsis "Linear Types for Linear Algebra")
    (libraries (
        owl
        core_kernel
        ppx_traverse_builtins
        ppx_jane
        ppx_traverse
        ppx_driver
    ))
    (preprocess (pps (ppx_traverse ppx_jane ppx_driver.runner)))
))
```
but now I have this:
```
(jbuild_version 1)

(library (
    (name lt4la)
    (synopsis "Linear Types for Linear Algebra")
    (libraries (
        owl
        core_kernel
        ppx_traverse_builtins
    ))
    (preprocess (pps (ppx_traverse ppx_jane ppx_driver.runner)))
))
```
Likewise, my old generate .merlin file is linked above, but the relevant changes/excerpt from the .merlin file that is now generated is
```
PKG ppx_assert.runtime-lib
PKG ppx_bench.runtime-lib
PKG ppx_compare.runtime-lib
PKG ppx_expect.collector
PKG ppx_expect.common
PKG ppx_expect.config
PKG ppx_hash.runtime-lib
PKG ppx_inline_test.config
PKG ppx_inline_test.runtime-lib
PKG ppx_traverse_builtins
```
As far as I can tell, unless you're actually using the ppx extensions as libraries (instead of as preprocessors only), you don't need to list them as libraries in jbuild - it will automagically use it in the correct way.

**Comment by leviroth** [comment]
I've found a minimal example for this, no jbuild necessary:

.merlin file:

```
PKG ppx_core
PKG ppx_type_conv
```

OCaml source file:

```ocaml
open Ppx_core
```

This generates an error: "Unbound module Ppx_core". However, the error goes away if the line `PKG ppx_type_conv` is removed. So it looks like ppx_type_conv is somehow hiding that module when it's loaded by merlin.

**Comment by dc-mak** [comment]
Yeah that's the same as what I had, I found the same thing happened with other ppx packages as well (ones that didn't (runtime-lib,expander,config,collector). Since I didn't need ppx_type_conv (or any other one) directly, I was able to delete. Shall I reopen this issue if this is something you need?

**Comment by leviroth** [comment]
That would be great, thanks!

**Comment by leviroth** [comment]
I am adding the merlin debug logs from the broken and working configurations. Of note is that, with `PKG ppx_type_conv`, merlin looks for `ppx_core.cmi` in `~/.opam/4.06.0/lib/ocaml`, which is obviously not where it's found.

[Broken version](https://github.com/ocaml/merlin/files/1591464/log_broken.txt)
[Working version](https://github.com/ocaml/merlin/files/1591465/log_working.txt)

**Comment by leviroth** [comment]
I'm no longer having this issue. There's been no new version of merlin, but Jane Street's libraries all went from 0.9.0 to 0.10.0 recently. I wonder if the problem was on their end.

**Comment by kandu** [comment]
@leviroth you mean the new version of ppx_driver comes with 0.10.0 causes the issue in some case?

**Comment by leviroth** [comment]
No, I mean that the issue went away with the new version of ppx_driver.

**Comment by trefis** [comment]
Since the issue seems to have disappeared...
