### ISSUE TITLE
Merlin build fails on ocaml msvs 64 (windows)

### ISSUE THREAD

**Issue by bikallem** [ocaml/merlin#762]
I am trying to build/install merlin on windows 10 64. I am successfully running ocaml - msvs(64) 4.06. However when I try to build merlin inside the cygwin shell with 'c compiler' pointing to msvs 64 I get the error below.

```
ocamlfind: Package `threads.posix' not found - required by `threads'
make[2]: *** [OCamlMakefile:1079: src/config/my_config.cmx] Error 2
```
Am I missing some packages needed to build merlin successfully on Windows? Or is it that merlin can't be built as native windows executable?
My 'ocamlfind list` is as follows.
```
bigarray            (version: [distributed with Ocaml])
biniou              (version: 1.2.0)
bytes               (version: [distributed with OCaml 4.02 or above])
compiler-libs       (version: [distributed with Ocaml])
compiler-libs.bytecomp (version: [distributed with Ocaml])
compiler-libs.common (version: [distributed with Ocaml])
compiler-libs.optcomp (version: [distributed with Ocaml])
compiler-libs.toplevel (version: [distributed with Ocaml])
cppo                (version: n/a)
dynlink             (version: [distributed with Ocaml])
easy-format         (version: n/a)
findlib             (version: 1.7.3)
findlib.dynload     (version: 1.7.3)
findlib.internal    (version: 1.7.3)
findlib.top         (version: 1.7.3)
graphics            (version: [distributed with Ocaml])
ocamlbuild          (version: NEXT_RELEASE)
ocamldoc            (version: [distributed with Ocaml])
result              (version: 1.2)
stdlib              (version: [distributed with Ocaml])
str                 (version: [distributed with Ocaml])
threads             (version: [distributed with Ocaml])
unix                (version: [distributed with Ocaml])
yojson              (version: 1.4.0)
yojson.biniou       (version: n/a)
````

**Comment by bikallem** [comment]
cc @dra27 . From your blog post I got the impression that `merlin` was supported and working as native msvs executable on windows. Is this not the case? Or am I perhaps missing some libs?

**Comment by dra27** [comment]
Do you have a Cygwin OCaml also installed? What's the output of Merlin's configuration script?

**Comment by dra27** [comment]
Actually, there's definitely something not quite with your findlib installation - `threads.posix` should certainly be in that list.

**Comment by bikallem** [comment]
> Do you have a Cygwin OCaml also installed? What's the output of Merlin's configuration script?

I have msvs 64 ocaml (built using msvc 2015 tools) - not the cygwin/mingw variants. Will this explain why I don't have posix installed in my ocaml installation?

**Comment by bikallem** [comment]
closing this.
