### ISSUE TITLE
ctypes becomes unavailable when ctypes-foreign is installed

### ISSUE THREAD

**Issue by xguerin** [ocaml/merlin#778]
Hey there,

1. When `ctypes` only is installed, `merlin` finds `Ctypes` modules no problem.
2. As soon as `ctypes-foreign` is installed, `merlin` can't find the `Ctypes` modules anymore.

I use `jbuilder` but tried authoring the `.merlin` file manually with the following, which works in case 1/ and fails in case 2/:

```
PKG ctypes
```

Any idea if I am doing anything wrong ?

**edit** I forgot to mention that all compile fine.

**Comment by trefis** [comment]
I have the packages `ctypes` and `ctypes-foreign` installed, a `.merlin` with only `PKG ctypes` and I can't ask for the type of the `Ctypes` module, I can complete after `Ctypes.`, I can jump (i.e. "merlin-locate"/":MerlinLocate") to `ctypes.mli` and merlin reports no error when I use the module.

Can you give more information regarding what you're trying to do (i.e. what are you asking merlin) that doesn't work?
