### ISSUE TITLE
Locate does not default to .mli file if .ml file is not present

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/merlin#787]
When locating a value from a library the does not have their .ml files installed, merlin does not default to its .mli counterpart.

See https://github.com/c-cube/ocaml-containers/issues/199

**Comment by trefis** [comment]
I don't think that's a bug in merlin: why do you have the `.cmt` if there is no `.ml`?
When merlin doesn't find a `.cmt` it will fallback to the `.cmti` without issue, but if the `.cmt` is there...

We could probably update merlin to support this situation, but really, people should fix their installation / installer (which has apparently been the case for jbuilder).

I'm tempted to close this issue @kit-ty-kate, do you object?

**Comment by kit-ty-kate** [comment]
I do not object if this requires to change a lot a code but if not I think it would be good to have this for users that don't use `jbuilder`. That could avoid some frustrations for some users.

**Comment by trefis** [comment]
Coming back to this issue after all the changes I've done to locate recently I can now confirm I'm definitely not planning to change merlin to accommodate this situation.

Thanks for the report anyway!
