### ISSUE TITLE
Merlin does not distinguishes bytes from string (ocaml v4.06.1)

### ISSUE THREAD

**Issue by sapristi** [ocaml/merlin#795]
Hello, 
using ocaml v4.06.1, it seems that merlin does not make a distinction between bytes and string, while the compiler does.

   let (a : bytes) = "abc";;
does not raise any error in merlin, while the compiler generates the appropriate error `Error: This expression has type string but an expression was expected of type bytes`

**Comment by trefis** [comment]
This is now fixed.
Until the fixes is released on opam you can always add the line `FLG -safe-string` in your `.merlin`.
