### ISSUE TITLE
Automatic display of the type and other occurences of identifier under the point 

### ISSUE THREAD

**Issue by Khady** [ocaml/merlin#796]
I have been trying to add to merlin a mode to automatically display the type of the value under the point after a small delay without moving. Inspired by what is done in emacs-lisp or typescript modes. And I have a few questions about how to do that well:

- Is it better to have the code in a different repo or should I try to make a PR to add it to merlin?
- I ended up copying some code from merlin to do some modifications for my task as most of the functions are doing multiple things or using side effects. Does it sound ok or I should be able to reach my objective just by calling some existing merlin functions? See https://github.com/Khady/merlin-auto-hl/blob/master/merlin-auto-hl.el#L15-L27

**Comment by Fourchaux** [comment]
Another proposition made 2 years ago!
See Issue https://github.com/ocaml/merlin/issues/500

With the script (from infinity0):
https://github.com/infinity0/l33tutils/blob/master/devel/emacs/site-lisp/merlin-extra.el

**Comment by Khady** [comment]
Right. Let's keep the #500 as the reference then. Thanks
