### ISSUE TITLE
A case when Merlin "locate" does not work properly.

### ISSUE THREAD

**Issue by matejkosik** [ocaml/merlin#798]
I've noticed that in a code like this:
```Ocaml
module List =
  struct
    include List
    let foo l =
      match l with
      | hd :: tl ->
         let _ = hd in
         assert false
      | [] ->
         assert false
  end
```
when I
- position the cursor at the last occurrence of the `tl` identifier (the one under the `hd :: tl` branch)
- and then when I ask Merlin to jump to the definition of this identifier

then Merlin Jumps to `List.tl` instead of the variable bound by the `hd :: tl` pattern.

**Comment by trefis** [comment]
I assume you meant `hd` not `tl`.
This is indeed a bug.

**Comment by matejkosik** [comment]
Yes, I meant `hd`, sorry for the confusion.

**Comment by trefis** [comment]
This is actually the same underlying issue as #806 .
