### ISSUE TITLE
Strange behaviour with bs-platform

### ISSUE THREAD

**Issue by argent-smith** [ocaml/merlin#800]
Hi. I’m quite new to everything related to bucklescript toolchain. Also, I’m not sure if this is the right place to post the issue but since I encounter it in Emacs merlin mode…

When I save an *.ml file in a tutorial bucklescript project (described here: https://bucklescript.github.io) I see «1 pending errors»  message. Then, C-c C-x gives me this:

```
/usr/local/lib/node_modules/bs-platform/lib/ocaml/js.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
```

Perhaps I am doing something wrong. I’d appreciate any hint how to help this ;)

**Comment by let-def** [comment]
The version of OCaml used by Merlin and bucklescript should match. I think bucklescript still uses OCaml 4.02, you probably need your whole setup to work with 4.02. Does that help?

**Comment by argent-smith** [comment]
@let-def thanks for your concern. I’ve found that few minutes later ;) Had to go to bs repo and check there. Tonight I’ll repeat the experiment according to this jewel of knowledge :)

**Comment by argent-smith** [comment]
@let-def **UPD** rolled 4.02.3 switch; everything is ok now. Thanks! Closing the issue.
