### ISSUE TITLE
Recursive definitions of values: Merlin complains but file compiles

### ISSUE THREAD

**Issue by disteph** [ocaml/merlin#803]
The following code, I think, complies with the [rules for the definition of recursive values](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#s%3aletrecvalues), and indeed it compiles fine.
But Merlin reports the error "This kind of expression is not allowed as right-hand side of `let rec`".
Not sure who is at fault there...
```
type t = { field : int Lazy.t }
let aux (h : t -> int) =
  let rec g = { field = lazy (h g)}
  in g
```

**Comment by Fourchaux** [comment]
(For Info) 
No error here.

merlin-master, emacs, linux x86_64, OCaml 4.06.1+flambda

**Comment by disteph** [comment]
Interesting. I've just done a fresh install of the opam switch OCaml 4.06.1+flambda, with merlin and tuareg.
Same error as before for me (also emacs, linux x86_64)... wonder where that comes from then. My directory with the file containing the above code is otherwise empty (no .merlin, no leftover compilation files, no _build, etc).

**Comment by Fourchaux** [comment]
Other tests: 
with OCaml 4.06.1 & Spacemacs (& an 'empty' directory)  : no problem. 

Your computer is making jokes on April 1st? Odd...

**Comment by trefis** [comment]
I can also reproduce this (from master) and I've seen that issue a bunch of time.
I'll look into it.

**Comment by trefis** [comment]
Turns out our version of 4.06 wasn't quite synced up with 4.06.1.
Things should be better now.

**Comment by disteph** [comment]
Great, thanks! That fixed it!
