### ISSUE TITLE
merlin-try-completion  deprecated in 2015 and still in the 'emacs from scratch' ...

### ISSUE THREAD

**Issue by houndofsound** [ocaml/merlin#813]
title says it all!

**Comment by nekketsuuu** [comment]
Indeed, #465 says `merlin-try-completion` has been removed. So I edited the wiki page. You can also edit it if you want to write more :)

https://github.com/ocaml/merlin/wiki/emacs-from-scratch#auto-complete

**Comment by trefis** [comment]
Thank you @nekketsuuu!
