### ISSUE TITLE
merlin compilation fails

### ISSUE THREAD

**Issue by mprevot** [ocaml/merlin#821]
I'm on Ubuntu 8 with gcc 8.

 How can I resolve this ?

> [yojson.1.4.1] found in cache
> 
> <><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
> ∗ installed conf-m4.1
> ∗ installed conf-which.1
> ∗ installed jbuilder.1.0+beta20
> ∗ installed easy-format.1.3.1
> ∗ installed biniou.1.2.0
> ∗ installed ocamlfind.1.8.0
> ∗ installed base-bytes.base
> ∗ installed cppo.1.6.4
> ∗ installed yojson.1.4.1
> [ERROR] The compilation of merlin failed at "/home/mprevot/.opam/opam-init/hooks/sandbox.sh build make -j 1".
> 
> === ERROR while compiling merlin.3.0.5 =======================================#
>  context     2.0.0~rc2 | linux/x86_64 | ocaml-variants.4.06.1+multicore | https://opam.ocaml.org/2.0#b36f28db
>  path        ~/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5
>  command     ~/.opam/opam-init/hooks/sandbox.sh build make -j 1
>  exit-code   2
>  env-file    ~/.opam/log/merlin-81501-1a5911.env
>  output-file ~/.opam/log/merlin-81501-1a5911.out
> ## output ###
>  [...]
>  /home/mprevot/.opam/4.06.1+multicore/lib/ocaml/caml/domain_state.h:17:10: fatal error: domain_state.tbl: No such file or directory
>   #include "domain_state.tbl"
>            ^~~~~~~~~~~~~~~~~~
>  compilation terminated.
>  OCamlMakefile:1135: recipe for target 'src/platform/platform_misc.o' failed
>  make[2]: *** [src/platform/platform_misc.o] Error 2
>  make[2]: Leaving directory '/home/mprevot/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5'
>  OCamlMakefile:780: recipe for target 'native-code' failed
>  make[1]: *** [native-code] Error 2
>  make[1]: Leaving directory '/home/mprevot/.opam/4.06.1+multicore/.opam-switch/build/merlin.3.0.5'
>  Makefile:56: recipe for target 'ocamlmerlin-server' failed
>  make: *** [ocamlmerlin-server] Error 2

**Comment by trefis** [comment]
I don't think this has anything to do with merlin:
```
/home/mprevot/.opam/4.06.1+multicore/lib/ocaml/caml/domain_state.h:17:10: fatal error: domain_state.tbl: No such file or directory
#include "domain_state.tbl"
^~~~~~~~~~~~~~~~~~
```
indicates that you're using an unreleased version of ocaml, and the compilation error is most likely due to that.

**Comment by trefis** [comment]
But you're not using 4.06.1, you're using 4.06.1+multicore.

**Comment by mprevot** [comment]
This is a multicore enhancement from Cambridge's ocamllabs, based on the release. A support would be welcome at some point.

[https://github.com/ocamllabs/ocaml-multicore](https://github.com/ocamllabs/ocaml-multicore)
[https://github.com/ocamllabs](https://github.com/ocamllabs)
[http://ocamllabs.io/](http://ocamllabs.io/)

I'm willing to solve the problem for the community once and for all: can I have some guidance please ?

**Comment by let-def** [comment]
I think the issue is due to ocaml-multicore not distributing the right files. The issue should be reported on their repository (the last lines of output should be enough, the point is that their distribution install an header that depends on domain.tbl but this file is missing)
