### ISSUE TITLE
merlin error

### ISSUE THREAD

**Issue by mprevot** [ocaml/merlin#823]
merlin:

> This expression has type string/15
>        but an expression was expected of type string/17
> string/17 is abstract because no corresponding cmi file was found in path.

I'm using this command `ocamlopt -g pa.ml -o pa` and this code:

```
let log = Printf.printf

let rec f id depth =
  log "Starting number %i\n%!" id; # <- HERE
  if depth > 0 then begin
    log "Forking number %i\n%!" (id * 2 + 1);
    Sched.fork (fun () -> f (id * 2 + 1) (depth - 1));
    log "Forking number %i\n%!" (id * 2 + 2);
    Sched.fork (fun () -> f (id * 2 + 2) (depth - 1))
  end else begin
    log "Yielding in number %i\n%!" id;
    Sched.yield ();
    log "Resumed number %i\n%!" id;
  end;
  log "Finishing number %i\n%!" id

let () = Sched.run (fun () -> f 0 2)
```

but this happens also with all `printf "some text"`.

**Comment by trefis** [comment]
1. There is not enough information here to reproduce the problem (for example, where does `Sched` come from?). Debugging would be easier if you reduced the test case further, or included it in full.
2. I believe you're trying merlin on a fork of ocaml which we don't explicitly support; is there a way to reproduce the issue with a regular ocaml installation? At this point, it's unlikely that we're going to spend time adding support for multicore.

**Comment by mprevot** [comment]
[https://github.com/ocamllabs/ocaml-multicore](https://github.com/ocamllabs/ocaml-multicore)
[http://kcsrk.info/ocaml/multicore/2015/05/20/effects-multicore/](http://kcsrk.info/ocaml/multicore/2015/05/20/effects-multicore/)

That's not really a fork, more a ahead future trunk main branch: [http://ocamllabs.io/](http://ocamllabs.io/)

Anyway, if that doesn't interest you, I'll consider doing it since it doesn't look a big job. In that case, would you recommend a place to start ?

Thanks

**Comment by trefis** [comment]
Sure :)

Basically what is needed is to import a copy of the frontend of the multicore compiler, and then adapt in to merlin.

I did this recently for the 4.07 version of the ocaml compiler, in the following commit chain:
- "*Add orig/ocaml_407*": 36b076f2be40b93381126f1e973d724a5766abb6
- "*add src/ocaml/typer_407*": f4f315d2a00b4a5aa61a1d582a28ba080d86516e
- "*WIP: sync parser_raw*": ae4e56be1ee050e6b6a35c591817a42b9889ecac
- "*WIP reimport merlin patches*": bf148c4c48f042742cabc3682d2fc3f85389a783
- "*refresh 407 parser*": 1a82d273ede167413344db13bc74d759e3426ca8

Good luck!

**Comment by mattpallissard** [comment]
Hey, sorry to bump an old issue, but I have a fork of merlin working off of the 4.10 ocaml-multicore repo.  Would you all be open to having a separate branch that tracks multicore?

```
(* test.ml *)
Printf.printf "foo"
```
before
```
~  ocamlmerlin single errors -filename test.ml < test.ml | jq '.["value"]'
[
  {
    "start": {
      "line": 2,
      "col": 14
    },
    "end": {
      "line": 2,
      "col": 19
    },
    "type": "typer",
    "sub": [],
    "valid": true,
    "message": "This expression has type string/1 but an expression was expected of type\n  string/2\nstring is abstract because no corresponding cmi file was found in path."
  }
]
```

after
```
~  ocamlmerlin single errors -filename test.ml < test.ml | jq '.["value"]'
[]
```

**Comment by trefis** [comment]
@mattpallissard could you open a dedicated issue so we can discuss it?
When doing so, it would be helpful if you could summarize where multicore and base ocaml differ in terms of type-checking, as well as any other difference that would affect merlin. (A link to your fork could also be useful)

Thanks!

**Comment by mattpallissard** [comment]
Sure, https://github.com/ocaml/merlin/issues/1197.
