### ISSUE TITLE
Incorrect highlighting of quoted strings inside comments

### ISSUE THREAD

**Issue by cfcs** [ocaml/merlin#824]
may be related to: https://github.com/ocaml/merlin/issues/314

I just got bitten by an issue where merlin didn't properly highlight a quoted string inside a comment.
My crappy keyboard skills had caused me to miss two quotes, so by coincidence the string ended up being well-formed, but the result was pretty surprising - instead of `9` I got `5` from the code below because the last `+1 + workers` is in fact inside a comment (which I would expect to be highlighted like the other comments):

![](https://i.imgur.com/lnw4dFV.png)

I've got
```
$ opam info merlin
             package: merlin
             version: 3.0.5
   installed-version: 3.0.5 [4.04.2+fPIC]
$ emacs --version
GNU Emacs 25.2.2
```

I'm not sure if this is a bug in merlin, or if I have configured something wrong on my end, but help would be greatly appreciated!

**Comment by trefis** [comment]
Merlin doesn't do syntax highlighting, I think you want to have a look at https://github.com/ocaml/tuareg

**Comment by cfcs** [comment]
@trefis Ah, my apologies! I found the issue already documented in tuareg.
