### ISSUE TITLE
Cannot find merlin binary at "ocamlmerlin".

### ISSUE THREAD

**Issue by TrakBit** [ocaml/merlin#831]
I have already install merlin but ocamlmerlin binary still doesn't seems to exist
checked path `/Users/user_name/.opam/system/bin/ocamlmerlin` but there was no binary available.

**Environment**
OCaml - 4.06.1
Opam - 1.2.2
Merlin - 3.0.5
MacOS

**Comment by trefis** [comment]
What about in `~/.opam/($opam config var switch)/bin`?

**Comment by TrakBit** [comment]
@trefis Thanks for that

**Comment by TrakBit** [comment]
@trefis  Any idea how I can set this path for vscode

{
    "ocaml.merlinPath": "/Users/nick/.opam/system/bin/ocamlmerlin",
    "reason.path.ocamlmerlin": "/Users/nick/.opam/system/bin/ocamlmerlin"
}

as suggested in this issue #739

**Comment by trefis** [comment]
I suggest you read up about [opam switches](https://opam.ocaml.org/doc/Usage.html#opam-switch)
The answer should be obvious once you know about switches (what they are for, and how they work).

Good luck!
