### ISSUE TITLE
Where is the documentation on how to use Merlin on a `trunk` clone of the compiler distribution?

### ISSUE THREAD

**Issue by gasche** [ocaml/merlin#846]
This could be here on in ocaml/CONTRIBUTING.md, but we need some documentation.

Say, I'm a new (non-expert) contributor to the OCaml codebase and I would like to use `Merlin`, but my usual setup fails:

```
/home/gasche/Prog/ocaml/github-trunk/typing/typedtree.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml.
```

What should I do then?

**Comment by trefis** [comment]
Note: the last part of my answer was perhaps a bit too cheeky, I do agree that the situation is frustrating. But I don't really have much to propose. Trunk moves frequently, and it's a ton of work to keep up to date with it. We basically do the work of adding a new backend or when a release is imminent or when segfaults get too frequent when loading `.cmi`s, apart from these situation it's just too much effort.

Incidentally, it's for that reason that I didn't already make of push for removing `Stypes` from the compiler: the only reasonable reason I can see for its existence nowadays is to be there for people working on a compiler when merlin just cannot be used.
I wish things were different.

**Comment by gasche** [comment]
I wasn't trying to say that `trunk` and Merlin should work all the time together, but rather that how to try to use it, and the fact that it sometimes breaks, should be documented in a place that ocaml distribution contributors can find. Could you copy-paste selected bits of your reply to this issue and propose it as a PR against [HACKING.adoc](https://github.com/ocaml/ocaml/blob/d3e7359/HACKING.adoc)?

**Comment by trefis** [comment]
Yeah, I’ll write something up later today.

**Comment by gasche** [comment]
(Including bits about how to contribute an updated branch to the Merlin upstream does sound like a good idea to me, but maybe that part should be located Merlin-documentation-side and just referenced from HACKING.)

**Comment by gasche** [comment]
The error report in my first message comes, of course, from using an Emacs ran from a 4.06.1 switch and trying to use it on current (4.08.0+dev) trunk, so your diagnostic "use the latest OCaml release" is spot on. Note that in the wild, I've observed some people interested in contributing to the OCaml compiler codebase who had say a "latest Ubunutu-stable" version of OCaml available system-wide, so I think this can be a common situation.

**Comment by avsm** [comment]
I could also use a best-effort 4.08 snapshot port...

I'm starting to activate CI in my experimental [ocaml platform tools monorepo](https://github.com/avsm), so having a best-effort 4.08 Merlin would let me find a snapshot where all the tools build against trunk OCaml.  Once that works, then bisection to find which changesets break which libraries (e.g. AST or typer changes breaking Merlin's build) will be easier.

**Comment by bluddy** [comment]
I'm currently getting a ton of error messages ending with 'abnormal termination' in neovim, trying to edit ocaml trunk. Is there a quick way to disable merlin temporarily?

**Comment by rgrinberg** [comment]
> What should I do then?

Would it make sense to recommend such users to use the dune build then? It makes merlin quite usable.

**Comment by gasche** [comment]
Thanks for bringing this issue back to life. I believe that @trefis resolved the issue by explaining in the compiler HACKING.adoc how to use `dune build @libs` to get a decent Merlin experience most of the time (depending on whether the compiler codebase is still buildable from the last release): [HACKING.adoc: Using merlin](https://github.com/ocaml/ocaml/blob/bdfdf96/HACKING.adoc#using-merlin).
