### ISSUE TITLE
Emacs: merlin-locate always opens results in a new buffer when using tramp

### ISSUE THREAD

**Issue by Wilfred** [ocaml/merlin#854]
The problem seems to be that `merlin/locate` on tramp files returns data of the form:

```
((assoc) (file . "foobar.ml") (pos (assoc) (line . 398) (col . 4)))
```

which returns `nil` from `merlin--differs-from-current-file` because that compares with the full path. The full path takes the form `"/sshx:example.com/home/wilfred/project/foobar.ml"`.

**Comment by rgrinberg** [comment]
Unless you'll send a PR, it's a WONTFIX - sorry. It's quite likely that this issue doesn't exist with the lsp and eglot frontends.
