### ISSUE TITLE
Huge RAM used by ocamlmerlin-server. Is this my fault?

### ISSUE THREAD

**Issue by ulugbekna** [ocaml/merlin#878]
At some point ocamlmerlin-server started using nearly 40 GB or RAM, running in VS Code on MacOS Mojave. Did I do something wrong?

![image](https://user-images.githubusercontent.com/16353531/47962110-652ce980-e039-11e8-8abb-ec6e8555bfd3.png)

**Comment by trefis** [comment]
:man_shrugging: 

Merlin usually uses a lot of memory when it has to load a lot of cmis / cmts. Which can happen on big projects / projects with a lot of dependencies.
40G seems excessive, but it's hard to say for sure without knowing more about your setup.

Do you still notice merlin consuming so much memory? If yes, useful information would be: version of merlin, version of ocaml, whether you're using locate/jump-to-definition at all, and what your project looks like (in terms of size, dependencies, etc).
