### ISSUE TITLE
Duplicate syntax checker exception when used with syntastic

### ISSUE THREAD

**Issue by tachukao** [ocaml/merlin#881]
Hi there, 

I get the following error when I check the syntax of an ocaml file (used with syntastic)

```
Error detected while processing function 80[16]..88:
line    8:
E605: Exception not caught: Syntastic: Duplicate syntax checker name: ocaml/merlin
Error detected while processing function <SNR>22_BufWritePostHook[4]..<SNR>22_UpdateErrors[15]..<SNR>22_CacheErrors[20]..81:
line   30:
E170: Missing :endfor
Error detected while processing function <SNR>22_BufWritePostHook[4]..<SNR>22_UpdateErrors[15]..<SNR>22_CacheErrors:
line   20:
E171: Missing :endif
Error detected while processing function <SNR>22_BufWritePostHook[4]..<SNR>22_UpdateErrors:
line   15:
E171: Missing :endif
```

this error disappears when I remove merlin as an opam package in my `.vimrc` file

any ideas why this might be happening or how to fix this? thank you!

**Comment by Dead-User** [comment]
I have encountered the same error. I have tried removing all lines relating syntastic and OCaml in my init.vim file and the same error will occur. I guess the problem may come from vim/merlin/syntax_checkers/ocaml/merlin.vim, which registers checkers for syntastic.

**Comment by let-def** [comment]
It is normal (or at least used to be normal) to register Merlin in Syntastic.
You should rather find out why it is registered from two different places.

Look at (and maybe share) the output of `:scriptnames` to find all merlin and ocaml auto loaded stuff.
