### ISSUE TITLE
Feature request: Go to the type inferred at point

### ISSUE THREAD

**Issue by Wilfred** [ocaml/merlin#885]
```ocaml
type 'a tree =
  Empty : 'a tree
| Tree : 'a tree * 'a * 'a tree -> 'a tree;;

let rec count_leaves t =
  match t with
    Empty -> 1
  | Tree (left, _, right) -> count_leaves left + count_leaves right
```

With point on `t`, I can use `M-x merlin-type-enclosing` to see that `t` has type `'a tree`. However, I'd love a way to jump to the the definition of `tree` from here. I can't see any way of doing so.

Is this possible? I've had a look at the wiki and read through `merlin.el` but I don't see any obvious way of doing this.

**Comment by Khady** [comment]
I would like this too. For now my workaround is to move to `Empty` or `Tree` and do a locate there.

**Comment by trefis** [comment]
You're not the first ones to ask for that feature, and I agree it makes sense.
The protocol is not quite precise enough to express such a request right now but with some very minor modifications it should be easy to support it.

I hope to implement it sometime in the next few weeks. But if someone wants to take a crack at it before then, speak up and I'll be happy to lay out what I think the changes should be.

**Comment by andreypopp** [comment]
This is implemented in LSP frontend now.

**Comment by Wilfred** [comment]
@andreypopp thanks, I presume you're referring to #905?

**Comment by trefis** [comment]
@andreypopp: I think my previous remark still stands, that is:
> The protocol is not quite precise enough to express such a request right now but with some very minor modifications it should be easy to support it.

For example, if the input is:
```ocaml
type tree = Leaf of int | Node of tree * tree

let tree = Node (Leaf 0, Leaf 1)

let leaf = Leaf 42
```
and I make the rpc call `* textDocument/typeDefinition`, I suspect that you will return the location of the *value* named `tree`, not of the *type* of the same name.

**Comment by andreypopp** [comment]
@trefis you are correct, this case needs to be handled.

Still I found even the current implementation work ok-ish in most cases.

**Comment by rgrinberg** [comment]
@andreypopp can this be closed?

**Comment by andreypopp** [comment]
If we are not going to provide this in merlin non-LSP frontend then yeah, we can close it.

**Comment by rgrinberg** [comment]
I actually just wanted to know if you fixed the handling the case Thomas pointed out. I think there's no point exposing this feature in the editor specific frontends.

**Comment by andreypopp** [comment]
Yes, this is handled properly now.
