### ISSUE TITLE
21st century stuff

### ISSUE THREAD

**Issue by ORESoftware** [ocaml/merlin#892]
if OCaml wants to pick up steam outside of the neckbeard world, would it not be prudent to allow for plugins outside of vim/emacs. Can Merlin work with Intellij or VSCode?

**Comment by Khady** [comment]
21st century stuff, such as google? Actually it is even in the readme.

https://github.com/reasonml-editor/vscode-reasonml

**Comment by andreypopp** [comment]
There's ongoing work to support LSP protocol by merlin. Plugin for VSCode should be available soon.

**Comment by rgrinberg** [comment]
The 21st century is here and we indeed have an [lsp server](https://github.com/ocaml/ocaml-lsp/)
