### ISSUE TITLE
LSP: the server doesn't pick up new lib dependencies added after a session has been initialized

### ISSUE THREAD

**Issue by Khady** [ocaml/merlin#930]
It looks like merlin-lsp doesn't pick up new libraries when they are added to a project after the lsp server is started.

- I open a file, compile the project, everything is fine
- add something like `let f = Fmt.pf`, it tells me that Fmt doesn't exist (fine)
- add fmt to the dune file, compile, dune is happy
- make a change in the file to trigger merlin-lsp
- merlin-lsp still tells me that Fmt doesn't exist. If I restart the session, Fmt is now detected.

**Comment by trefis** [comment]
Not sure this is related to lsp, there were problem of that sort in merlin that we've since fixed.
I think this can be safely closed, if I was mistaken then I suggest you open an issue on https://github.com/ocaml/ocaml-lsp/
