### ISSUE TITLE
confusing error message: "The value ... is not an instance variable"

### ISSUE THREAD

**Issue by gasche** [ocaml/merlin#940]
``` ocaml
let test foo =
  match foo with
  | None -> exit 1
  | Some pkg -> pkg (*< ERROR *)
end (* < ERROR *)
```

The error is due to `pkg end` (`end` should be `in`); Merlin says:

```
The value pkg is not an instance variable
```

**Comment by trefis** [comment]
Here is the AST that merlin is working on in that case:
```ocaml
let test foo =
  match foo with
  | None -> ((exit 1)[@merlin.loc ])
  | Some pkg -> ((pkg <- [%merlin.hole ])[@merlin.loc ])
```

Obtained with: `ocamlmerlin single dump -what parsetree < gasche.ml | jq .value | sed 's/"\([^"]*\)"/\1/' | sed 's/\\n/\n/g'`.

I don't know why it chose to introduce that `<-`, I'll let @let-def comment.

**Comment by let-def** [comment]
:) unfortunate choice of the recovery algorithm. I will tell it to avoid `<-`.
