### ISSUE TITLE
merlin-locate does not work on +.

### ISSUE THREAD

**Issue by Chris00** [ocaml/merlin#949]
`merlin-locate` does not work when the point in on a dotted infix operator such as `+.` (in Emacs).

Example:
```ocaml
module A = struct
  let ( +. ) a b = a +. b
end

let f x = A.(x +. 1.)
``` 
(put the cursor on the latest `+.` and `M-x merlin-locate`).

**Comment by trefis** [comment]
The answer I get when I try it is `Not in environment ''`.

Note for whoever tries to fix this: looks like a bug in `reconstruct_identifier`.

**Comment by rgrinberg** [comment]
I had a brief look, and I think it might be a bug in `Longident.parse` instead. `Longident.parse "+."` does not seem to work as expected.

cc @gasche

**Comment by gasche** [comment]
(I gave some context in https://github.com/ocaml-ppx/ppxlib/pull/111#issuecomment-568283753.)

For the needs of Merlin, the choice of exposing the more robust functions from the parser seems reasonable. Should we experiment with a PR to do this in trunk?

**Comment by Octachron** [comment]
Should I add a generic `Longident.t` parser to ocaml/ocaml#9021?
