### ISSUE TITLE
[WISH] per file ppx flags

### ISSUE THREAD

**Issue by gares** [ocaml/merlin#951]
It would be nice to be able to specify different ppx related flags on a per file basis.
In particular this would help implementing the `per_module` dune directive in a non hackish way.
As of today, dune is able to handle per module ppx directive, but is unable to generate a merlin file that actually works.

See also: https://github.com/ocaml/dune/issues/1212

**Comment by trefis** [comment]
All that needed to happen on the merlin side has happened and been released on opam (thanks to @voodoos), the ball is now in dune's court.

**Comment by gares** [comment]
Thanks!!!
