### ISSUE TITLE
Merlin unusably slow on OSX

### ISSUE THREAD

**Issue by pbiggar** [ocaml/merlin#955]
When I open an ocaml file in vim on my OSX machine, it takes about 4s, with a minimal vim installation. On a docker container, its instantaneous (I've confirmed merlin loads in both cases). Many other operations are extremely slow, this is just one I've managed to reproduce easily.

I've attached a profile.log: [profile.log](https://github.com/ocaml/merlin/files/3150814/profile.log). The interesting line seems to be this:

```
FUNCTION  merlin#LoadProject()
    Defined: ~/.opam/4.06.1/share/merlin/vim/autoload/merlin.vim line 652
Called 1 time
Total time:   3.518525
 Self time:   3.518424

count  total (s)   self (s)
    1              0.000070   if isdirectory(expand('%:p:h'))
    1   3.518436   3.518335     MerlinPy merlin.setup_merlin()
    1              0.000011     if exists("b:dotmerlin") && exists("g:merlin_move_to_project") && g:merlin_move_to_project && len(b:dotmerlin) > 0
                                  execute ":lchdir " . fnamemodify(b:dotmerlin[0], ":p:h")
    1              0.000001     endif
    1              0.000001   endif
```

It doesn't seem like the profiling goes into python file - what's the next step I can do to debug this?

**Comment by vsiles** [comment]
How do you create this profile.log ? And is this on a big file ?
I don't have anything huge right now to test but on my macos, vim + merlin opens any .ml file I have in ~600 ms

**Comment by pbiggar** [comment]
I profiled using the instructions on https://stackoverflow.com/a/12216578/104021.

The file wasn't huge: 1529 lines, 52kb. 

Some more tests:
- opening nvim instead - same time
- opening an 89 line file: 2s
- opening the same original file outside of my project (so no .merlin files) - instant

**Comment by vsiles** [comment]
Also I forgot to ask: does your file have errors ? If it has, how many ?

**Comment by vsiles** [comment]
I tried to open a 7k files with some errors to stress vim but I don't manage to reproduce your issue, everything is under 500 ms

**Comment by pbiggar** [comment]
Good questions:

- number of errors: 458 (not finding modules, the file compiles perfectly)
- note that I run `ocamlmerlin single errors < myfile.ml` in 0.05s
- 191 files (162 ml, 29 mli), 44kLOC, 1.32MB source
- 11 merlin files, 1463LOC, 88k total

Note that there are no compiled files in the project - we run compilation within a docker container (the .merlin files are generated by the dune build)

**Comment by vsiles** [comment]
We'll have to wait for some more knowledgeable then me I'm afraid.
Do you have any vim plugin that might interfere ? What's your python version ?

**Comment by pbiggar** [comment]
I deleted my .vim and .viminfo files to try and debug this. My entire .vimrc is:

```
filetype plugin on
syntax on
let g:opamshare = substitute(system('opam config var share'),'\n$','','''')
execute "set rtp+=" . g:opamshare . "/merlin/vim"
```

Versions 
```
 $ python --version
Python 2.7.15
 $ python3 --version
Python 3.7.3
 $ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 23 2019 20:00:52)
macOS version
Included patches: 1-1200
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
[...] -python +python3 [...]
```

**Comment by pbiggar** [comment]
I got this to work by going through my docker container.

**Comment by let-def** [comment]
In your case the actual problem seemed to be that the environment merlin was run from was incorrect.
Also I get that most of the time was spent in Vim, which deals very badly with large errors list. Maybe we should trim error lists (in vim client?)
