### ISSUE TITLE
LSP : codelenses types are not using -short-path

### ISSUE THREAD

**Issue by jorisgio** [ocaml/merlin#971]
It seems that while merlin uses (a similar feature as ?) -short-path to display type of expressions uppon requests, types of top-level bindings displayed as codelenses are displayed with long path, which make them quite noisy. 
This happens with neovim + coc.nvim, but i assume it is indifferent of the editor. Any reason not to use short-path there too ?

**Comment by jorisgio** [comment]
I had a quick look at this and my understanding is that it is not easy to tweak. As far as i understand, the reason of different behavior is that codelenses use outline that types every symbol in the context of the module, while type on hover uses the local type env.
So Outline types are shown in an env that has no opens/local opens. I can try to work on this but finding a good solution to solve it is way beyond my current understanding of how things work.

**Comment by Bannerets** [comment]
@trefis 

> Can you give some example of what you're talking about? (i.e. for a given toplevel item, can you reproduce the type displayed in the "code lense", and the one returned by "type on hover"?)

If I understood the issue correctly:

![image](https://user-images.githubusercontent.com/10106819/68532279-51365a80-0313-11ea-8b5f-3fb90887b433.png)

(merlin `2b0ce3a42`)

**Comment by etanter** [comment]
Hi, I'm the one who posted the linked issue from the VCode Ocaml Platform extension, which was tracked down to this Merlin issue. I see it has been open for over a year already -- is there any hope of seeing this fixed anytime soon?
Thanks!
