### ISSUE TITLE
Large stacktraces in Emacs when upgrading to Ocaml 4.08.0

### ISSUE THREAD

**Issue by benkonz** [ocaml/merlin#972]
I'm getting large stack traces in Emacs when I hover over errors and try to autocomplete some of the modules added in Ocaml 4.08 (`Option`, `Int`, etc.). 

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/18561476/59565494-64722200-9022-11e9-9757-0061624b6fc8.png">

Is there a way to fix this?

**Comment by benkonz** [comment]
I'm pretty sure this was getting caused by conflicting installs of `merlin`. Removing the old install of `merlin` fixed the stack traces.

**Comment by aatxe** [comment]
I seem to be having this same issue, but I don't think I have conflicting installs of `merlin`. I even uninstalled the one on my system switch to be safe.

**Comment by benkonz** [comment]
Interesting, I'll re-open this issue

**Comment by aatxe** [comment]
Can you clarify how you ended up with conflicting installs and what you did to rectify that?

**Comment by benkonz** [comment]
I used `opam switch create 4.08.0` to install the new compiler while also having version 4.07.1 as my default switch and `merlin` was installed for both compiler switches.

**Comment by aatxe** [comment]
I removed my old 4.07.1 switch entirely just now, and it's still reproducing.

Here's the full stack trace (since it's not totally visible in your screenshot):
```
Error from syntax checker ocaml-merlin: unknown answer: "exception":"Syntaxerr.Error(_)
Raised at file \"parser_raw.mly\", line 176, characters 4-65
Called from file \"parser_raw.mly\", line 1913, characters 5-48
Called from file \"src/utils/menhirLib.ml\", line 1885, characters 18-44
Called from file \"src/utils/std.ml\", line 93, characters 17-25
Called from file \"src/kernel/mreader_recover.ml\", line 210, characters 10-57
Called from file \"src/kernel/mreader_recover.ml\", line 248, characters 28-38
Called from file \"src/kernel/mreader_parser.ml\", line 130, characters 21-35
Called from file \"src/kernel/mreader_parser.ml\", line 175, characters 20-48
Called from file \"src/kernel/mreader_parser.ml\", line 190, characters 6-42
Called from file \"src/ocaml/utils/misc.ml\", line 30, characters 8-15
Re-raised at file \"src/ocaml/utils/misc.ml\", line 42, characters 10-24
Called from file \"src/kernel/mreader_parser.ml\", line 204, characters 20-56
Called from file \"src/kernel/mreader.ml\", line 49, characters 15-77
Called from file \"src/kernel/mpipeline.ml\", line 103, characters 19-62
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Re-raised at file \"src/kernel/mpipeline.ml\", line 15, characters 34-49
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Re-raised at file \"src/kernel/mpipeline.ml\", line 15, characters 34-49
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Re-raised at file \"src/kernel/mpipeline.ml\", line 15, characters 34-49
Called from file \"camlinternalLazy.ml\", line 29, characters 17-27
Re-raised at file \"camlinternalLazy.ml\", line 36, characters 4-11
Called from file \"src/kernel/mpipeline.ml\" (inlined), line 78, characters 21-30
Called from file \"src/frontend/query_commands.ml\", line 64, characters 14-45
Called from file \"src/frontend/new/new_commands.ml\", line 65, characters 15-53
Called from file \"src/utils/std.ml\", line 679, characters 8-12
Re-raised at file \"src/utils/std.ml\", line 681, characters 30-39
Called from file \"src/ocaml/utils/misc.ml\", line 30, characters 8-15
Re-raised at file \"src/ocaml/utils/misc.ml\", line 42, characters 10-24
Called from file \"src/frontend/new/new_merlin.ml\", line 99, characters 18-54
"
```

**Comment by benkonz** [comment]
I guess I assumed the issue was an issue with my environment (arch linux + emacs + doom emacs + opam + ocaml + tuareg), good to know that someone was able to replicate it

**Comment by aatxe** [comment]
Hm, some added info: I think it _might_ (at least in my case) be related to the use (possibly misuse only) of the new 4.08 user-defined binding operators (https://caml.inria.fr/pub/distrib/ocaml-4.08/ocaml-4.08-refman.html#s%3Abinding-operators). In a file with a syntax error in their use, the error above happens, but if I solve the syntax error, it appears to work correctly.

**Comment by trefis** [comment]
@aatxe : your issue is different from the one in the original post.
Your issue is due to a bug in the handling of syntax errors that @let-def is currently looking at. We hope to do another minor release next week.

**Comment by trefis** [comment]
> When I try to do something like merlin-type-enclosing inside something like let* x = e1 in e2 (e.g. on e1), merlin will give me the type of the whole thing, i.e. the type of e2. So, maybe there's a larger issue with merlin and tthe new user-defined binding operators.

If you don't mind opening a dedicated issue I will have a look at that.

**Comment by benkonz** [comment]
Closing this, since it looks like PR #987 fixed the issue. Thanks everyone!
