### ISSUE TITLE
merlin-type-enclosing does not behave as expected with user-defined binding operators

### ISSUE THREAD

**Issue by aatxe** [ocaml/merlin#985]
When I try to do something like `merlin-type-enclosing` inside something like `let* x = e1 in e2 `(e.g. on e1), merlin will give me the type of the whole thing, i.e. the type of `e2`. This includes if `e1` is actually a function application and I attempt to use `merlin-type-enclosing` on one of the arguments to that function application.

For instance,
```ocaml
let* foo = do_something bar baz
in something_else
```

Performing `merlin-type-enclosing` on `bar` or `baz` will highlight the whole expression (`let* ... in something_else`) shown and give its type, i.e. the type of `something_else`.

(I had originally brought this up in the context of #972, but was directed to open a new issue)

cc @trefis

**Comment by trefis** [comment]
I believe this should have become (slightly) better in v3.3.2.
Can you confirm?
