### ISSUE TITLE
Monomorphic holes

### ISSUE THREAD

**Issue by aalekseyev** [ocaml/merlin#998]
Currently if you ask merlin for the type of a hole (`(??)`) it just always gives you `'a`.
It would be nice if instead it printed the actual expected type.

Consider an example:

```
let f x = 
  if (??) x 
  then (??) 3
  else 8
```

Here it's clear what the types of holes are and in fact you can force this information out of merlin by representing holes differently:

```
let f x =
  if (assert false) x
  then (assert false) 3
  else 8
```

Here if you ask for the types of hole1 and hole2 you get what you want. The types are  `'_a -> bool` and `hole2 : int -> int` respectively.

**Comment by let-def** [comment]
This is the behavior I get with current master for OCaml 4.08.1

**Comment by aalekseyev** [comment]
I do too.
