### ISSUE TITLE
Graph.add: module already defined

### ISSUE THREAD

**Issue by MattWindsor91** [ocaml/merlin#999]
Similar issue to #907, appears when I try to save (or, in neovim/ale, occasionally while I'm editing) code with module-related semantic errors.

- Merlin 3.3.2
- OCaml 4.08
- Noticed in both emacs (26.2) and neovim (0.3.8, with ale 2.5.0, python 3.7.4)

In neovim, the backtrace is:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/Users/mattbw/.opam/act_408/share/merlin/vim/autoload/merlin.py", line 398, in vim_loclist
    errors = command("errors")
  File "/Users/mattbw/.opam/act_408/share/merlin/vim/autoload/merlin.py", line 188, in command
    return command2(args)
  File "/Users/mattbw/.opam/act_408/share/merlin/vim/autoload/merlin.py", line 181, in command2
    raise Failure(value)
Failure: u'Graph.add: module already defined'
```

I haven't been able to come up with a convincing MWE for this: the examples I've seen seemingly all involve trying to apply a functor to a module that doesn't match its signature (or exist, etc.), but trying to reconstruct the issue as of yet hasn't triggered anything.

**Comment by trefis** [comment]
Thanks for the report.
Ping @lpw25 .

**Comment by Cjen1** [comment]
I just started getting this as well. Here is a small test case showing it: 

foo.ml
```
module type S = sig
  type t

  val foo : int -> t
end

module Functor (S: S) : sig
  val bar : int -> S.t 
end = struct
  let bar i = 
     S.foo i
  end
```

bar.ml
```
open Foo

type t = int

module Bar = Functor (struct
    type t = int

    let foo i = i 
    end)
```

If anything in the module getting passed into Functor changes to make it not conform to the signature, the error is observed. e.g. changing the return type of `foo` to be a string.

**Comment by trefis** [comment]
I just fixed @Cjen1's issue, and given the lack of reproduction case I'm going to assume that the original issue was the same. (which seems likely)
